      *{TOTEM}PRG-COMMENT
      * extmovedi.Cbl
      * extmovedi.Cbl is generated by TOTEM
      * This is a generated file. DO NOT modify this file directly.
      *{TOTEM}END
       IDENTIFICATION       DIVISION.
      *{TOTEM}PRGID
       PROGRAM-ID.          extmovedi.
       AUTHOR.              andre.
       DATE-WRITTEN.        mercoledì 14 aprile 2021 20:25:04.
       REMARKS.
      *{TOTEM}END

       ENVIRONMENT          DIVISION.
       CONFIGURATION        SECTION.
       SPECIAL-NAMES.
      *{TOTEM}SPECIAL-NAME
      * <TOTEM:EPT. INIT:extmovedi, INIT:extmovedi, SpecialName>
      * <TOTEM:END>
      *{TOTEM}END
      *{TOTEM}ACTIVEX-DEF
      *{TOTEM}END
      *{TOTEM}DECIMAL-POINT
           DECIMAL-POINT IS COMMA.
      *{TOTEM}END

       INPUT-OUTPUT         SECTION.
       FILE-CONTROL.
      *{TOTEM}FILE-CONTROL
      *{TOTEM}END
       DATA                 DIVISION.
       FILE                 SECTION.
      *{TOTEM}FILE
      *{TOTEM}END

       WORKING-STORAGE      SECTION.
      *{TOTEM}ACU-DEF
               COPY "acugui.def".
               COPY "acucobol.def".
               COPY "fonts.def".
               COPY "crtvars.def".
               COPY "showmsg.def".
               COPY "totem.def".
               COPY "standard.def".
      *{TOTEM}END

      *{TOTEM}COPY-WORKING
      * Key Status
       77 Key-Status IS SPECIAL-NAMES CRT STATUS PIC 9(5) VALUE 0.
          88 Enter-Pushed VALUE 13.
          88 Exit-Pushed VALUE 27.
          88 Message-Received VALUE 95.
          88 Event-Occurred VALUE 96.
          88 Screen-No-Input-Field VALUE 97.
          88 Screen-Time-Out VALUE 99.
      * Properties & User defined Working Stoarge
       78 titolo VALUE IS "Estrazione movimenti UTF telematici". 
       77 E-ESCI           PIC  9
                  VALUE IS 1.
       77 E-NUOVO          PIC  9
                  VALUE IS 1.
       77 E-CANCELLA       PIC  9
                  VALUE IS 1.
       77 E-SALVA          PIC  9
                  VALUE IS 1.
       77 Small-Font
                  USAGE IS HANDLE OF FONT SMALL-FONT.
       77 Default-Font
                  USAGE IS HANDLE OF FONT DEFAULT-FONT.
       77 form1-Handle
                  USAGE IS HANDLE OF WINDOW.
       77 AUTO-ID          PIC  9(6)
                  VALUE IS 0.
       77 ok-73x21-bmp     PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 cancel-73x21-bmp PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 BLUE-FINO-28X24-BMP          PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 BLUE-DA-28X24-BMP            PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 como-data-to     PIC  9(8).
       77 como-data-from   PIC  9(8).
       77 Form1-Tb-1-Handlea
                  USAGE IS HANDLE OF WINDOW.
       77 E-CERCA          PIC  9
                  VALUE IS 0.
       77 ef-data-from-buf PIC  99/99/9999.
       77 ef-data-to-buf   PIC  99/99/9999.
       77 ESCI-73X21-BMP   PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 bottone-ok-bmp   PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 bottone-cancel-bmp           PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 BOTTONE-EXIT-BMP PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 Verdana12-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 Screen1-Handle
                  USAGE IS HANDLE OF WINDOW.
       77 Verdana12B-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 toolbar-bmp      PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 link-user        PIC  x(20).
       77 STATUS-tvettori  PIC  X(2).
           88 Valid-STATUS-tvettori VALUE IS "00" THRU "09". 
       77 ef-vet-buf       PIC  z(5).
       77 lab-vet-buf      PIC  X(50)
                  VALUE IS "<<HELP>> 0 = Tutti i vettori".
       77 Verdana12BI-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 scr-elab-handle
                  USAGE IS HANDLE OF WINDOW.
       77 v-screen1        PIC  9
                  VALUE IS 1.
       77 scr-fine-SF-HANDLE
                  USAGE IS HANDLE OF WINDOW.
       77 mov-da           PIC  z(8).
       77 mov-a            PIC  z(8).
       77 tot-mov          PIC  z(10).
       77 tot-ent          PIC  z.zzz.zzz.zz9.
       77 tot-edi          PIC  z(10).

      ***********************************************************
      *   Code Gen's Buffer                                     *
      ***********************************************************
       77 STATUS-Form1-FLAG-REFRESH PIC  9.
          88 Form1-FLAG-REFRESH  VALUE 1 FALSE 0. 
       77 STATUS-scr-elab-FLAG-REFRESH PIC  9.
          88 scr-elab-FLAG-REFRESH  VALUE 1 FALSE 0. 
       77 STATUS-scr-fine-FLAG-REFRESH PIC  9.
          88 scr-fine-FLAG-REFRESH  VALUE 1 FALSE 0. 
           copy "link-extmovedi.def".
           copy "splcrt2graf.lks".
      *{TOTEM}END

      *{TOTEM}ID-LOGICI
      ***** Elenco ID Logici *****
       78  78-ID-ef-data-from VALUE 5001.
       78  78-ID-ef-data-to VALUE 5002.
      ***** Fine ID Logici *****
      *{TOTEM}END

       LINKAGE          SECTION.
      *{TOTEM}LINKAGE
           COPY  "COMMON-LINKAGE.DEF".
      *{TOTEM}END

       SCREEN           SECTION.
      *{TOTEM}COPY-SCREEN
      * FORM
       01 
           Form1, 
           AFTER PROCEDURE  Form1-AFTER-SCREEN
           .

      * FRAME
       05
           frame-limiti, 
           Frame, 
           COL 1,50, 
           LINE 1,17,
           LINES 4,33 ,
           SIZE 41,20 ,
           ID IS 9,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TITLE "Selezione limiti",
           TITLE-POSITION 2,
           .

      * ENTRY FIELD
       05
           ef-data-from, 
           Entry-Field, 
           COL 3,20, 
           LINE 2,94,
           LINES 1,33 ,
           SIZE 10,50 ,
           BOXED,
           COLOR IS 513,
           ENABLED 1,
           ID IS 78-ID-ef-data-from,                
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           CENTER,
           NUMERIC,
           VALUE ef-data-from-buf,
           AFTER PROCEDURE ef-data-from-AfterProcedure, 
           BEFORE PROCEDURE ef-data-from-BeforeProcedure, 
           .


      * ENTRY FIELD
       05
           ef-data-to, 
           Entry-Field, 
           COL 30,50, 
           LINE 2,94,
           LINES 1,33 ,
           SIZE 10,50 ,
           BOXED,
           COLOR IS 513,
           ENABLED 1,
           ID IS 78-ID-ef-data-to,                
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           CENTER,
           NUMERIC,
           VALUE ef-data-to-buf,
           AFTER PROCEDURE ef-data-to-AfterProcedure, 
           BEFORE PROCEDURE ef-data-to-BeforeProcedure, 
           .


      * LABEL
       05
           Screen3-La-1a, 
           Label, 
           COL 18,70, 
           LINE 2,95,
           LINES 1,33 ,
           SIZE 7,00 ,
           ID IS 100,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           CENTER,
           TRANSPARENT,
           TITLE "Data",
           .

      * BITMAP
       05
           Bitmap-freccia-fino, 
           Bitmap, 
           COL 26,70, 
           LINE 2,94,
           LINES 24,00 ,
           SIZE 28,00 ,
           TRANSPARENT-COLOR TR-COLOR,
           BITMAP-HANDLE BLUE-FINO-28X24-BMP,
           BITMAP-NUMBER 1,
           ID IS 13,
           .

      * BITMAP
       05
           Bitmap-freccia-da, 
           Bitmap, 
           COL 14,70, 
           LINE 2,94,
           LINES 24,00 ,
           SIZE 28,00 ,
           TRANSPARENT-COLOR TR-COLOR,
           BITMAP-HANDLE BLUE-DA-28X24-BMP,
           BITMAP-NUMBER 1,
           ID IS 14,
           .

      * LABEL
       05
           Screen4-blockpgm-1, 
           Label, 
           COL 20,00, 
           LINE 2,17,
           LINES 0,44 ,
           SIZE 1,60 ,
           ID IS 1,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "BlockPgm",
           VISIBLE v-custom,
           .

      * LABEL
       05
           Screen4-Custom1-2, 
           Label, 
           COL 4,00, 
           LINE 2,06,
           LINES 0,50 ,
           SIZE 2,20 ,
           ID IS 8,
           TRANSPARENT,
           TITLE "CUSTOM CONTROL",
           VISIBLE v-custom,
           .

      * FRAME
       05
           Screen4-Fr-1, 
           Frame, 
           COL 1,00, 
           LINE 5,72,
           LINES 2,78 ,
           SIZE 41,70 ,
           LOWERED,
           ID IS 29,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           .

      * PUSH BUTTON
       05
           pb-ok, 
           Push-Button, 
           COL 26,50, 
           LINE 6,41,
           LINES 30,00 ,
           SIZE 73,00 ,
           BITMAP-HANDLE BOTTONE-OK-BMP,
           BITMAP-NUMBER 1,
           UNFRAMED,
           SQUARE,
           EXCEPTION-VALUE 1000,
           FLAT,
           ID IS 200,
           AFTER PROCEDURE pb-ok-AfterProcedure, 
           BEFORE PROCEDURE pb-ok-BeforeProcedure, 
           .

      * PUSH BUTTON
       05
           pb-annulla, 
           Push-Button, 
           COL 34,30, 
           LINE 6,41,
           LINES 30,00 ,
           SIZE 73,00 ,
           BITMAP-HANDLE BOTTONE-CANCEL-BMP,
           BITMAP-NUMBER 1,
           UNFRAMED,
           SQUARE,
           EXCEPTION-VALUE 27,
           FLAT,
           ID IS 201,
           SELF-ACT,
           ESCAPE-BUTTON,
           AFTER PROCEDURE pb-annulla-AfterProcedure, 
           BEFORE PROCEDURE pb-annulla-BeforeProcedure, 
           .

      * FORM
       01 
           scr-elab, 
           AFTER PROCEDURE  scr-elab-AFTER-SCREEN
           .

      * LABEL
       05
           Screen1-La-1b, 
           Label, 
           COL 2,00, 
           LINE 1,67,
           LINES 1,00 ,
           SIZE 18,00 ,
           ID IS 2,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           CENTER,
           TRANSPARENT,
           TITLE "Estrazione in corso...",
           .

      * FORM
       01 
           scr-fine, 
           HELP-ID 1,
           AFTER PROCEDURE  scr-fine-AFTER-SCREEN
           .

      * FRAME
       05
           Screen1-Fr-1a, 
           Frame, 
           COL 2,10, 
           LINE 1,30,
           LINES 12,20 CELLS,
           SIZE 32,80 CELLS,
           ID IS 3,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           .

      * LABEL
       05
           scr-fine-La-4ab, 
           Label, 
           COL 3,20, 
           LINE 4,90,
           LINES 2,00 CELLS,
           SIZE 30,50 CELLS,
           ID IS 22,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           CENTER,
           TRANSPARENT,
           TITLE "Totale Mov. UTF telematici generati",
           .

      * LABEL
       05
           lbl-tot-EDI, 
           Label, 
           COL 13,50, 
           LINE 7,90,
           LINES 2,00 CELLS,
           SIZE 10,00 CELLS,
           COLOR IS 5,
           ID IS 23,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           CENTER,
           TRANSPARENT,
           TITLE tot-edi,
           .

      * PUSH BUTTON
       05
           pb-sia, 
           Push-Button, 
           COL 14,40, 
           LINE 13,90,
           LINES 30,00 ,
           SIZE 73,00 ,
           BITMAP-HANDLE BOTTONE-OK-BMP,
           BITMAP-NUMBER 2,
           UNFRAMED,
           SQUARE,
           EXCEPTION-VALUE 27,
           FLAT,
           ID IS 10,
           ESCAPE-BUTTON,
           AFTER PROCEDURE pb-sia-AfterProcedure, 
           BEFORE PROCEDURE pb-sia-BeforeProcedure, 
           .

      * PUSH BUTTON
       05
           scr-fine-Pb-1, 
           Push-Button, 
           COL 35,10, 
           LINE 17,20,
           LINES 0,80 CELLS,
           SIZE 0,90 CELLS,
           ID IS 24,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           .

      * PUSH BUTTON
       05
           scr-fine-Pb-1a, 
           Push-Button, 
           COL 35,10, 
           LINE 1,00,
           LINES 0,80 CELLS,
           SIZE 0,90 CELLS,
           ID IS 7,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           .

      * PUSH BUTTON
       05
           scr-fine-Pb-1b, 
           Push-Button, 
           COL 1,00, 
           LINE 17,20,
           LINES 0,80 CELLS,
           SIZE 0,90 CELLS,
           ID IS 8,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           .

      * PUSH BUTTON
       05
           scr-fine-Pb-1c, 
           Push-Button, 
           COL 1,00, 
           LINE 1,00,
           LINES 0,80 CELLS,
           SIZE 0,90 CELLS,
           ID IS 9,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           .

      *{TOTEM}END

      *{TOTEM}LINKPARA
       PROCEDURE  DIVISION USING LK-BLOCKPGM, USER-CODI, LIVELLO-ABIL.
      *{TOTEM}END

      *{TOTEM}DECLARATIVE
      *{TOTEM}END

       MAIN-LOGIC.
      *{TOTEM}ENTRY-BEFPRG
      *    Before-Program
           PERFORM ginqui-Ev-Before-Program
      *{TOTEM}END
           PERFORM INITIALIZE-ROUTINE.
      * run main screen
      *{TOTEM}RUN-MAINSCR
           PERFORM Form1-OPEN-ROUTINE.
      *{TOTEM}END

      *{TOTEM}COPY-PROCEDURE
       EXIT-STOP-ROUTINE.
      * <TOTEM:EPT. INIT:extmovedi, INIT:extmovedi, BeforeDestroyResource>
      * <TOTEM:END>
           DESTROY Verdana12-Occidentale
           DESTROY Verdana12BI-Occidentale
           CALL "w$bitmap" USING WBITMAP-DESTROY, BLUE-FINO-28X24-BMP
           CALL "w$bitmap" USING WBITMAP-DESTROY, BLUE-DA-28X24-BMP
           CALL "w$bitmap" USING WBITMAP-DESTROY, BOTTONE-OK-BMP
           CALL "w$bitmap" USING WBITMAP-DESTROY, BOTTONE-CANCEL-BMP
      *    After-Program
           PERFORM ginqui-Ev-After-Program
           EXIT PROGRAM TOTEM-PgmStatus
           STOP RUN.

       INITIALIZE-ROUTINE.
      *    Before Init
      * initialize program status variable
           Initialize TOTEM-PgmStatus.
      * get system information
           ACCEPT SYSTEM-INFORMATION FROM SYSTEM-INFO.
      * get terminal information
           ACCEPT TERMINAL-ABILITIES FROM TERMINAL-INFO.
      * set font
           PERFORM INIT-FONT.
      * load bitmap
           PERFORM INIT-BMP.
      * load resource
           PERFORM INIT-RES.
      * create pop-up menu
           PERFORM INIT-POPUP.
      *    After Init
           .
    
       INIT-FONT.
      * Verdana12-Occidentale
           INITIALIZE WFONT-DATA Verdana12-Occidentale
           MOVE 12 TO WFONT-SIZE
           MOVE "Verdana" TO WFONT-NAME
           SET WFCHARSET-DONT-CARE TO TRUE
           SET WFONT-BOLD TO FALSE
           SET WFONT-ITALIC TO FALSE
           SET WFONT-UNDERLINE TO FALSE
           SET WFONT-STRIKEOUT TO FALSE
           SET WFONT-FIXED-PITCH TO FALSE
           MOVE 0 TO WFONT-CHAR-SET
           CALL "W$FONT" USING WFONT-GET-FONT, 
                     Verdana12-Occidentale, WFONT-DATA
      * Verdana12BI-Occidentale
           INITIALIZE WFONT-DATA Verdana12BI-Occidentale
           MOVE 12 TO WFONT-SIZE
           MOVE "Verdana" TO WFONT-NAME
           SET WFCHARSET-DONT-CARE TO TRUE
           SET WFONT-BOLD TO TRUE
           SET WFONT-ITALIC TO TRUE
           SET WFONT-UNDERLINE TO FALSE
           SET WFONT-STRIKEOUT TO FALSE
           SET WFONT-FIXED-PITCH TO FALSE
           MOVE 0 TO WFONT-CHAR-SET
           CALL "W$FONT" USING WFONT-GET-FONT, 
                     Verdana12BI-Occidentale, WFONT-DATA
           .

       INIT-BMP.
      * Bitmap-freccia-fino
           COPY RESOURCE "BLUE-FINO-28X24.BMP".
           CALL "w$bitmap" USING WBITMAP-LOAD "BLUE-FINO-28X24.BMP", 
                   GIVING BLUE-FINO-28X24-BMP.
      * Bitmap-freccia-da
           COPY RESOURCE "BLUE-DA-28X24.BMP".
           CALL "w$bitmap" USING WBITMAP-LOAD "BLUE-DA-28X24.BMP", 
                   GIVING BLUE-DA-28X24-BMP.
      * pb-ok
           COPY RESOURCE "BOTTONE-OK.BMP".
           CALL "w$bitmap" USING WBITMAP-LOAD "BOTTONE-OK.BMP", 
                   GIVING BOTTONE-OK-BMP.
      * pb-annulla
           COPY RESOURCE "BOTTONE-CANCEL.BMP".
           CALL "w$bitmap" USING WBITMAP-LOAD "BOTTONE-CANCEL.BMP", 
                   GIVING BOTTONE-CANCEL-BMP.
           .

       INIT-RES.
           .

       INIT-POPUP.
           .


       Form1-Open-Routine.
           PERFORM Form1-Scrn
           PERFORM Form1-Proc
           .

       Form1-Scrn.
           PERFORM Form1-Create-Win
           PERFORM Form1-Init-Value
           PERFORM Form1-Init-Data
      * Tab keystrok settings
      * Tool Bar
           PERFORM Form1-DISPLAY
           .

       Form1-Create-Win.
           Display Independent GRAPHICAL WINDOW
              LINES 7,50,
              SIZE 41,70,
              HEIGHT-IN-CELLS,
              WIDTH-IN-CELLS,
              COLOR 65793,
              CONTROL FONT Verdana12-Occidentale,
              LABEL-OFFSET 23,
              LINK TO THREAD,
              NO SCROLL,
              TITLE-BAR,
              TITLE TITOLO,
              WITH SYSTEM MENU,
              USER-GRAY,
              USER-WHITE,
              No WRAP,
              EVENT PROCEDURE Screen4-Event-Proc,
              HANDLE IS form1-Handle,
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterCreateWin>
      * <TOTEM:END>


      * Tool Bar    
      * Status-bar
           DISPLAY Form1 UPON form1-Handle
      * DISPLAY-COLUMNS settings
           .

       Form1-PROC.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeAccept>
           accept como-data-from from century-date
           move "01"   to como-data-from(7:2)

           move como-data-from(7:2)   to como-data(1:2)
           move como-data-from(5:2)   to como-data(3:2)
           move como-data-from(1:4)   to como-data(5:4)
           move como-data             to ef-data-from-buf
           modify ef-data-from, VALUE ef-data-from-buf

           accept como-data-to from century-date
           evaluate como-data-from(5:2)
           when "01"
           when "03"
           when "05"
           when "07"
           when "08"
           when "10"
           when "12"
                move "31"   to como-data-to(7:2)
           when "02"
                move "28"   to como-data-to(7:2)
           when "04"
           when "06"
           when "09"
           when "11"
                move "30"   to como-data-to(7:2)
           end-evaluate

           move como-data-to(7:2)   to como-data(1:2)
           move como-data-to(5:2)   to como-data(3:2)
           move como-data-to(1:4)   to como-data(5:4)

           move como-data             to ef-data-to-buf
           modify ef-data-to, VALUE ef-data-to-buf

           .
      * <TOTEM:END>
           PERFORM UNTIL Exit-Pushed
              ACCEPT Form1
                 ON EXCEPTION
                    PERFORM Form1-Evaluate-Func
                 MOVE 1 TO TOTEM-Form-Index
              END-ACCEPT
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterEndAccept>
      * <TOTEM:END>
           END-PERFORM
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeDestroyWindow>
      * <TOTEM:END>
           DESTROY form1-Handle
           INITIALIZE Key-Status
           .

       Form1-Evaluate-Func.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterAccept>
      * <TOTEM:END>
           EVALUATE TRUE
              WHEN Exit-Pushed
                 PERFORM Form1-Exit
              WHEN Event-Occurred
                 IF Event-Type = Cmd-Close
                    PERFORM Form1-Exit
                 END-IF
              WHEN Key-Status = 1000
                 PERFORM pb-ok-LinkTo
           END-EVALUATE
      * avoid changing focus
           MOVE 4 TO Accept-Control
           .

       Form1-CLEAR.
           PERFORM Form1-INIT-VALUE
           PERFORM Form1-DISPLAY
           .

       Form1-DISPLAY.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeDisplay>
      * <TOTEM:END>
           DISPLAY Form1 UPON form1-Handle
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterDisplay>
           SET LK-BL-SCRITTURA     TO TRUE.
           MOVE COMO-PROG-ID       TO LK-BL-PROG-ID.
           MOVE FORM1-HANDLE       TO LK-HND-WIN.
           CALL "BLOCKPGM"  USING LK-BLOCKPGM.
           CANCEL "BLOCKPGM".

           .
      * <TOTEM:END>
           .

       Form1-Exit.
      * for main screen
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeExit>
      * <TOTEM:END>
           MOVE 27 TO Key-Status
           .

       Form1-Init-Data.
           MOVE 1 TO TOTEM-Form-Index
           MOVE 0 TO TOTEM-Frame-Index
           .

       Form1-Init-Value.
           MOVE TITOLO TO TOTEM-MSG-TITLE
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, SetDefault>
      * <TOTEM:END>
           PERFORM Form1-FLD-TO-BUF
           .


       Form1-ALLGRID-RESET.
           .

      * for Form's Validation
       Form1-VALIDATION-ROUTINE.
           SET TOTEM-CHECK-OK TO TRUE
           .


       Form1-Buf-To-Fld.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeBufToFld>
      * <TOTEM:END>
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterBufToFld>
      * <TOTEM:END>
           .

       Form1-Fld-To-Buf.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeFldToBuf>
      * <TOTEM:END>
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterFldToBuf>
      * <TOTEM:END>
           .

       Form1-CONTROLLO-OLD.
           set SiSalvato to true.
           if mod = 0 exit paragraph end-if.
           perform Form1-BUF-TO-FLD.
           move 0 to scelta.
           .
       Form1-EXTENDED-FILE-STATUS.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
           MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           PERFORM Form1-SHOW-MSG-ROUTINE
           .

       Form1-SHOW-MSG-ROUTINE.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM Form1-DISPLAY-MESSAGE
           .

       Form1-DISPLAY-MESSAGE.
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

       Form1-Save-Status.
           .             

       Form1-Restore-Status.
           .


      * Paragrafo per la struttura del codice in AFTER sulla screen Form1
      ***---
       Form1-AFTER-SCREEN.

      * Generazione risettaggio keyboard "." ---> "."

      * Generazione stringa perform CONTROLLO
           evaluate control-id
           |78-ID-ef-data-from è l'ID del campo ef-data-from
           when 78-ID-ef-data-from
                perform CONTROLLO
           |78-ID-ef-data-to è l'ID del campo ef-data-to
           when 78-ID-ef-data-to
                perform CONTROLLO
           |99999 è un valore fittizio, che non sarà MAI usato,
           |ma mi serve per non riscontrare errori di compilazione
           |in caso non avessi generato nulla nella AFTER CONTROLLO della screen
           when 99999 continue
           when other continue
           end-evaluate.

       scr-elab-Open-Routine.
           PERFORM scr-elab-Scrn
           PERFORM scr-elab-Proc
           .

       scr-elab-Scrn.
           PERFORM scr-elab-Create-Win
           PERFORM scr-elab-Init-Value
           PERFORM scr-elab-Init-Data
      * Tab keystrok settings
      * Tool Bar
           PERFORM scr-elab-DISPLAY
           .

       scr-elab-Create-Win.
           Display Independent GRAPHICAL WINDOW
              LINES 3,00,
              SIZE 20,00,
              HEIGHT-IN-CELLS,
              WIDTH-IN-CELLS,
              COLOR 65793,
              CONTROL FONT Verdana12BI-Occidentale,
              LINK TO THREAD,
              NO SCROLL,
              USER-GRAY,
           VISIBLE v-screen1,
              USER-WHITE,
              No WRAP,
              EVENT PROCEDURE Screen1-Event-Proc,
              HANDLE IS scr-elab-handle,
      * <TOTEM:EPT. FORM:scr-elab, FORM:scr-elab, AfterCreateWin>
      * <TOTEM:END>


      * Tool Bar    
      * Status-bar
           DISPLAY scr-elab UPON scr-elab-handle
      * DISPLAY-COLUMNS settings
           .

       scr-elab-PROC.
      * <TOTEM:EPT. FORM:scr-elab, FORM:scr-elab, BeforeAccept>
           call "W$MOUSE" using set-mouse-shape, wait-pointer

           initialize extmovedi-linkage.
           move como-data-from  to extmovedi-mov-gen-da
           move como-data-to    to extmovedi-mov-gen-a
           move user-codi to extmovedi-user.
           move scr-elab-handle to extmovedi-handle.
           call   "extmovedi-p" using extmovedi-linkage.
           cancel "extmovedi-p".
           move 27 to key-status.

           call "W$MOUSE" using set-mouse-shape, arrow-pointer

           .
      * <TOTEM:END>
           PERFORM UNTIL Exit-Pushed
              ACCEPT OMITTED LINE 1 COL 1
                 ON EXCEPTION
                    PERFORM scr-elab-Evaluate-Func
                 MOVE 2 TO TOTEM-Form-Index
              END-ACCEPT
      * <TOTEM:EPT. FORM:scr-elab, FORM:scr-elab, AfterEndAccept>
      * <TOTEM:END>
           END-PERFORM
      * <TOTEM:EPT. FORM:scr-elab, FORM:scr-elab, BeforeDestroyWindow>
      * <TOTEM:END>
           DESTROY scr-elab-handle
           INITIALIZE Key-Status
           .

       scr-elab-Evaluate-Func.
      * <TOTEM:EPT. FORM:scr-elab, FORM:scr-elab, AfterAccept>
      * <TOTEM:END>
           EVALUATE TRUE
              WHEN Exit-Pushed
                 PERFORM scr-elab-Exit
              WHEN Event-Occurred
                 IF Event-Type = Cmd-Close
                    PERFORM scr-elab-Exit
                 END-IF
           END-EVALUATE
      * avoid changing focus
           MOVE 4 TO Accept-Control
           .

       scr-elab-CLEAR.
           PERFORM scr-elab-INIT-VALUE
           PERFORM scr-elab-DISPLAY
           .

       scr-elab-DISPLAY.
      * <TOTEM:EPT. FORM:scr-elab, FORM:scr-elab, BeforeDisplay>
      * <TOTEM:END>
           DISPLAY scr-elab UPON scr-elab-handle
      * <TOTEM:EPT. FORM:scr-elab, FORM:scr-elab, AfterDisplay>
      *<<** Customized_Default, SP-G, Screen4-blockpgm-1, Disable **>>

           .
      * <TOTEM:END>
           .

       scr-elab-Exit.
      * for main screen
      * <TOTEM:EPT. FORM:scr-elab, FORM:scr-elab, BeforeExit>
      * <TOTEM:END>
           MOVE 27 TO Key-Status
           .

       scr-elab-Init-Data.
           MOVE 2 TO TOTEM-Form-Index
           MOVE 0 TO TOTEM-Frame-Index
           .

       scr-elab-Init-Value.
      * <TOTEM:EPT. FORM:scr-elab, FORM:scr-elab, SetDefault>
      * <TOTEM:END>
           PERFORM scr-elab-FLD-TO-BUF
           .


       scr-elab-ALLGRID-RESET.
           .

      * for Form's Validation
       scr-elab-VALIDATION-ROUTINE.
           SET TOTEM-CHECK-OK TO TRUE
           .


       scr-elab-Buf-To-Fld.
      * <TOTEM:EPT. FORM:scr-elab, FORM:scr-elab, BeforeBufToFld>
      * <TOTEM:END>
      * <TOTEM:EPT. FORM:scr-elab, FORM:scr-elab, AfterBufToFld>
      * <TOTEM:END>
           .

       scr-elab-Fld-To-Buf.
      * <TOTEM:EPT. FORM:scr-elab, FORM:scr-elab, BeforeFldToBuf>
      * <TOTEM:END>
      * <TOTEM:EPT. FORM:scr-elab, FORM:scr-elab, AfterFldToBuf>
      * <TOTEM:END>
           .

       scr-elab-CONTROLLO-OLD.
           set SiSalvato to true.
           if mod = 0 exit paragraph end-if.
           perform scr-elab-BUF-TO-FLD.
           move 0 to scelta.
           .
       scr-elab-EXTENDED-FILE-STATUS.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
           MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           PERFORM scr-elab-SHOW-MSG-ROUTINE
           .

       scr-elab-SHOW-MSG-ROUTINE.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM scr-elab-DISPLAY-MESSAGE
           .

       scr-elab-DISPLAY-MESSAGE.
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

       scr-elab-Save-Status.
           .             

       scr-elab-Restore-Status.
           .


      * Paragrafo per la struttura del codice in AFTER sulla screen scr-elab
      ***---
       scr-elab-AFTER-SCREEN.

      * Generazione risettaggio keyboard "." ---> "."

      * Generazione stringa perform CONTROLLO
           evaluate control-id
           |99999 è un valore fittizio, che non sarà MAI usato,
           |ma mi serve per non riscontrare errori di compilazione
           |in caso non avessi generato nulla nella AFTER CONTROLLO della screen
           when 99999 continue
           when other continue
           end-evaluate.

       scr-fine-Open-Routine.
           PERFORM scr-fine-Scrn
           PERFORM scr-fine-Proc
           .

       scr-fine-Scrn.
           PERFORM scr-fine-Create-Win
           PERFORM scr-fine-Init-Value
           PERFORM scr-fine-Init-Data
      * Tab keystrok settings
      * Tool Bar
           PERFORM scr-fine-DISPLAY
           .

       scr-fine-Create-Win.
           Display Floating GRAPHICAL WINDOW
              LINES 17,00,
              SIZE 35,00,
              CELL HEIGHT 10,
              CELL WIDTH 10,
              HEIGHT-IN-CELLS,
              WIDTH-IN-CELLS,
              COLOR 65793,
              ERASE,
              CONTROL FONT Verdana12-Occidentale,
              LABEL-OFFSET 0,
              LINK TO THREAD,
              MODELESS,
              RESIZABLE,
              NO SCROLL,
              TITLE-BAR,
              TITLE "Operazione conclusa - Riepilogo",
              WITH SYSTEM MENU,
              USER-GRAY,
              USER-WHITE,
              No WRAP,
              HANDLE IS scr-fine-SF-HANDLE,
      * <TOTEM:EPT. FORM:scr-fine, FORM:scr-fine, AfterCreateWin>
      * <TOTEM:END>


      * Tool Bar    
      * Status-bar
           DISPLAY scr-fine UPON scr-fine-SF-HANDLE
      * DISPLAY-COLUMNS settings
           .

       scr-fine-PROC.
      * <TOTEM:EPT. FORM:scr-fine, FORM:scr-fine, BeforeAccept>
           move extmovedi-tot-edi     to tot-edi
           display scr-fine.

           .
      * <TOTEM:END>
           PERFORM UNTIL Exit-Pushed
              ACCEPT scr-fine
                 ON EXCEPTION
                    PERFORM scr-fine-Evaluate-Func
                 MOVE 3 TO TOTEM-Form-Index
              END-ACCEPT
      * <TOTEM:EPT. FORM:scr-fine, FORM:scr-fine, AfterEndAccept>
      * <TOTEM:END>
           END-PERFORM
      * <TOTEM:EPT. FORM:scr-fine, FORM:scr-fine, BeforeDestroyWindow>
      * <TOTEM:END>
           DESTROY scr-fine-SF-HANDLE
           INITIALIZE Key-Status
           .

       scr-fine-Evaluate-Func.
      * <TOTEM:EPT. FORM:scr-fine, FORM:scr-fine, AfterAccept>
      * <TOTEM:END>
           EVALUATE TRUE
              WHEN Exit-Pushed
                 PERFORM scr-fine-Exit
              WHEN Event-Occurred
                 IF Event-Type = Cmd-Close
                    PERFORM scr-fine-Exit
                 END-IF
              WHEN Key-Status = 27
                 PERFORM pb-si-LinkTo
           END-EVALUATE
      * avoid changing focus
           MOVE 4 TO Accept-Control
           .

       scr-fine-CLEAR.
           PERFORM scr-fine-INIT-VALUE
           PERFORM scr-fine-DISPLAY
           .

       scr-fine-DISPLAY.
      * <TOTEM:EPT. FORM:scr-fine, FORM:scr-fine, BeforeDisplay>
      * <TOTEM:END>
           DISPLAY scr-fine UPON scr-fine-SF-HANDLE
      * <TOTEM:EPT. FORM:scr-fine, FORM:scr-fine, AfterDisplay>
      *<<** Customized_Default, SP-G, Screen4-blockpgm-1, Disable **>>

           .
      * <TOTEM:END>
           .

       scr-fine-Exit.
      * for main screen
      * <TOTEM:EPT. FORM:scr-fine, FORM:scr-fine, BeforeExit>
      * <TOTEM:END>
           MOVE 27 TO Key-Status
           .

       scr-fine-Init-Data.
           MOVE 3 TO TOTEM-Form-Index
           MOVE 0 TO TOTEM-Frame-Index
           .

       scr-fine-Init-Value.
      * <TOTEM:EPT. FORM:scr-fine, FORM:scr-fine, SetDefault>
      * <TOTEM:END>
           PERFORM scr-fine-FLD-TO-BUF
           .


       scr-fine-ALLGRID-RESET.
           .

      * for Form's Validation
       scr-fine-VALIDATION-ROUTINE.
           SET TOTEM-CHECK-OK TO TRUE
           .


       scr-fine-Buf-To-Fld.
      * <TOTEM:EPT. FORM:scr-fine, FORM:scr-fine, BeforeBufToFld>
      * <TOTEM:END>
      * <TOTEM:EPT. FORM:scr-fine, FORM:scr-fine, AfterBufToFld>
      * <TOTEM:END>
           .

       scr-fine-Fld-To-Buf.
      * <TOTEM:EPT. FORM:scr-fine, FORM:scr-fine, BeforeFldToBuf>
      * <TOTEM:END>
      * <TOTEM:EPT. FORM:scr-fine, FORM:scr-fine, AfterFldToBuf>
      * <TOTEM:END>
           .

       scr-fine-CONTROLLO-OLD.
           set SiSalvato to true.
           if mod = 0 exit paragraph end-if.
           perform scr-fine-BUF-TO-FLD.
           move 0 to scelta.
           .
       scr-fine-EXTENDED-FILE-STATUS.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
           MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           PERFORM scr-fine-SHOW-MSG-ROUTINE
           .

       scr-fine-SHOW-MSG-ROUTINE.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM scr-fine-DISPLAY-MESSAGE
           .

       scr-fine-DISPLAY-MESSAGE.
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

       scr-fine-Save-Status.
           .             

       scr-fine-Restore-Status.
           .


      * Paragrafo per la struttura del codice in AFTER sulla screen scr-fine
      ***---
       scr-fine-AFTER-SCREEN.

      * Generazione risettaggio keyboard "." ---> "."

      * Generazione stringa perform CONTROLLO
           evaluate control-id
           |99999 è un valore fittizio, che non sarà MAI usato,
           |ma mi serve per non riscontrare errori di compilazione
           |in caso non avessi generato nulla nella AFTER CONTROLLO della screen
           when 99999 continue
           when other continue
           end-evaluate.



       Screen4-Event-Proc.
           .

       Screen1-Event-Proc.
           .

      * USER DEFINE PARAGRAPH
       CONTROLLO.
      * <TOTEM:PARA. CONTROLLO>
           set tutto-ok to true.

           evaluate CONTROL-ID
           when 78-ID-ef-data-from                          
                inquire ef-data-from, value in ef-data-from-buf
                move ef-data-from-buf to como-data
                if como-data not = 0
                   perform DATE-FORMAT
                   move como-data to ef-data-from-buf
                end-if
                display ef-data-from
      *                       
           when 78-ID-ef-data-to                              
                inquire ef-data-from, value in ef-data-from-buf
                inquire ef-data-to,   value in ef-data-to-buf
                move ef-data-to-buf to como-data
                if como-data = 0
                   move 99999999  to como-data
                end-if
                if como-data not = 99999999
                   perform DATE-FORMAT
                   move como-data to ef-data-to-buf
                end-if

                move como-data to ef-data-to-buf
                display ef-data-to

                perform DATE-TO-FILE
                move como-data        to como-data-to

                move ef-data-from-buf to como-data
                perform DATE-TO-FILE
                move como-data    to como-data-from

                if como-data-to < como-data-from
                   set errori to true
                   display message box "Intervallo limiti data errato!"
                           title = tit-err
                           icon 2
                   move 78-ID-ef-data-from to control-id
                end-if

           end-evaluate.

           if errori
              perform CANCELLA-COLORE
              move control-id to store-id        
              move 4          to accept-control  
           end-if 
           .
      * <TOTEM:END>

       PARAGRAFO-COPY.
      * <TOTEM:PARA. PARAGRAFO-COPY>
           copy "color-custom.cpy".
           copy "utydata.cpy".
           copy "calcola-colore-trasparente.cpy".

      ***--- DUMMY ---> NON TOCCARE!!!!
       STATUS-HELP.
           continue.

      *****     move    intfat-path             to splcrt2graf-percorso-stampa
      *****     set     splcrt2graf-stampa      to true.
      *****     set     splcrt2graf-windows     to true.
      *****     set     splcrt2graf-orizzontale to true.
      *****     set     splcrt2graf-forza-crt   to true.
      *****     set     splcrt2graf-10pt        to true.
      *****     call   "splcrt2graf"   using splcrt2graf-link.
      *****     cancel "splcrt2graf" 
           .
      * <TOTEM:END>

       VIS-REPORT.
      * <TOTEM:PARA. VIS-REPORT>
           move extmovedi-path-no-art    to splcrt2graf-percorso-stampa

           set splcrt2graf-anteprima     to true

           set splcrt2graf-windows       to true
           set splcrt2graf-verticale     to true
           set splcrt2graf-forza-crt     to true
           set splcrt2graf-10pt          to true
           set splcrt2graf-si-grasssetto to false

           call "splcrt2graf" using splcrt2graf-link
           cancel "splcrt2graf" 
           .
      * <TOTEM:END>

      * EVENT PARAGRAPH
       ginqui-Ev-Before-Program.
      * <TOTEM:PARA. ginqui-Ev-Before-Program>
           move LK-BL-PROG-ID    TO COMO-PROG-ID.
           perform CALCOLA-COLORE-TRASPARENTE 
           .
      * <TOTEM:END>
       ginqui-Ev-After-Program.
      * <TOTEM:PARA. ginqui-Ev-After-Program>
           SET LK-BL-CANCELLAZIONE TO TRUE.
           MOVE COMO-PROG-ID       TO LK-BL-PROG-ID.
           CALL "BLOCKPGM"  USING LK-BLOCKPGM 
           .
      * <TOTEM:END>
       ef-data-from-BeforeProcedure.
      * <TOTEM:PARA. ef-data-from-BeforeProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-NU
           .
      * <TOTEM:END>
       ef-data-to-BeforeProcedure.
      * <TOTEM:PARA. ef-data-to-BeforeProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-NU
           .
      * <TOTEM:END>
       ef-data-from-AfterProcedure.
      * <TOTEM:PARA. ef-data-from-AfterProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-OR
           perform CONTROLLO 
           .
      * <TOTEM:END>
       ef-data-to-AfterProcedure.
      * <TOTEM:PARA. ef-data-to-AfterProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-OR
           perform CONTROLLO 
           .
      * <TOTEM:END>
       pb-ok-BeforeProcedure.
      * <TOTEM:PARA. pb-ok-BeforeProcedure>
           modify pb-ok, bitmap-number 2 
           .
      * <TOTEM:END>
       pb-ok-AfterProcedure.
      * <TOTEM:PARA. pb-ok-AfterProcedure>
           modify pb-ok, bitmap-number 1 
           .
      * <TOTEM:END>
       pb-ok-LinkTo.
      * <TOTEM:PARA. pb-ok-LinkTo>
           move CONTROL-ID to mem-id.

           perform  varying CONTROL-ID from 78-ID-ef-data-from by 1
                      until CONTROL-ID > 78-ID-ef-data-to
              perform CONTROLLO
              if errori exit perform end-if
           end-perform.

           if tutto-ok
              modify form1-handle, visible false
              perform SCR-ELAB-OPEN-ROUTINE
              if extmovedi-tot-EDI > 0
                 perform SCR-FINE-OPEN-ROUTINE
              end-if
              modify form1-handle, visible true
              if extmovedi-problemi-art
                 perform VIS-REPORT
              end-if
      *
      *
      *
      *        move user-codi to link-user
      *        call   "ricaltras-p" using como-data-from
      *                                   como-data-to
      *                                   link-user
      *                                   form1-handle
      *        cancel "ricaltras-p"
      *        
      *        modify form1-handle, visible = 1
              modify pb-ok,        bitmap-number = 1
              modify pb-annulla,   bitmap-number = 1
              move 78-ID-ef-data-from   to CONTROL-ID     
              move 4                    to ACCEPT-CONTROL 
           end-if 
           .
      * <TOTEM:END>
       pb-annulla-BeforeProcedure.
      * <TOTEM:PARA. pb-annulla-BeforeProcedure>
           modify pb-annulla, bitmap-number 2 
           .
      * <TOTEM:END>
       pb-annulla-AfterProcedure.
      * <TOTEM:PARA. pb-annulla-AfterProcedure>
           modify pb-annulla, bitmap-number 1 
           .
      * <TOTEM:END>
       pb-sia-BeforeProcedure.
      * <TOTEM:PARA. pb-sia-BeforeProcedure>
           .
      * <TOTEM:END>
       pb-sia-AfterProcedure.
      * <TOTEM:PARA. pb-sia-AfterProcedure>
           .
      * <TOTEM:END>
       pb-si-LinkTo.
      * <TOTEM:PARA. pb-si-LinkTo>
           .
      * <TOTEM:END>

      *{TOTEM}END

      *{TOTEM}SHOW-MSG
       MESSAGE-FOR-FILEERROR.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
              MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           .

       SHOW-TRANSACTION-ROUTINE.
           IF TOTEM-TRANSACTION-FLAG = SPACES
              IF TRANSACTION-STATUS NOT = 0
                 STRING "TRANSACTION ERROR ", TRANSACTION-STATUS
                    DELIMITED BY SIZE INTO TOTEM-MSG-1
              END-IF
           ELSE
              PERFORM SHOW-MSG-ROUTINE
              IF TRANSACTION-STATUS = 0
                 MOVE "Transazione terminata con Rollback." TO 
           TOTEM-MSG-3
              ELSE
                 STRING "TRANSACTION ERROR ", TRANSACTION-STATUS
                    DELIMITED BY SIZE INTO TOTEM-MSG-3
              END-IF
           END-IF
           .

       SHOW-MSG-ROUTINE.
           MOVE SPACE TO TOTEM-MSG-1 TOTEM-MSG-2 TOTEM-MSG-3
           EVALUATE TOTEM-MSG-ID
               WHEN "10"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Nessun altro dato." TO TOTEM-MSG-2
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "22"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Chiave Duplicata." TO TOTEM-MSG-2
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "23"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Raggiunta fine file." TO TOTEM-MSG-2
                    MOVE MB-WARNING-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "101"
                    MOVE "Terminare l'applicazione?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "201"
                    MOVE "Aggiungere un nuovo record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "202"
                    MOVE "Aggiornare il Record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "203"
                    MOVE "Cancellare il Record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "204"
                    MOVE "Chiave duplicata." TO TOTEM-MSG-1
                    MOVE MB-WARNING-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "301"
                    MOVE "Inserimento avvenuto con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "302"
                    MOVE "Aggiornamento avvenuto con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "303"
                    MOVE "Cancellazione avvenuta con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "401"
                    MOVE "Shell non trovata." TO TOTEM-MSG-1
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN OTHER
                    MOVE TEXT-MESSAGE TO TOTEM-MSG-1
                    STRING "FILE:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-3
                    MOVE 0 TO TOTEM-IDX1
                    INSPECT TOTEM-MSG-3 TALLYING TOTEM-IDX1
                       FOR TRAILING SPACE
                    STRING TOTEM-MSG-3(1:TOTEM-MSG-LENGTH - 
           TOTEM-IDX1), 
                       ", FILE STATUS ", PRIMARY-ERROR "," 
                       SECONDARY-ERROR
                    DELIMITED BY SIZE INTO TOTEM-MSG-2
                    MOVE SPACES TO TOTEM-MSG-3
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
           END-EVALUATE
           PERFORM MESSAGE-BOX-ROUTINE
           .

       MESSAGE-BOX-ROUTINE.
           MOVE 1 TO TOTEM-MSG-TEXT-POINTER
           IF TOTEM-MSG-1 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-1 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              STRING TOTEM-MSG-1( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                 DELIMITED BY SIZE
                 INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-2 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-2 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              IF TOTEM-MSG-TEXT-POINTER > 1
                 STRING X"0A" DELIMITED BY SIZE
                     INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
              END-IF
              STRING TOTEM-MSG-2( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                  DELIMITED BY SIZE
                  INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-3 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-3 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              IF TOTEM-MSG-TEXT-POINTER > 1
                 STRING X"0A" DELIMITED BY SIZE
                     INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
              END-IF
              STRING TOTEM-MSG-3( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                  DELIMITED BY SIZE
                  INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-TEXT-POINTER = 1
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-TEXT TALLYING TOTEM-MSG-SIZE FOR 
           TRAILING SPACE
                  COMPUTE TOTEM-MSG-TEXT-POINTER = 
           TOTEM-MSG-FULL-LENGTH - TOTEM-MSG-SIZE + 1
           END-IF
           MOVE LOW-VALUES TO TOTEM-MSG-TEXT(TOTEM-MSG-TEXT-POINTER : 1 
           )
           .

       MESSAGE-BOX-DISPLAY.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

      *{TOTEM}END

