       SELECT OPTIONAL ABI
           ASSIGN       TO RANDOM "ABI"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-ABI
           RECORD KEY   IS ABI-CODICE
           ALTERNATE RECORD KEY IS ABI-CODICE1 = ABI-BANCA1, ABI-CITTA, 
           ABI-BANCA2, ABI-CODICE
           ALTERNATE RECORD KEY IS ABI-CODICE2 = ABI-CITTA, ABI-BANCA1, 
           ABI-BANCA2, ABI-CODICE.
