       SELECT OPTIONAL CLZ
           ASSIGN       TO RANDOM SELCLZ
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-CLZ
           RECORD KEY   IS CLZ-CODICE.
