       SELECT OPTIONAL DES
           ASSIGN       TO RANDOM "DES"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-DES
           RECORD KEY   IS DES-CODICE-G2.
