       SELECT OPTIONAL DOCES
           ASSIGN       TO RANDOM "DOC"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-DOCES
           RECORD KEY   IS DOCES-CODICE.
