       SELECT OPTIONAL FRN
           ASSIGN       TO RANDOM "FRN"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-FRN
           RECORD KEY   IS FRN-CODICE
           ALTERNATE RECORD KEY IS FRN-CODICE1 = 
           FRN-CODICE-ALTERNATIVO, FRN-CODICE
           ALTERNATE RECORD KEY IS FRN-CODICE2 = FRN-DESCRIZIONE1, 
           FRN-CODICE
           ALTERNATE RECORD KEY IS FRN-CODICE3 = FRN-PARTITA-IVA, 
           FRN-CODICE
           ALTERNATE RECORD KEY IS FRN-CODICE4 = FRN-CODICE-FISCALE, 
           FRN-CODICE.
