      ** Righe documento di vendita presente nel direttorio GESLUX
       SELECT GDVR
           ASSIGN       TO  "GDVR"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS status-gdvr
           RECORD KEY   IS DVR-CODICE
           ALTERNATE RECORD KEY IS DVR-CODICE1 = DVR-DATA-DOCUMENTO, 
           DVR-DOCUMENTO, DVR-CODICE
           ALTERNATE RECORD KEY IS DVR-CODICE2 = DVR-CODICE-CONTO, 
           DVR-DATA-DOCUMENTO, DVR-CODICE
           ALTERNATE RECORD KEY IS DVR-CODICE3 = DVR-CODICE-ART, 
           DVR-DATA-DOCUMENTO, DVR-CODICE
           ALTERNATE RECORD KEY IS DVR-CODICE4 = DVR-CODICE-ART, 
           DVR-CODICE-INTESTAZIONE, DVR-DATA-DOCUMENTO, DVR-CODICE.
