      ** Struttura DVT ma usato in direttorio GESLUX per gestire 36 rate
       SELECT GDVT
           ASSIGN       TO  "GDVT"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS status-gdvt
           RECORD KEY   IS DVT-CODICE
           ALTERNATE RECORD KEY IS DVT-CODICE1 = DVT-CODICE-CONTO, 
           DVT-DATA-DOCUMENTO, DVT-CODICE
           ALTERNATE RECORD KEY IS DVT-CODICE2 = DVT-DOCUMENTO, 
           DVT-DATA-DOCUMENTO, DVT-CODICE
           ALTERNATE RECORD KEY IS DVT-CODICE3 = DVT-FATTURA, 
           DVT-DATA-FATTURA, DVT-CODICE
           ALTERNATE RECORD KEY IS DVT-CODICE4 = DVT-PROTOCOLLO, 
           DVT-DATA-PROTOCOLLO, DVT-CODICE
           ALTERNATE RECORD KEY IS DVT-CODICE5 = DVT-DATA-DOCUMENTO, 
           DVT-DOCUMENTO, DVT-CODICE
           ALTERNATE RECORD KEY IS DVT-CODICE6 = DVT-CODICE-CONTO, 
           DVT-CODICE-DO, DVT-SITUAZIONE, DVT-CODICE.
