       SELECT OPTIONAL MAS
           ASSIGN       TO RANDOM "MAS"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-MAS
           RECORD KEY   IS MAS-CODICE
           ALTERNATE RECORD KEY IS MAS-CODICE1 = 
           MAS-CODICE-ALTERNATIVO, MAS-CODICE
           ALTERNATE RECORD KEY IS MAS-CODICE2 = MAS-DESCRIZIONE1, 
           MAS-CODICE.
