       SELECT OPTIONAL PNT
           ASSIGN       TO RANDOM "PNT"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-PNT
           RECORD KEY   IS PNT-CODICE
           ALTERNATE RECORD KEY IS PNT-CODICE1 = 
           PNT-DATA-REGISTRAZIONE, PNT-CODICE
           ALTERNATE RECORD KEY IS PNT-CODICE2 = PNT-PROTOCOLLO, 
           PNT-DATA-REGISTRAZIONE, PNT-CODICE
           ALTERNATE RECORD KEY IS PNT-CODICE3 = PNT-DOCUMENTO, 
           PNT-DATA-DOCUMENTO, PNT-CODICE.
