       SELECT OPTIONAL stv
           ASSIGN       TO RANDOM "STV"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-STV
           RECORD KEY   IS STV-CODICE
           ALTERNATE RECORD KEY IS STV-CODICE1 = STV-CODICE-CLI, 
           STV-DATA-FATTURA, STV-CODICE
           ALTERNATE RECORD KEY IS STV-CODICE2 = STV-CODICE-ART, 
           STV-DATA-FATTURA, STV-CODICE
           ALTERNATE RECORD KEY IS STV-CODICE3 = STV-DATA-FATTURA, 
           STV-CODICE
           ALTERNATE RECORD KEY IS STV-CODICE4 = STV-CODICE-CLI, 
           STV-CODICE-ART, STV-DATA-FATTURA, STV-CODICE.
