      *{TOTEM}PRG-COMMENT
      * sitfin.Cbl
      * sitfin.Cbl is generated by TOTEM
      * This is a generated file. DO NOT modify this file directly.
      *{TOTEM}END
       IDENTIFICATION       DIVISION.
      *{TOTEM}PRGID
       PROGRAM-ID.          sitfin.
       AUTHOR.              ANDREA EVENTI.
       DATE-WRITTEN.        martedì 1 aprile 2014 19:18:56.
       REMARKS.
      *{TOTEM}END

       ENVIRONMENT          DIVISION.
       CONFIGURATION        SECTION.
       SPECIAL-NAMES.
      *{TOTEM}SPECIAL-NAME
      * <TOTEM:EPT. INIT:sitfin, INIT:sitfin, SpecialName>
      * <TOTEM:END>
      *{TOTEM}END
      *{TOTEM}ACTIVEX-DEF
      *{TOTEM}END
      *{TOTEM}DECIMAL-POINT
           DECIMAL-POINT IS COMMA.
      *{TOTEM}END

       INPUT-OUTPUT         SECTION.
       FILE-CONTROL.
      *{TOTEM}FILE-CONTROL
           COPY "tgrupgdo.sl".
           COPY "clienti.sl".
           COPY "sitfin.sl".
           COPY "tparamge.sl".
      *{TOTEM}END
       DATA                 DIVISION.
       FILE                 SECTION.
      *{TOTEM}FILE
           COPY "tgrupgdo.fd".
           COPY "clienti.fd".
           COPY "sitfin.fd".
           COPY "tparamge.fd".
      *{TOTEM}END

       WORKING-STORAGE      SECTION.
      *{TOTEM}ACU-DEF
               COPY "acugui.def".
               COPY "acucobol.def".
               COPY "fonts.def".
               COPY "crtvars.def".
               COPY "showmsg.def".
               COPY "totem.def".
               COPY "F:\Lubex\GESLUX\Copylib\UTYDATA.DEF".
               COPY "F:\Lubex\GESLUX\Copylib\comune.def".
               COPY "F:\Lubex\GESLUX\Copylib\custom.def".
      *{TOTEM}END

      *{TOTEM}COPY-WORKING
      * Key Status
       77 Key-Status IS SPECIAL-NAMES CRT STATUS PIC 9(5) VALUE 0.
          88 Enter-Pushed VALUE 13.
          88 Exit-Pushed VALUE 27.
          88 Message-Received VALUE 95.
          88 Event-Occurred VALUE 96.
          88 Screen-No-Input-Field VALUE 97.
          88 Screen-Time-Out VALUE 99.
      * Properties & User defined Working Stoarge
       77 Screen1-Handle
                  USAGE IS HANDLE OF WINDOW.
       01 verifica-1       PIC  9.
           88 verifica-1-ok VALUE IS 1    WHEN SET TO FALSE  0. 
       01 verifica-2       PIC  9.
           88 verifica-2-ok VALUE IS 1    WHEN SET TO FALSE  0. 
       01 verifica-3       PIC  9.
           88 verifica-3-ok VALUE IS 1    WHEN SET TO FALSE  0. 
       78 titolo VALUE IS "GESLUX - Situazione finanziaria cliente". 
       77 Verdana10-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 mese-rif         PIC  99.
       77 como-anno        PIC  9999.
       77 perce-max-x      PIC  x(6).
       77 perce-max        PIC  9(3)v99.
       77 perce            PIC  9(3)v99.
       77 num  PIC  9(9)v99.
       77 den  PIC  9(9)v99.
       77 PgmChiamante     PIC  x(20).
       01 data-oggi.
           05 anno PIC  9999.
           05 mese PIC  99.
           05 giorno           PIC  99.
       77 Small-Font
                  USAGE IS HANDLE OF FONT SMALL-FONT.
       77 STATUS-clienti   PIC  X(2).
           88 Valid-STATUS-clienti VALUE IS "00" THRU "09". 
       77 Verdana12-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 lab-cliente-buf  PIC  X(100)
                  VALUE IS "Label".
       77 fatto-bmp        PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 Verdana12B-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 Screen1-Bt-1-Handle          PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 stati-bmp        PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 lab-lince-buf    PIC  ----.---.--9,99.
       77 lab-scaduto-buf  PIC  ---.---.--9,99.
       77 fatturato        PIC  s9(9)v99.
       77 como-valore      PIC  s9(9)v99.
       77 scoperto-tot     PIC  s9(9)v99.
       77 max-fido         PIC  s9(9)v99.
       77 STATUS-rmovmag   PIC  X(2).
           88 Valid-STATUS-rmovmag VALUE IS "00" THRU "09". 
       77 STATUS-tmovmag   PIC  X(2).
           88 Valid-STATUS-tmovmag VALUE IS "00" THRU "09". 
       77 STATUS-tparamge  PIC  X(2).
           88 Valid-STATUS-tparamge VALUE IS "00" THRU "09". 
       77 STATUS-tcaumag   PIC  X(2).
           88 Valid-STATUS-tcaumag VALUE IS "00" THRU "09". 
       77 lab-fatt-per-buf PIC  x(50).
       77 lab-fatturato-buf            PIC  ---.---.--9,99.
       77 lab-fido-buf     PIC  ---.---.--9,99.
       77 lab-gg-buf       PIC  zz9.
       77 lab-rb-buf       PIC  ---.---.--9,99.
       77 lab-ordini-buf   PIC  ---.---.--9,99.
       77 lab-tot-scad-buf PIC  ---.---.--9,99.
       77 lab-scadenze-buf PIC  X(50).
       77 lab-scaduto-al-buf           PIC  X(50).
       77 lab-perce-buf    PIC  zz9,99.
       77 status-pas       PIC  X(2).
           88 Valid-status-pas VALUE IS "00" THRU "09". 
       77 status-pat       PIC  X(2).
           88 Valid-status-pat VALUE IS "00" THRU "09". 
       77 lab-attuale-buf  PIC  ---.---.--9,99.
       77 v-attuale        PIC  9
                  VALUE IS 1.
       77 lab-num-buf      PIC  ---.---.--9,99.
       77 lab-den-buf      PIC  ---.---.--9,99.
       77 lab-perce-max-buf            PIC  x(50).
       77 colore-perce     PIC  9(6)
                  VALUE IS 5.
       77 lab-scad-tot-buf PIC  ---.---.--9,99.
       77 STATUS-sitfin    PIC  X(2).
           88 Valid-STATUS-sitfin VALUE IS "00" THRU "09". 
       77 STATUS-tgrupgdo  PIC  X(2).
           88 Valid-STATUS-tgrupgdo VALUE IS "00" THRU "09". 
       77 lab-piva-buf     PIC  x(11)
                  VALUE IS "Label".
       77 lab-scheda-buf   PIC  ---.---.--9,99.
       77 lab-scaduti-buf  PIC  ---.---.--9,99.
       77 lab-scadenza-buf PIC  ---.---.--9,99.
       77 lab-fido-extra-buf           PIC  ---.---.--9,99.
       77 lab-dif-den-fido-extra-buf   PIC  ---.---.--9,99.
       77 como-dif-den-fido-extra      PIC  s9(9)v99.

      ***********************************************************
      *   Code Gen's Buffer                                     *
      ***********************************************************
       77 STATUS-Screen1-FLAG-REFRESH PIC  9.
          88 Screen1-FLAG-REFRESH  VALUE 1 FALSE 0. 
       77 TMP-DataSet1-tgrupgdo-BUF     PIC X(1206).
       77 TMP-DataSet1-clienti-BUF     PIC X(1910).
       77 TMP-DataSet1-sitfin-BUF     PIC X(888).
       77 TMP-DataSet1-tparamge-BUF     PIC X(815).
      * VARIABLES FOR RECORD LENGTH.
       77  TotemFdSlRecordClearOffset   PIC 9(5) COMP-4.
       77  TotemFdSlRecordLength        PIC 9(5) COMP-4.
      * FILE'S LOCK MODE FLAG
       77 DataSet1-tgrupgdo-LOCK-FLAG   PIC X VALUE SPACE.
           88 DataSet1-tgrupgdo-LOCK  VALUE "Y".
       77 DataSet1-tgrupgdo-KEY-ORDER  PIC X VALUE "A".
          88 DataSet1-tgrupgdo-KEY-Asc  VALUE "A".
          88 DataSet1-tgrupgdo-KEY-Desc VALUE "D".
       77 DataSet1-clienti-LOCK-FLAG   PIC X VALUE SPACE.
           88 DataSet1-clienti-LOCK  VALUE "Y".
       77 DataSet1-KEYIS   PIC 9(3) VALUE 1.
       77 DataSet1-clienti-KEY1-ORDER  PIC X VALUE "A".
          88 DataSet1-clienti-KEY1-Asc  VALUE "A".
          88 DataSet1-clienti-KEY1-Desc VALUE "D".
       77 DataSet1-sitfin-LOCK-FLAG   PIC X VALUE SPACE.
           88 DataSet1-sitfin-LOCK  VALUE "Y".
       77 DataSet1-sitfin-KEY-ORDER  PIC X VALUE "A".
          88 DataSet1-sitfin-KEY-Asc  VALUE "A".
          88 DataSet1-sitfin-KEY-Desc VALUE "D".
       77 DataSet1-tparamge-LOCK-FLAG   PIC X VALUE SPACE.
           88 DataSet1-tparamge-LOCK  VALUE "Y".
       77 DataSet1-tparamge-KEY-ORDER  PIC X VALUE "A".
          88 DataSet1-tparamge-KEY-Asc  VALUE "A".
          88 DataSet1-tparamge-KEY-Desc VALUE "D".

       77 clienti-cli-K1-SPLITBUF  PIC X(47).
       77 clienti-cli-K3-SPLITBUF  PIC X(12).
       77 clienti-cli-K4-SPLITBUF  PIC X(8).

           copy "link-sitfin-p.def".
       77  num-bmp-1   pic 9.
       77  num-bmp-2   pic 9.
       77  num-bmp-3   pic 9.
      *{TOTEM}END

      *{TOTEM}ID-LOGICI
      ***** Elenco ID Logici *****
      ***** Fine ID Logici *****
      *{TOTEM}END

       LINKAGE          SECTION.
      *{TOTEM}LINKAGE
           COPY  "LINK-SITFIN.DEF".
      *{TOTEM}END

       SCREEN           SECTION.
      *{TOTEM}COPY-SCREEN
      * FORM
       01 
           Screen1, 
           .

      * FRAME
       05
           Screen1-Fr-1, 
           Frame, 
           COL 2,10, 
           LINE 1,88,
           LINES 4,83 ,
           SIZE 56,00 ,
           COLOR IS 5,
           ID IS 1,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TITLE "Ragione Sociale / Gruppo GDO",
           TITLE-POSITION 2,
           .

      * LABEL
       05
           lab-cliente, 
           Label, 
           COL 3,60, 
           LINE 3,38,
           LINES 1,44 ,
           SIZE 53,00 ,
           COLOR IS 2,
           FONT IS Verdana12B-Occidentale,
           ID IS 2,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           CENTER,
           TRANSPARENT,
           TITLE lab-cliente-buf,
           .

      * LABEL
       05
           lab-piva, 
           Label, 
           COL 3,60, 
           LINE 4,82,
           LINES 1,44 ,
           SIZE 53,00 ,
           COLOR IS 2,
           FONT IS Verdana12B-Occidentale,
           ID IS 3,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           CENTER,
           TRANSPARENT,
           TITLE lab-piva-buf,
           .

      * PUSH BUTTON
       05
           pb-fatto, 
           Push-Button, 
           COL 26,00, 
           LINE 18,67,
           LINES 30,00 ,
           SIZE 73,00 ,
           BITMAP-HANDLE FATTO-BMP,
           BITMAP-NUMBER 2,
           UNFRAMED,
           SQUARE,
           EXCEPTION-VALUE 27,
           FLAT,
           FONT IS Small-Font,
           ID IS 4,
           ESCAPE-BUTTON,
           .

      * BITMAP
       05
           bmp-1, 
           Bitmap, 
           COL 2,00, 
           LINE 7,94,
           LINES 2,22 ,
           SIZE 3,40 ,
           TRANSPARENT-COLOR TR-COLOR,
           BITMAP-HANDLE STATI-BMP,
           BITMAP-NUMBER 2,
           ID IS 5,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           bitmap-number num-bmp-1
           .

      * LABEL
       05
           Screen1-La-1, 
           Label, 
           COL 7,00, 
           LINE 8,11,
           LINES 1,17 ,
           SIZE 4,00 ,
           ID IS 6,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "Fido:",
           .

      * LABEL
       05
           lab-scadenze, 
           Label, 
           COL 7,20, 
           LINE 13,56,
           LINES 1,17 ,
           SIZE 30,00 ,
           ID IS 7,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE lab-scadenze-buf,
           .

      * BITMAP
       05
           bmp-2, 
           Bitmap, 
           COL 2,00, 
           LINE 12,11,
           LINES 2,22 ,
           SIZE 3,40 ,
           TRANSPARENT-COLOR TR-COLOR,
           BITMAP-HANDLE STATI-BMP,
           BITMAP-NUMBER 2,
           ID IS 8,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           bitmap-number num-bmp-2
           .

      * LABEL
       05
           lab-lince, 
           Label, 
           COL 13,00, 
           LINE 8,11,
           LINES 1,17 ,
           SIZE 14,00 ,
           COLOR IS 2,
           FONT IS Verdana12B-Occidentale,
           ID IS 11,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           RIGHT,
           TRANSPARENT,
           TITLE lab-lince-buf,
           .

      * LABEL
       05
           Screen1-La-2, 
           Label, 
           COL 30,50, 
           LINE 8,11,
           LINES 1,17 ,
           SIZE 10,30 ,
           ID IS 12,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "Esposizione:",
           .

      * LABEL
       05
           lab-scaduto, 
           Label, 
           COL 41,00, 
           LINE 8,11,
           LINES 1,17 ,
           SIZE 14,50 ,
           COLOR IS 2,
           FONT IS Verdana12B-Occidentale,
           ID IS 13,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           RIGHT,
           TRANSPARENT,
           TITLE lab-scad-tot-buf,
           .

      * BAR
       05
           Screen1-Br-1a, 
           Bar,
           COL 2,10, 
           LINE 18,17,
           SIZE 56,00 ,
           ID IS 27,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           COLORS (5),
           WIDTH 1,
           .

      * BAR
       05
           Screen1-Br-1b, 
           Bar,
           COL 2,10, 
           LINE 10,56,
           SIZE 56,00 ,
           ID IS 34,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           COLORS (5),
           WIDTH 1,
           .

      * LABEL
       05
           lab-scaduto-al, 
           Label, 
           COL 7,20, 
           LINE 11,89,
           LINES 1,17 ,
           SIZE 25,00 ,
           ID IS 36,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE lab-scaduto-al-buf,
           .

      * LABEL
       05
           lab-perce-max, 
           Label, 
           COL 31,50, 
           LINE 15,44,
           LINES 1,17 ,
           SIZE 13,00 ,
           FONT IS Verdana10-Occidentale,
           ID IS 37,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           RIGHT,
           TRANSPARENT,
           TITLE lab-perce-max-buf,
           .

      * LABEL
       05
           lab-num, 
           Label, 
           COL 41,00, 
           LINE 11,89,
           LINES 1,17 ,
           SIZE 14,50 ,
           COLOR IS 2,
           FONT IS Verdana12B-Occidentale,
           ID IS 38,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           RIGHT,
           TRANSPARENT,
           TITLE lab-num-buf,
           .

      * LABEL
       05
           lab-den, 
           Label, 
           COL 41,00, 
           LINE 13,56,
           LINES 1,17 ,
           SIZE 14,50 ,
           COLOR IS 2,
           FONT IS Verdana12B-Occidentale,
           ID IS 39,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           RIGHT,
           TRANSPARENT,
           TITLE lab-den-buf,
           .

      * LABEL
       05
           lab-perce, 
           Label, 
           COL 47,50, 
           LINE 15,44,
           LINES 1,17 ,
           SIZE 8,00 ,
           COLOR IS colore-perce,
           FONT IS Verdana12B-Occidentale,
           ID IS 42,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           RIGHT,
           TRANSPARENT,
           TITLE lab-perce-buf,
           .

      * LABEL
       05
           lab-percea, 
           Label, 
           COL 55,80, 
           LINE 15,44,
           LINES 1,17 ,
           SIZE 2,10 ,
           COLOR IS colore-perce,
           FONT IS Verdana12B-Occidentale,
           ID IS 43,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           RIGHT,
           TRANSPARENT,
           TITLE "%",
           .

      *{TOTEM}END

      *{TOTEM}LINKPARA
       PROCEDURE  DIVISION USING sitfin-linkage, calfido-linkage.
      *{TOTEM}END

      *{TOTEM}DECLARATIVE
       DECLARATIVES.
      * <TOTEM:EPT. INIT:sitfin, INIT:sitfin, BeforeDeclarative>
      ***---
       SITFIN-ERR SECTION.
           use after error procedure on SITFIN.
           evaluate status-SITFIN
           when "35" continue
           when "39"
                display message "File [SITFIN] Mismatch size!"
                           title titolo
                            icon 3
                
           when "98"
                display message "[SITFIN] Indexed file corrupt!"
                           title titolo
                            icon 3
                
           end-evaluate.

      * <TOTEM:END>
       INPUT-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON INPUT.
       0100-DECL.
           EXIT.
       I-O-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON I-O.
       0200-DECL.
           EXIT.
       OUTPUT-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON OUTPUT.
       0300-DECL.
           EXIT.
       TRANSACTION-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON TRANSACTION.
       0400-DECL.
           EXIT.
       END DECLARATIVES.
      *{TOTEM}END

       MAIN-LOGIC.
      *{TOTEM}ENTRY-BEFPRG
      *    Before-Program
           PERFORM sitfin-Ev-Before-Program
      *{TOTEM}END
           PERFORM INITIALIZE-ROUTINE.
      * run main screen
      *{TOTEM}RUN-MAINSCR
           PERFORM Screen1-OPEN-ROUTINE.
      *{TOTEM}END

      *{TOTEM}COPY-PROCEDURE
       EXIT-STOP-ROUTINE.
           PERFORM CLOSE-FILE-RTN
      * <TOTEM:EPT. INIT:sitfin, INIT:sitfin, BeforeDestroyResource>
      * <TOTEM:END>
           DESTROY Verdana12B-Occidentale
           DESTROY Verdana10-Occidentale
           DESTROY Verdana12-Occidentale
           CALL "w$bitmap" USING WBITMAP-DESTROY, FATTO-BMP
           CALL "w$bitmap" USING WBITMAP-DESTROY, STATI-BMP
      *    After-Program
           PERFORM sitfin-Ev-After-Program
           EXIT PROGRAM TOTEM-PgmStatus
           STOP RUN.

       INITIALIZE-ROUTINE.
      *    Before Init
      * initialize program status variable
           Initialize TOTEM-PgmStatus.
      * get system information
           ACCEPT SYSTEM-INFORMATION FROM SYSTEM-INFO.
      * get terminal information
           ACCEPT TERMINAL-ABILITIES FROM TERMINAL-INFO.
      * set font
           PERFORM INIT-FONT.
      * load bitmap
           PERFORM INIT-BMP.
      * load resource
           PERFORM INIT-RES.
      * create pop-up menu
           PERFORM INIT-POPUP.
      * open files
           PERFORM OPEN-FILE-RTN.
      *    After Init
           .
    
       INIT-FONT.
      * Verdana12B-Occidentale
           INITIALIZE WFONT-DATA Verdana12B-Occidentale
           MOVE 12 TO WFONT-SIZE
           MOVE "Verdana" TO WFONT-NAME
           SET WFCHARSET-DONT-CARE TO TRUE
           SET WFONT-BOLD TO TRUE
           SET WFONT-ITALIC TO FALSE
           SET WFONT-UNDERLINE TO FALSE
           SET WFONT-STRIKEOUT TO FALSE
           SET WFONT-FIXED-PITCH TO FALSE
           MOVE 0 TO WFONT-CHAR-SET
           CALL "W$FONT" USING WFONT-GET-FONT, 
                     Verdana12B-Occidentale, WFONT-DATA
      * Verdana10-Occidentale
           INITIALIZE WFONT-DATA Verdana10-Occidentale
           MOVE 10 TO WFONT-SIZE
           MOVE "Verdana" TO WFONT-NAME
           SET WFCHARSET-DONT-CARE TO TRUE
           SET WFONT-BOLD TO FALSE
           SET WFONT-ITALIC TO FALSE
           SET WFONT-UNDERLINE TO FALSE
           SET WFONT-STRIKEOUT TO FALSE
           SET WFONT-FIXED-PITCH TO FALSE
           MOVE 0 TO WFONT-CHAR-SET
           CALL "W$FONT" USING WFONT-GET-FONT, 
                     Verdana10-Occidentale, WFONT-DATA
      * Verdana12-Occidentale
           INITIALIZE WFONT-DATA Verdana12-Occidentale
           MOVE 12 TO WFONT-SIZE
           MOVE "Verdana" TO WFONT-NAME
           SET WFCHARSET-DONT-CARE TO TRUE
           SET WFONT-BOLD TO FALSE
           SET WFONT-ITALIC TO FALSE
           SET WFONT-UNDERLINE TO FALSE
           SET WFONT-STRIKEOUT TO FALSE
           SET WFONT-FIXED-PITCH TO FALSE
           MOVE 0 TO WFONT-CHAR-SET
           CALL "W$FONT" USING WFONT-GET-FONT, 
                     Verdana12-Occidentale, WFONT-DATA
           .

       INIT-BMP.
      * pb-fatto
           COPY RESOURCE "FATTO.BMP".
           CALL "w$bitmap" USING WBITMAP-LOAD "FATTO.BMP", 
                   GIVING FATTO-BMP.
      * bmp-1
           COPY RESOURCE "STATI.BMP".
           CALL "w$bitmap" USING WBITMAP-LOAD "STATI.BMP", 
                   GIVING STATI-BMP.
           .

       INIT-RES.
           .

       INIT-POPUP.
           .

       OPEN-FILE-RTN.
      *    Before Open
           PERFORM OPEN-tgrupgdo
           PERFORM OPEN-clienti
      *    sitfin OPEN MODE IS FALSE
      *    PERFORM OPEN-sitfin
           PERFORM OPEN-tparamge
      *    After Open
           .

       OPEN-tgrupgdo.
      * <TOTEM:EPT. INIT:sitfin, FD:tgrupgdo, BeforeOpen>
      * <TOTEM:END>
           OPEN  INPUT tgrupgdo
           IF NOT Valid-STATUS-tgrupgdo
              PERFORM  Screen1-EXTENDED-FILE-STATUS
              GO TO EXIT-STOP-ROUTINE
           END-IF
      * <TOTEM:EPT. INIT:sitfin, FD:tgrupgdo, AfterOpen>
      * <TOTEM:END>
           .

       OPEN-clienti.
      * <TOTEM:EPT. INIT:sitfin, FD:clienti, BeforeOpen>
      * <TOTEM:END>
           OPEN  INPUT clienti
           IF NOT Valid-STATUS-clienti
              PERFORM  Screen1-EXTENDED-FILE-STATUS
              GO TO EXIT-STOP-ROUTINE
           END-IF
      * <TOTEM:EPT. INIT:sitfin, FD:clienti, AfterOpen>
      * <TOTEM:END>
           .

       OPEN-sitfin.
      * <TOTEM:EPT. INIT:sitfin, FD:sitfin, BeforeOpen>
      * <TOTEM:END>
           OPEN  INPUT sitfin
           IF NOT Valid-STATUS-sitfin
              PERFORM  Screen1-EXTENDED-FILE-STATUS
              GO TO EXIT-STOP-ROUTINE
           END-IF
      * <TOTEM:EPT. INIT:sitfin, FD:sitfin, AfterOpen>
      * <TOTEM:END>
           .

       OPEN-tparamge.
      * <TOTEM:EPT. INIT:sitfin, FD:tparamge, BeforeOpen>
      * <TOTEM:END>
           OPEN  INPUT tparamge
           IF NOT Valid-STATUS-tparamge
              PERFORM  Screen1-EXTENDED-FILE-STATUS
              GO TO EXIT-STOP-ROUTINE
           END-IF
      * <TOTEM:EPT. INIT:sitfin, FD:tparamge, AfterOpen>
      * <TOTEM:END>
           .

       CLOSE-FILE-RTN.
      *    Before Close
           PERFORM CLOSE-tgrupgdo
           PERFORM CLOSE-clienti
      *    sitfin CLOSE MODE IS FALSE
      *    PERFORM CLOSE-sitfin
           PERFORM CLOSE-tparamge
      *    After Close
           .

       CLOSE-tgrupgdo.
      * <TOTEM:EPT. INIT:sitfin, FD:tgrupgdo, BeforeClose>
      * <TOTEM:END>
           CLOSE tgrupgdo
           .

       CLOSE-clienti.
      * <TOTEM:EPT. INIT:sitfin, FD:clienti, BeforeClose>
      * <TOTEM:END>
           CLOSE clienti
           .

       CLOSE-sitfin.
      * <TOTEM:EPT. INIT:sitfin, FD:sitfin, BeforeClose>
      * <TOTEM:END>
           .

       CLOSE-tparamge.
      * <TOTEM:EPT. INIT:sitfin, FD:tparamge, BeforeClose>
      * <TOTEM:END>
           CLOSE tparamge
           .

       DataSet1-tgrupgdo-INITSTART.
           IF DataSet1-tgrupgdo-KEY-Asc
              MOVE Low-Value TO gdo-chiave OF tgrupgdo
           ELSE
              MOVE High-Value TO gdo-chiave OF tgrupgdo
           END-IF
           .

       DataSet1-tgrupgdo-INITEND.
           IF DataSet1-tgrupgdo-KEY-Asc
              MOVE High-Value TO gdo-chiave OF tgrupgdo
           ELSE
              MOVE Low-Value TO gdo-chiave OF tgrupgdo
           END-IF
           .

      * tgrupgdo
       DataSet1-tgrupgdo-START.
           IF DataSet1-tgrupgdo-KEY-Asc
              START tgrupgdo KEY >= gdo-chiave OF tgrupgdo
           ELSE
              START tgrupgdo KEY <= gdo-chiave OF tgrupgdo
           END-IF
           .

       DataSet1-tgrupgdo-START-NOTGREATER.
           IF DataSet1-tgrupgdo-KEY-Asc
              START tgrupgdo KEY <= gdo-chiave OF tgrupgdo
           ELSE
              START tgrupgdo KEY >= gdo-chiave OF tgrupgdo
           END-IF
           .

       DataSet1-tgrupgdo-START-GREATER.
           IF DataSet1-tgrupgdo-KEY-Asc
              START tgrupgdo KEY > gdo-chiave OF tgrupgdo
           ELSE
              START tgrupgdo KEY < gdo-chiave OF tgrupgdo
           END-IF
           .

       DataSet1-tgrupgdo-START-LESS.
           IF DataSet1-tgrupgdo-KEY-Asc
              START tgrupgdo KEY < gdo-chiave OF tgrupgdo
           ELSE
              START tgrupgdo KEY > gdo-chiave OF tgrupgdo
           END-IF
           .

       DataSet1-tgrupgdo-Read.
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, BeforeReadRecord>
      * <TOTEM:END>
           IF DataSet1-tgrupgdo-LOCK
              READ tgrupgdo WITH LOCK 
              KEY gdo-chiave OF tgrupgdo
           ELSE
              READ tgrupgdo WITH NO LOCK 
              KEY gdo-chiave OF tgrupgdo
           END-IF
           MOVE STATUS-tgrupgdo TO TOTEM-ERR-STAT 
           MOVE "tgrupgdo" TO TOTEM-ERR-FILE
           MOVE "READ" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, AfterReadRecord>
      * <TOTEM:END>
           .

       DataSet1-tgrupgdo-Read-Next.
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, BeforeReadNext>
      * <TOTEM:END>
           IF DataSet1-tgrupgdo-KEY-Asc
              IF DataSet1-tgrupgdo-LOCK
                 READ tgrupgdo NEXT WITH LOCK
              ELSE
                 READ tgrupgdo NEXT WITH NO LOCK
              END-IF
           ELSE
              IF DataSet1-tgrupgdo-LOCK
                 READ tgrupgdo PREVIOUS WITH LOCK
              ELSE
                 READ tgrupgdo PREVIOUS WITH NO LOCK
              END-IF
           END-IF
           MOVE STATUS-tgrupgdo TO TOTEM-ERR-STAT
           MOVE "tgrupgdo" TO TOTEM-ERR-FILE
           MOVE "READ NEXT" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, AfterReadNext>
      * <TOTEM:END>
           .

       DataSet1-tgrupgdo-Read-Prev.
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, BeforeReadPrev>
      * <TOTEM:END>
           IF DataSet1-tgrupgdo-KEY-Asc
              IF DataSet1-tgrupgdo-LOCK
                 READ tgrupgdo PREVIOUS WITH LOCK
              ELSE
                 READ tgrupgdo PREVIOUS WITH NO LOCK
              END-IF
           ELSE
              IF DataSet1-tgrupgdo-LOCK
                 READ tgrupgdo NEXT WITH LOCK
              ELSE
                 READ tgrupgdo NEXT WITH NO LOCK
              END-IF
           END-IF
           MOVE STATUS-tgrupgdo TO TOTEM-ERR-STAT
           MOVE "tgrupgdo" TO TOTEM-ERR-FILE
           MOVE "READ PREVIOUS" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, AfterReadPrev>
      * <TOTEM:END>
           .

       DataSet1-tgrupgdo-Rec-Write.
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, BeforeWrite>
      * <TOTEM:END>
           MOVE STATUS-tgrupgdo TO TOTEM-ERR-STAT
           MOVE "tgrupgdo" TO TOTEM-ERR-FILE
           MOVE "WRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, AfterWrite>
      * <TOTEM:END>
           .

       DataSet1-tgrupgdo-Rec-Rewrite.
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, BeforeRewrite>
      * <TOTEM:END>
           MOVE STATUS-tgrupgdo TO TOTEM-ERR-STAT
           MOVE "tgrupgdo" TO TOTEM-ERR-FILE
           MOVE "REWRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, AfterRewrite>
      * <TOTEM:END>
           .

       DataSet1-tgrupgdo-Rec-Delete.
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, BeforeDelete>
      * <TOTEM:END>
           MOVE STATUS-tgrupgdo TO TOTEM-ERR-STAT
           MOVE "tgrupgdo" TO TOTEM-ERR-FILE
           MOVE "DELETE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tgrupgdo, AfterDelete>
      * <TOTEM:END>
           .

       clienti-cli-K1-MERGE-SPLITBUF.
           INITIALIZE clienti-cli-K1-SPLITBUF
           MOVE cli-tipo-CF OF clienti(1:1) TO 
           clienti-cli-K1-SPLITBUF(1:1)
           MOVE cli-ragsoc-1 OF clienti(1:40) TO 
           clienti-cli-K1-SPLITBUF(2:40)
           MOVE cli-codice OF clienti(1:5) TO 
           clienti-cli-K1-SPLITBUF(42:5)
           .

       clienti-cli-K3-MERGE-SPLITBUF.
           INITIALIZE clienti-cli-K3-SPLITBUF
           MOVE cli-gdo OF clienti(1:5) TO clienti-cli-K3-SPLITBUF(1:5)
           MOVE cli-chiave OF clienti(1:6) TO 
           clienti-cli-K3-SPLITBUF(6:6)
           .

       clienti-cli-K4-MERGE-SPLITBUF.
           INITIALIZE clienti-cli-K4-SPLITBUF
           MOVE cli-utf OF clienti(1:1) TO clienti-cli-K4-SPLITBUF(1:1)
           MOVE cli-chiave OF clienti(1:6) TO 
           clienti-cli-K4-SPLITBUF(2:6)
           .

       DataSet1-clienti-INITSTART.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-clienti-KEY1-Asc
                 MOVE Low-Value TO cli-chiave OF clienti
              ELSE
                 MOVE High-Value TO cli-chiave OF clienti
              END-IF
           END-EVALUATE
           .

       DataSet1-clienti-INITEND.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-clienti-KEY1-Asc
                 MOVE High-Value TO cli-chiave OF clienti
              ELSE
                 MOVE Low-Value TO cli-chiave OF clienti
              END-IF
           END-EVALUATE
           .

       DataSet1-CHANGETO-KEY1.
           MOVE 1 TO DataSet1-KEYIS
           .   

       DataSet1-Change-CurrentKey-Asc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "A" TO DataSet1-clienti-KEY1-ORDER
           END-EVALUATE
           .

       DataSet1-Change-CurrentKey-Desc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "D" TO DataSet1-clienti-KEY1-ORDER
           END-EVALUATE
           .

      * clienti
       DataSet1-clienti-START.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-clienti-KEY1-Asc
                 START clienti KEY >= cli-chiave OF clienti
              ELSE
                 START clienti KEY <= cli-chiave OF clienti
              END-IF
           END-EVALUATE
           .

       DataSet1-clienti-START-NOTGREATER.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-clienti-KEY1-Asc
                 START clienti KEY <= cli-chiave OF clienti
              ELSE
                 START clienti KEY >= cli-chiave OF clienti
              END-IF
           END-EVALUATE
           .

       DataSet1-clienti-START-GREATER.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-clienti-KEY1-Asc
                 START clienti KEY > cli-chiave OF clienti
              ELSE
                 START clienti KEY < cli-chiave OF clienti
              END-IF
           END-EVALUATE
           .

       DataSet1-clienti-START-LESS.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-clienti-KEY1-Asc
                 START clienti KEY < cli-chiave OF clienti
              ELSE
                 START clienti KEY > cli-chiave OF clienti
              END-IF
           END-EVALUATE
           .

       DataSet1-clienti-Read.
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, BeforeReadRecord>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-clienti-LOCK
                 READ clienti WITH LOCK 
                 KEY cli-chiave OF clienti
              ELSE
                 READ clienti WITH NO LOCK 
                 KEY cli-chiave OF clienti
              END-IF
           END-EVALUATE
           PERFORM clienti-cli-K1-MERGE-SPLITBUF
           PERFORM clienti-cli-K3-MERGE-SPLITBUF
           PERFORM clienti-cli-K4-MERGE-SPLITBUF
           MOVE STATUS-clienti TO TOTEM-ERR-STAT 
           MOVE "clienti" TO TOTEM-ERR-FILE
           MOVE "READ" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, AfterReadRecord>
      * <TOTEM:END>
           .

       DataSet1-clienti-Read-Next.
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, BeforeReadNext>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-clienti-KEY1-Asc
                 IF DataSet1-clienti-LOCK
                    READ clienti NEXT WITH LOCK
                 ELSE
                    READ clienti NEXT WITH NO LOCK
                 END-IF
              ELSE
                 IF DataSet1-clienti-LOCK
                    READ clienti PREVIOUS WITH LOCK
                 ELSE
                    READ clienti PREVIOUS WITH NO LOCK
                 END-IF
              END-IF
           END-EVALUATE
           PERFORM clienti-cli-K1-MERGE-SPLITBUF
           PERFORM clienti-cli-K3-MERGE-SPLITBUF
           PERFORM clienti-cli-K4-MERGE-SPLITBUF
           MOVE STATUS-clienti TO TOTEM-ERR-STAT
           MOVE "clienti" TO TOTEM-ERR-FILE
           MOVE "READ NEXT" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, AfterReadNext>
      * <TOTEM:END>
           .

       DataSet1-clienti-Read-Prev.
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, BeforeReadPrev>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-clienti-KEY1-Asc
                 IF DataSet1-clienti-LOCK
                    READ clienti PREVIOUS WITH LOCK
                 ELSE
                    READ clienti PREVIOUS WITH NO LOCK
                 END-IF
              ELSE
                 IF DataSet1-clienti-LOCK
                    READ clienti NEXT WITH LOCK
                 ELSE
                    READ clienti NEXT WITH NO LOCK
                 END-IF
              END-IF
           END-EVALUATE
           PERFORM clienti-cli-K1-MERGE-SPLITBUF
           PERFORM clienti-cli-K3-MERGE-SPLITBUF
           PERFORM clienti-cli-K4-MERGE-SPLITBUF
           MOVE STATUS-clienti TO TOTEM-ERR-STAT
           MOVE "clienti" TO TOTEM-ERR-FILE
           MOVE "READ PREVIOUS" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, AfterReadPrev>
      * <TOTEM:END>
           .

       DataSet1-clienti-Rec-Write.
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, BeforeWrite>
      * <TOTEM:END>
           MOVE STATUS-clienti TO TOTEM-ERR-STAT
           MOVE "clienti" TO TOTEM-ERR-FILE
           MOVE "WRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, AfterWrite>
      * <TOTEM:END>
           .

       DataSet1-clienti-Rec-Rewrite.
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, BeforeRewrite>
      * <TOTEM:END>
           MOVE STATUS-clienti TO TOTEM-ERR-STAT
           MOVE "clienti" TO TOTEM-ERR-FILE
           MOVE "REWRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, AfterRewrite>
      * <TOTEM:END>
           .

       DataSet1-clienti-Rec-Delete.
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, BeforeDelete>
      * <TOTEM:END>
           MOVE STATUS-clienti TO TOTEM-ERR-STAT
           MOVE "clienti" TO TOTEM-ERR-FILE
           MOVE "DELETE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:clienti, AfterDelete>
      * <TOTEM:END>
           .

       DataSet1-sitfin-INITSTART.
           IF DataSet1-sitfin-KEY-Asc
              MOVE Low-Value TO sf-chiave
           ELSE
              MOVE High-Value TO sf-chiave
           END-IF
           .

       DataSet1-sitfin-INITEND.
           IF DataSet1-sitfin-KEY-Asc
              MOVE High-Value TO sf-chiave
           ELSE
              MOVE Low-Value TO sf-chiave
           END-IF
           .

      * sitfin
       DataSet1-sitfin-START.
           IF DataSet1-sitfin-KEY-Asc
              START sitfin KEY >= sf-chiave
           ELSE
              START sitfin KEY <= sf-chiave
           END-IF
           .

       DataSet1-sitfin-START-NOTGREATER.
           IF DataSet1-sitfin-KEY-Asc
              START sitfin KEY <= sf-chiave
           ELSE
              START sitfin KEY >= sf-chiave
           END-IF
           .

       DataSet1-sitfin-START-GREATER.
           IF DataSet1-sitfin-KEY-Asc
              START sitfin KEY > sf-chiave
           ELSE
              START sitfin KEY < sf-chiave
           END-IF
           .

       DataSet1-sitfin-START-LESS.
           IF DataSet1-sitfin-KEY-Asc
              START sitfin KEY < sf-chiave
           ELSE
              START sitfin KEY > sf-chiave
           END-IF
           .

       DataSet1-sitfin-Read.
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, BeforeReadRecord>
      * <TOTEM:END>
           IF DataSet1-sitfin-LOCK
              READ sitfin WITH LOCK 
              KEY sf-chiave
           ELSE
              READ sitfin WITH NO LOCK 
              KEY sf-chiave
           END-IF
           MOVE STATUS-sitfin TO TOTEM-ERR-STAT 
           MOVE "sitfin" TO TOTEM-ERR-FILE
           MOVE "READ" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, AfterReadRecord>
      * <TOTEM:END>
           .

       DataSet1-sitfin-Read-Next.
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, BeforeReadNext>
      * <TOTEM:END>
           IF DataSet1-sitfin-KEY-Asc
              IF DataSet1-sitfin-LOCK
                 READ sitfin NEXT WITH LOCK
              ELSE
                 READ sitfin NEXT WITH NO LOCK
              END-IF
           ELSE
              IF DataSet1-sitfin-LOCK
                 READ sitfin PREVIOUS WITH LOCK
              ELSE
                 READ sitfin PREVIOUS WITH NO LOCK
              END-IF
           END-IF
           MOVE STATUS-sitfin TO TOTEM-ERR-STAT
           MOVE "sitfin" TO TOTEM-ERR-FILE
           MOVE "READ NEXT" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, AfterReadNext>
      * <TOTEM:END>
           .

       DataSet1-sitfin-Read-Prev.
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, BeforeReadPrev>
      * <TOTEM:END>
           IF DataSet1-sitfin-KEY-Asc
              IF DataSet1-sitfin-LOCK
                 READ sitfin PREVIOUS WITH LOCK
              ELSE
                 READ sitfin PREVIOUS WITH NO LOCK
              END-IF
           ELSE
              IF DataSet1-sitfin-LOCK
                 READ sitfin NEXT WITH LOCK
              ELSE
                 READ sitfin NEXT WITH NO LOCK
              END-IF
           END-IF
           MOVE STATUS-sitfin TO TOTEM-ERR-STAT
           MOVE "sitfin" TO TOTEM-ERR-FILE
           MOVE "READ PREVIOUS" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, AfterReadPrev>
      * <TOTEM:END>
           .

       DataSet1-sitfin-Rec-Write.
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, BeforeWrite>
      * <TOTEM:END>
           MOVE STATUS-sitfin TO TOTEM-ERR-STAT
           MOVE "sitfin" TO TOTEM-ERR-FILE
           MOVE "WRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, AfterWrite>
      * <TOTEM:END>
           .

       DataSet1-sitfin-Rec-Rewrite.
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, BeforeRewrite>
      * <TOTEM:END>
           MOVE STATUS-sitfin TO TOTEM-ERR-STAT
           MOVE "sitfin" TO TOTEM-ERR-FILE
           MOVE "REWRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, AfterRewrite>
      * <TOTEM:END>
           .

       DataSet1-sitfin-Rec-Delete.
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, BeforeDelete>
      * <TOTEM:END>
           MOVE STATUS-sitfin TO TOTEM-ERR-STAT
           MOVE "sitfin" TO TOTEM-ERR-FILE
           MOVE "DELETE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:sitfin, AfterDelete>
      * <TOTEM:END>
           .

       DataSet1-tparamge-INITSTART.
           IF DataSet1-tparamge-KEY-Asc
              MOVE Low-Value TO tge-chiave
           ELSE
              MOVE High-Value TO tge-chiave
           END-IF
           .

       DataSet1-tparamge-INITEND.
           IF DataSet1-tparamge-KEY-Asc
              MOVE High-Value TO tge-chiave
           ELSE
              MOVE Low-Value TO tge-chiave
           END-IF
           .

      * tparamge
       DataSet1-tparamge-START.
           IF DataSet1-tparamge-KEY-Asc
              START tparamge KEY >= tge-chiave
           ELSE
              START tparamge KEY <= tge-chiave
           END-IF
           .

       DataSet1-tparamge-START-NOTGREATER.
           IF DataSet1-tparamge-KEY-Asc
              START tparamge KEY <= tge-chiave
           ELSE
              START tparamge KEY >= tge-chiave
           END-IF
           .

       DataSet1-tparamge-START-GREATER.
           IF DataSet1-tparamge-KEY-Asc
              START tparamge KEY > tge-chiave
           ELSE
              START tparamge KEY < tge-chiave
           END-IF
           .

       DataSet1-tparamge-START-LESS.
           IF DataSet1-tparamge-KEY-Asc
              START tparamge KEY < tge-chiave
           ELSE
              START tparamge KEY > tge-chiave
           END-IF
           .

       DataSet1-tparamge-Read.
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, BeforeReadRecord>
      * <TOTEM:END>
           IF DataSet1-tparamge-LOCK
              READ tparamge WITH LOCK 
              KEY tge-chiave
           ELSE
              READ tparamge WITH NO LOCK 
              KEY tge-chiave
           END-IF
           MOVE STATUS-tparamge TO TOTEM-ERR-STAT 
           MOVE "tparamge" TO TOTEM-ERR-FILE
           MOVE "READ" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, AfterReadRecord>
      * <TOTEM:END>
           .

       DataSet1-tparamge-Read-Next.
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, BeforeReadNext>
      * <TOTEM:END>
           IF DataSet1-tparamge-KEY-Asc
              IF DataSet1-tparamge-LOCK
                 READ tparamge NEXT WITH LOCK
              ELSE
                 READ tparamge NEXT WITH NO LOCK
              END-IF
           ELSE
              IF DataSet1-tparamge-LOCK
                 READ tparamge PREVIOUS WITH LOCK
              ELSE
                 READ tparamge PREVIOUS WITH NO LOCK
              END-IF
           END-IF
           MOVE STATUS-tparamge TO TOTEM-ERR-STAT
           MOVE "tparamge" TO TOTEM-ERR-FILE
           MOVE "READ NEXT" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, AfterReadNext>
      * <TOTEM:END>
           .

       DataSet1-tparamge-Read-Prev.
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, BeforeReadPrev>
      * <TOTEM:END>
           IF DataSet1-tparamge-KEY-Asc
              IF DataSet1-tparamge-LOCK
                 READ tparamge PREVIOUS WITH LOCK
              ELSE
                 READ tparamge PREVIOUS WITH NO LOCK
              END-IF
           ELSE
              IF DataSet1-tparamge-LOCK
                 READ tparamge NEXT WITH LOCK
              ELSE
                 READ tparamge NEXT WITH NO LOCK
              END-IF
           END-IF
           MOVE STATUS-tparamge TO TOTEM-ERR-STAT
           MOVE "tparamge" TO TOTEM-ERR-FILE
           MOVE "READ PREVIOUS" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, AfterReadPrev>
      * <TOTEM:END>
           .

       DataSet1-tparamge-Rec-Write.
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, BeforeWrite>
      * <TOTEM:END>
           MOVE STATUS-tparamge TO TOTEM-ERR-STAT
           MOVE "tparamge" TO TOTEM-ERR-FILE
           MOVE "WRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, AfterWrite>
      * <TOTEM:END>
           .

       DataSet1-tparamge-Rec-Rewrite.
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, BeforeRewrite>
      * <TOTEM:END>
           MOVE STATUS-tparamge TO TOTEM-ERR-STAT
           MOVE "tparamge" TO TOTEM-ERR-FILE
           MOVE "REWRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, AfterRewrite>
      * <TOTEM:END>
           .

       DataSet1-tparamge-Rec-Delete.
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, BeforeDelete>
      * <TOTEM:END>
           MOVE STATUS-tparamge TO TOTEM-ERR-STAT
           MOVE "tparamge" TO TOTEM-ERR-FILE
           MOVE "DELETE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tparamge, AfterDelete>
      * <TOTEM:END>
           .

       DataSet1-INIT-RECORD.
           INITIALIZE gdo-rec OF tgrupgdo
           INITIALIZE cli-rec OF clienti
           INITIALIZE sf-rec OF sitfin
           INITIALIZE tge-rec OF tparamge
           .


      * FD's Initialize Paragraph
       DataSet1-tgrupgdo-INITREC.
           INITIALIZE gdo-rec OF tgrupgdo
               REPLACING NUMERIC       DATA BY ZEROS
                         ALPHANUMERIC  DATA BY SPACES
                         ALPHABETIC    DATA BY SPACES
           .

      * FD's Initialize Paragraph
       DataSet1-clienti-INITREC.
           INITIALIZE cli-rec OF clienti
               REPLACING NUMERIC       DATA BY ZEROS
                         ALPHANUMERIC  DATA BY SPACES
                         ALPHABETIC    DATA BY SPACES
           .

      * FD's Initialize Paragraph
       DataSet1-sitfin-INITREC.
           INITIALIZE sf-rec OF sitfin
               REPLACING NUMERIC       DATA BY ZEROS
                         ALPHANUMERIC  DATA BY SPACES
                         ALPHABETIC    DATA BY SPACES
           .

      * FD's Initialize Paragraph
       DataSet1-tparamge-INITREC.
           INITIALIZE tge-rec OF tparamge
               REPLACING NUMERIC       DATA BY ZEROS
                         ALPHANUMERIC  DATA BY SPACES
                         ALPHABETIC    DATA BY SPACES
           .

      *
       DataSet1-DISPATCH-BUFTOFLD.
           .

       Screen1-Open-Routine.
           PERFORM Screen1-Scrn
           PERFORM Screen1-Proc
           .

       Screen1-Scrn.
           PERFORM Screen1-Create-Win
           PERFORM Screen1-Init-Value
           PERFORM Screen1-Init-Data
      * Tab keystrok settings
      * Tool Bar
           PERFORM Screen1-DISPLAY
           .

       Screen1-Create-Win.
           Display Floating GRAPHICAL WINDOW
              LINES 19,94,
              SIZE 58,20,
              HEIGHT-IN-CELLS,
              WIDTH-IN-CELLS,
              COLOR 65793,
              CONTROL FONT Verdana12-Occidentale,
              LINK TO THREAD,
              NO SCROLL,
              TITLE-BAR,
              TITLE titolo,
              WITH SYSTEM MENU,
              USER-GRAY,
           VISIBLE 0,
              USER-WHITE,
              No WRAP,
              EVENT PROCEDURE Screen1-Event-Proc,
              HANDLE IS Screen1-Handle,
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, AfterCreateWin>
      * <TOTEM:END>


      * Tool Bar    
      * Status-bar
           DISPLAY Screen1 UPON Screen1-Handle
      * DISPLAY-COLUMNS settings
           .

       Screen1-PROC.
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, BeforeAccept>
           move spaces to tge-chiave.
           read tparamge no lock invalid continue end-read.


           initialize lab-cliente-buf.
      *****     if link-cli-codice is numeric
              move link-cli-codice to cli-codice
              set cli-tipo-C to true
              read clienti no lock invalid continue end-read
              move cli-codice to lab-cliente-buf
      *****        if cli-gdo not = spaces
      *****           move cli-gdo to gdo-codice lab-cliente-buf
      *****           read tgrupgdo no lock
      *****           move gdo-intestazione to cli-ragsoc-1
      *****        end-if
      *****     else
      *****        move link-cli-codice to cli-gdo gdo-codice lab-cliente-buf
      *****        read tgrupgdo no lock
      *****        move gdo-intestazione to cli-ragsoc-1
      *****     end-if.

           move cli-piva to sf-piva.
           read sitfin no lock invalid continue end-read.
           call "C$CALLEDBY" using PgmChiamante.
           if PgmChiamante = "ordine"    or
                           = "ordinevar" or
                           = "gordc"     or
                           = "gordcvar"
      *****        if ( sf-verifica-1 + sf-verifica-2 + sf-verifica-3 ) <= 1
              if ( sf-verifica-1 + sf-verifica-2 ) <= 1
                 inspect lab-cliente-buf replacing leading x"30" by x"20
      -    ""
                 call "C$JUSTIFY" using lab-cliente-buf, "L"
                 inspect lab-cliente-buf replacing trailing spaces by 
           low-value
                 string  lab-cliente-buf delimited low-value
                         " - "           delimited size
                         cli-ragsoc-1    delimited size
                         into lab-cliente-buf
                 end-string
                 inspect lab-cliente-buf 
                         replacing trailing low-value by spaces
           
                 display lab-cliente

                 move 0 to v-attuale
                 if sitfin-importo not = 0
                    move 1 to v-attuale
                    move sitfin-importo to lab-attuale-buf
                 end-if
      *****           display lab-attuale fr-attuale

                 perform VAL-SCREEN
                 modify screen1-handle, visible true
              else
                 move 27 to key-status
              end-if
           else
              inspect lab-cliente-buf replacing leading x"30" by x"20"
              call "C$JUSTIFY" using lab-cliente-buf, "L"
              inspect lab-cliente-buf replacing trailing spaces by 
           low-value
              string  lab-cliente-buf delimited low-value
                      " - "           delimited size
                      cli-ragsoc-1    delimited size
                      into lab-cliente-buf
              end-string
              inspect lab-cliente-buf 
                      replacing trailing low-value by spaces
           
              display lab-cliente

              move 0 to v-attuale
              if sitfin-importo not = 0
                 move 1 to v-attuale
                 move sitfin-importo to lab-attuale-buf
              end-if
      *****        display lab-attuale fr-attuale

              perform VAL-SCREEN
              modify screen1-handle, visible true
           end-if.

           .
      * <TOTEM:END>
           PERFORM UNTIL Exit-Pushed
              ACCEPT Screen1
                 ON EXCEPTION
                    PERFORM Screen1-Evaluate-Func
                 MOVE 1 TO TOTEM-Form-Index
              END-ACCEPT
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, AfterEndAccept>
      * <TOTEM:END>
           END-PERFORM
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, BeforeDestroyWindow>
      * <TOTEM:END>
           DESTROY Screen1-Handle
           INITIALIZE Key-Status
           .

       Screen1-Evaluate-Func.
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, AfterAccept>
      * <TOTEM:END>
           EVALUATE TRUE
              WHEN Exit-Pushed
                 PERFORM Screen1-Exit
              WHEN Event-Occurred
                 IF Event-Type = Cmd-Close
                    PERFORM Screen1-Exit
                 END-IF
           END-EVALUATE
      * avoid changing focus
           MOVE 4 TO Accept-Control
           .

       Screen1-CLEAR.
           PERFORM Screen1-INIT-VALUE
           PERFORM Screen1-DISPLAY
           .

       Screen1-DISPLAY.
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, BeforeDisplay>
      * <TOTEM:END>
           DISPLAY Screen1 UPON Screen1-Handle
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, AfterDisplay>
      * <TOTEM:END>
           .

       Screen1-Exit.
      * for main screen
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, BeforeExit>
      * <TOTEM:END>
           MOVE 27 TO Key-Status
           .

       Screen1-Init-Data.
           MOVE 1 TO TOTEM-Form-Index
           MOVE 0 TO TOTEM-Frame-Index
           .

       Screen1-Init-Value.
           MOVE titolo TO TOTEM-MSG-TITLE
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, SetDefault>
      * <TOTEM:END>
           PERFORM Screen1-FLD-TO-BUF
           .


       Screen1-ALLGRID-RESET.
           .

      * for Form's Validation
       Screen1-VALIDATION-ROUTINE.
           SET TOTEM-CHECK-OK TO TRUE
           .


       Screen1-Buf-To-Fld.
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, BeforeBufToFld>
      * <TOTEM:END>
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, AfterBufToFld>
      * <TOTEM:END>
           .

       Screen1-Fld-To-Buf.
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, BeforeFldToBuf>
      * <TOTEM:END>
      * <TOTEM:EPT. FORM:Screen1, FORM:Screen1, AfterFldToBuf>
      * <TOTEM:END>
           .

       Screen1-CONTROLLO-OLD.
           set SiSalvato to true.
           if mod = 0 exit paragraph end-if.
           perform Screen1-BUF-TO-FLD.
           move 0 to scelta.
           .
       Screen1-EXTENDED-FILE-STATUS.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
           MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           PERFORM Screen1-SHOW-MSG-ROUTINE
           .

       Screen1-SHOW-MSG-ROUTINE.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM Screen1-DISPLAY-MESSAGE
           .

       Screen1-DISPLAY-MESSAGE.
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

       Screen1-Save-Status.
           .             

       Screen1-Restore-Status.
           .



       Screen1-Event-Proc.
           .

      * USER DEFINE PARAGRAPH
       PARAGRAFO-COPY.
      * <TOTEM:PARA. PARAGRAFO-COPY>
           copy "calcola-colore-trasparente.cpy" 
           .
      * <TOTEM:END>

       VAL-SCREEN.
      * <TOTEM:PARA. VAL-SCREEN>
      *    VERIFICA 1
           move sf-lince           to lab-lince-buf.
           move sf-scoperto-tot    to lab-scad-tot-buf.
           move sf-saldo-scheda    to lab-scaduto-buf.
           move sf-saldo-scaduto   to lab-scaduti-buf.
           move sf-saldo-scadenza  to lab-scadenza-buf.

           if sf-verifica-1-ok
              set verifica-1-ok to true
              move 2   to num-bmp-1
           else
              set verifica-1-ok to false
              move 3   to num-bmp-1
           end-if.

      *    VERIFICA 2
           move sf-scaduto-al   to lab-scaduto-al-buf
           move sf-scadenze     to lab-scadenze-buf
           move sf-perce-max    to lab-perce-max-buf
           move sf-num          to lab-num-buf
           move sf-den          to lab-den-buf
      *     move sf-perce        to lab-perce-buf

           move cli-fido-extra  to lab-fido-extra-buf
           compute como-dif-den-fido-extra = sf-den - cli-fido-extra
           if como-dif-den-fido-extra < 0
              move 0 to como-dif-den-fido-extra
           end-if.
           move como-dif-den-fido-extra  to lab-dif-den-fido-extra-buf

      *    ricalcolo la verifica in base al fido extra
           if sf-den = 0 or cli-fido-extra > sf-den
              move 0 to sf-perce
           else
              compute sf-perce = (sf-den - cli-fido-extra)
                                                        / sf-num * 100
           end-if
           move sf-perce        to lab-perce-buf.

           if sf-verifica-2-ok
              set verifica-2-ok to true
              move 2   to num-bmp-2
              move 3   to colore-perce
           else
              set verifica-2-ok to false
              move 3   to num-bmp-2
              move 5   to colore-perce
           end-if.

      *    VERIFICA 3
           move sf-fat-per          to lab-fatt-per-buf.
           move sf-fatturato        to lab-fatturato-buf.
           move sf-fido-max         to lab-fido-buf.
           move sf-effetti-rischio  to lab-rb-buf.
           move sf-ordini-in-essere to lab-ordini-buf.
           move sf-scoperto-tot     to lab-tot-scad-buf.
           move sf-gg-dilazione     to lab-gg-buf.

           if sf-verifica-3-ok
              set verifica-3-ok to true
              move 2   to num-bmp-3
      *****     else
      *****        set verifica-3-ok to false
      *****        modify bmp-3, bitmap-number = 3
      *****        move 3   to num-bmp-3
           end-if.

           move sf-piva to lab-piva-buf.

           display Screen1.

           rewrite sf-rec
              invalid 
                 continue
           end-rewrite 
           .
      * <TOTEM:END>

      * EVENT PARAGRAPH
       sitfin-Ev-Before-Program.
      * <TOTEM:PARA. sitfin-Ev-Before-Program>
      *     open input sitfin.
           open i-o sitfin.
           if status-sitfin not = "00"
              display message "Effettuare lancio notturno"
                        title tit-err
                         icon 2
              goback
           end-if.
           perform CALCOLA-COLORE-TRASPARENTE 
           .
      * <TOTEM:END>
       sitfin-Ev-After-Program.
      * <TOTEM:PARA. sitfin-Ev-After-Program>
           close sitfin 
           .
      * <TOTEM:END>

      *{TOTEM}END

      *{TOTEM}SHOW-MSG
       MESSAGE-FOR-FILEERROR.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
              MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           .

       SHOW-TRANSACTION-ROUTINE.
           IF TOTEM-TRANSACTION-FLAG = SPACES
              IF TRANSACTION-STATUS NOT = 0
                 STRING "TRANSACTION ERROR ", TRANSACTION-STATUS
                    DELIMITED BY SIZE INTO TOTEM-MSG-1
              END-IF
           ELSE
              PERFORM SHOW-MSG-ROUTINE
              IF TRANSACTION-STATUS = 0
                 MOVE "Transazione terminata con Rollback." TO 
           TOTEM-MSG-3
              ELSE
                 STRING "TRANSACTION ERROR ", TRANSACTION-STATUS
                    DELIMITED BY SIZE INTO TOTEM-MSG-3
              END-IF
           END-IF
           .

       SHOW-MSG-ROUTINE.
           MOVE SPACE TO TOTEM-MSG-1 TOTEM-MSG-2 TOTEM-MSG-3
           EVALUATE TOTEM-MSG-ID
               WHEN "10"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Nessun altro dato." TO TOTEM-MSG-2
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "22"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Chiave Duplicata." TO TOTEM-MSG-2
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "23"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Raggiunta fine file." TO TOTEM-MSG-2
                    MOVE MB-WARNING-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "101"
                    MOVE "Terminare l'applicazione?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "201"
                    MOVE "Aggiungere un nuovo record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "202"
                    MOVE "Aggiornare il Record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "203"
                    MOVE "Cancellare il Record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "204"
                    MOVE "Chiave duplicata." TO TOTEM-MSG-1
                    MOVE MB-WARNING-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "301"
                    MOVE "Inserimento avvenuto con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "302"
                    MOVE "Aggiornamento avvenuto con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "303"
                    MOVE "Cancellazione avvenuta con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "401"
                    MOVE "Shell non trovata." TO TOTEM-MSG-1
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN OTHER
                    MOVE TEXT-MESSAGE TO TOTEM-MSG-1
                    STRING "FILE:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-3
                    MOVE 0 TO TOTEM-IDX1
                    INSPECT TOTEM-MSG-3 TALLYING TOTEM-IDX1
                       FOR TRAILING SPACE
                    STRING TOTEM-MSG-3(1:TOTEM-MSG-LENGTH - 
           TOTEM-IDX1), 
                       ", FILE STATUS ", PRIMARY-ERROR "," 
                       SECONDARY-ERROR
                    DELIMITED BY SIZE INTO TOTEM-MSG-2
                    MOVE SPACES TO TOTEM-MSG-3
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
           END-EVALUATE
           PERFORM MESSAGE-BOX-ROUTINE
           .

       MESSAGE-BOX-ROUTINE.
           MOVE 1 TO TOTEM-MSG-TEXT-POINTER
           IF TOTEM-MSG-1 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-1 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              STRING TOTEM-MSG-1( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                 DELIMITED BY SIZE
                 INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-2 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-2 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              IF TOTEM-MSG-TEXT-POINTER > 1
                 STRING X"0A" DELIMITED BY SIZE
                     INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
              END-IF
              STRING TOTEM-MSG-2( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                  DELIMITED BY SIZE
                  INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-3 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-3 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              IF TOTEM-MSG-TEXT-POINTER > 1
                 STRING X"0A" DELIMITED BY SIZE
                     INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
              END-IF
              STRING TOTEM-MSG-3( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                  DELIMITED BY SIZE
                  INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-TEXT-POINTER = 1
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-TEXT TALLYING TOTEM-MSG-SIZE FOR 
           TRAILING SPACE
                  COMPUTE TOTEM-MSG-TEXT-POINTER = 
           TOTEM-MSG-FULL-LENGTH - TOTEM-MSG-SIZE + 1
           END-IF
           MOVE LOW-VALUES TO TOTEM-MSG-TEXT(TOTEM-MSG-TEXT-POINTER : 1 
           )
           .

       MESSAGE-BOX-DISPLAY.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

      *{TOTEM}END

