      *{TOTEM}PRG-COMMENT
      * stdoccsv.Cbl
      * stdoccsv.Cbl is generated by TOTEM
      * This is a generated file. DO NOT modify this file directly.
      *{TOTEM}END
       IDENTIFICATION       DIVISION.
      *{TOTEM}PRGID
       PROGRAM-ID.          stdoccsv.
       AUTHOR.              andre.
       DATE-WRITTEN.        mercoledì 21 ottobre 2020 01:13:51.
       REMARKS.
      *{TOTEM}END

       ENVIRONMENT          DIVISION.
       CONFIGURATION        SECTION.
       SPECIAL-NAMES.
      *{TOTEM}SPECIAL-NAME
      * <TOTEM:EPT. INIT:stdoccsv, INIT:stdoccsv, SpecialName>
      * <TOTEM:END>
      *{TOTEM}END
      *{TOTEM}ACTIVEX-DEF
      *{TOTEM}END
      *{TOTEM}DECIMAL-POINT
           DECIMAL-POINT IS COMMA.
      *{TOTEM}END

       INPUT-OUTPUT         SECTION.
       FILE-CONTROL.
      *{TOTEM}FILE-CONTROL
           COPY "lineseq.sl".
           COPY "tnotacr.sl".
           COPY "tordini.sl".
      *{TOTEM}END
       DATA                 DIVISION.
       FILE                 SECTION.
      *{TOTEM}FILE
           COPY "lineseq.fd".
           COPY "tnotacr.fd".
           COPY "tordini.fd".
      *{TOTEM}END

       WORKING-STORAGE      SECTION.
      *{TOTEM}ACU-DEF
               COPY "acugui.def".
               COPY "acucobol.def".
               COPY "fonts.def".
               COPY "crtvars.def".
               COPY "opensave.def".
               COPY "showmsg.def".
               COPY "totem.def".
               COPY "standard.def".
      *{TOTEM}END

      *{TOTEM}COPY-WORKING
      * Key Status
       77 Key-Status IS SPECIAL-NAMES CRT STATUS PIC 9(5) VALUE 0.
          88 Enter-Pushed VALUE 13.
          88 Exit-Pushed VALUE 27.
          88 Message-Received VALUE 95.
          88 Event-Occurred VALUE 96.
          88 Screen-No-Input-Field VALUE 97.
          88 Screen-Time-Out VALUE 99.
      * Properties & User defined Working Stoarge
       77 OK-73X21-BMP     PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
           COPY  "SPLCRT2GRAF.LKS".
           COPY  "LINK-STBOLLE.DEF".
           COPY  "LINK-STFATT.DEF".
       77 Screen1-Handle
                  USAGE IS HANDLE OF WINDOW.
       77 CANCEL-73X21-BMP PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 Default-Font
                  USAGE IS HANDLE OF FONT DEFAULT-FONT.
       77 Small-Font
                  USAGE IS HANDLE OF FONT SMALL-FONT.
       78 titolo VALUE IS "GESLUX - Stampa documenti da csv". 
       77 bottone-ok-bmp   PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 bottone-cancel-bmp           PIC  S9(9)
                  USAGE IS COMP-4
                  VALUE IS 0.
       77 Verdana12-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 form1-Handle
                  USAGE IS HANDLE OF WINDOW.
       01 file-info.
           05 file-size        PIC  X(8)
                      USAGE IS COMP-X.
           05 file-date        PIC  9(8)
                      USAGE IS COMP-X.
           05 file-time        PIC  9(8)
                      USAGE IS COMP-X.
       77 AUTO-ID          PIC  9(6)
                  VALUE IS 0.
       77 Verdana18B-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 docs PIC  9(5).
       77 tipo-doc         PIC  S9(1)
                  VALUE IS 0.
       77 ef-path-buf      PIC  X(2000).
       77 opensave-status  PIC  s99
                  VALUE IS 0.
       77 como-anno        PIC  9(4).
       77 como-numero      PIC  9(8).
       77 wstampa          PIC  X(2000).
       77 STATUS-lineseq   PIC  X(2).
           88 Valid-STATUS-lineseq VALUE IS "00" THRU "09". 
       77 STATUS-tnotacr   PIC  X(2).
           88 Valid-STATUS-tnotacr VALUE IS "00" THRU "09". 
       77 STATUS-tordini   PIC  X(2).
           88 Valid-STATUS-tordini VALUE IS "00" THRU "09". 
       77 tipo-doc-s       PIC  S9(1)
                  VALUE IS 0.

      ***********************************************************
      *   Code Gen's Buffer                                     *
      ***********************************************************
       77 STATUS-form1-FLAG-REFRESH PIC  9.
          88 form1-FLAG-REFRESH  VALUE 1 FALSE 0. 
       77 TMP-DataSet1-lineseq-BUF     PIC X(1000).
       77 TMP-DataSet1-tnotacr-BUF     PIC X(752).
       77 TMP-DataSet1-tordini-BUF     PIC X(3898).
      * VARIABLES FOR RECORD LENGTH.
       77  TotemFdSlRecordClearOffset   PIC 9(5) COMP-4.
       77  TotemFdSlRecordLength        PIC 9(5) COMP-4.
      * FILE'S LOCK MODE FLAG
       77 DataSet1-lineseq-LOCK-FLAG   PIC X VALUE SPACE.
           88 DataSet1-lineseq-LOCK  VALUE "Y".
       77 DataSet1-lineseq-KEY-ORDER  PIC X VALUE "A".
          88 DataSet1-lineseq-KEY-Asc  VALUE "A".
          88 DataSet1-lineseq-KEY-Desc VALUE "D".
       77 DataSet1-tnotacr-LOCK-FLAG   PIC X VALUE SPACE.
           88 DataSet1-tnotacr-LOCK  VALUE "Y".
       77 DataSet1-tnotacr-KEY-ORDER  PIC X VALUE "A".
          88 DataSet1-tnotacr-KEY-Asc  VALUE "A".
          88 DataSet1-tnotacr-KEY-Desc VALUE "D".
       77 DataSet1-tordini-LOCK-FLAG   PIC X VALUE SPACE.
           88 DataSet1-tordini-LOCK  VALUE "Y".
       77 DataSet1-tordini-KEY-ORDER  PIC X VALUE "A".
          88 DataSet1-tordini-KEY-Asc  VALUE "A".
          88 DataSet1-tordini-KEY-Desc VALUE "D".

       77 tnotacr-k-causale-SPLITBUF  PIC X(17).
       77 tnotacr-k1-SPLITBUF  PIC X(23).
       77 tnotacr-k2-SPLITBUF  PIC X(21).
       77 tnotacr-k-fattura-SPLITBUF  PIC X(13).
       77 tnotacr-k4-SPLITBUF  PIC X(30).
       77 tnotacr-k-contab-SPLITBUF  PIC X(14).
       77 tnotacr-k-data-SPLITBUF  PIC X(17).
       77 tnotacr-k-agfatt-SPLITBUF  PIC X(42).
       77 tnotacr-k-andamento-data-SPLITBUF  PIC X(10).
       77 tnotacr-k-andamento-cliente-SPLITBUF  PIC X(15).
       77 tnotacr-k-andamento-clides-SPLITBUF  PIC X(20).
       77 tordini-k-causale-SPLITBUF  PIC X(17).
       77 tordini-k1-SPLITBUF  PIC X(23).
       77 tordini-k2-SPLITBUF  PIC X(21).
       77 tordini-k-bolla-SPLITBUF  PIC X(13).
       77 tordini-k3-SPLITBUF  PIC X(22).
       77 tordini-k-fattura-SPLITBUF  PIC X(13).
       77 tordini-k4-SPLITBUF  PIC X(30).
       77 tordini-k-contab-SPLITBUF  PIC X(14).
       77 tordini-k-tipo-SPLITBUF  PIC X(14).
       77 tordini-k-data-SPLITBUF  PIC X(17).
       77 tordini-k-agfatt-SPLITBUF  PIC X(42).
       77 tordini-k-stbolle-SPLITBUF  PIC X(34).
       77 tordini-k-andamento-data-SPLITBUF  PIC X(10).
       77 tordini-k-andamento-cliente-SPLITBUF  PIC X(15).
       77 tordini-k-andamento-clides-SPLITBUF  PIC X(20).
       77 tordini-k-promo-SPLITBUF  PIC X(29).
       77 tordini-k-or-SPLITBUF  PIC X(21).
       77 tordini-k-tor-inviare-SPLITBUF  PIC X(14).
       77 tordini-k-tor-tipocli-SPLITBUF  PIC X(25).
       77 tordini-k-tor-gdo-SPLITBUF  PIC X(28).

      *{TOTEM}END

      *{TOTEM}ID-LOGICI
      ***** Elenco ID Logici *****
       78  78-ID-rb-b VALUE 5001.
       78  78-ID-rb-f VALUE 5002.
       78  78-ID-rb-nc VALUE 5003.
       78  78-ID-ef-path VALUE 5004.
      ***** Fine ID Logici *****
      *{TOTEM}END

       LINKAGE          SECTION.
      *{TOTEM}LINKAGE
           COPY  "COMMON-LINKAGE.DEF".
      *{TOTEM}END

       SCREEN           SECTION.
      *{TOTEM}COPY-SCREEN
      * FORM
       01 
           form1, 
           HELP-ID 1,
           AFTER PROCEDURE  form1-AFTER-SCREEN
           .

      * RADIO BUTTON
       05
           rb-b, 
           Radio-Button, 
           COL 13,80, 
           LINE 2,90,
           LINES 2,00 CELLS,
           SIZE 1,50 CELLS,
           EXCEPTION-VALUE 1001
           FLAT,
           FONT IS Small-Font,
           GROUP 1,
           GROUP-VALUE 1,
           ID IS 78-ID-rb-b,                
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TITLE "&bolle",
           VALUE tipo-doc-s,
           AFTER PROCEDURE scr-elab-Rb-1-AfterProcedure, 
           BEFORE PROCEDURE scr-elab-Rb-1-BeforeProcedure, 
           .
      * RADIO BUTTON
       05
           rb-f, 
           Radio-Button, 
           COL 26,10, 
           LINE 2,90,
           LINES 2,00 CELLS,
           SIZE 1,50 CELLS,
           EXCEPTION-VALUE 1002
           FLAT,
           FONT IS Small-Font,
           GROUP 1,
           GROUP-VALUE 2,
           ID IS 78-ID-rb-f,                
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TITLE "&fatture",
           VALUE tipo-doc-s,
           AFTER PROCEDURE scr-elab-Rb-1-AfterProcedure, 
           BEFORE PROCEDURE scr-elab-Rb-1-BeforeProcedure, 
           .
      * RADIO BUTTON
       05
           rb-nc, 
           Radio-Button, 
           COL 39,10, 
           LINE 2,90,
           LINES 2,00 CELLS,
           SIZE 1,50 CELLS,
           EXCEPTION-VALUE 1003
           FLAT,
           FONT IS Small-Font,
           GROUP 1,
           GROUP-VALUE 3,
           ID IS 78-ID-rb-nc,                
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TITLE "&note credito",
           VALUE tipo-doc-s,
           AFTER PROCEDURE scr-elab-Rb-1-AfterProcedure, 
           BEFORE PROCEDURE scr-elab-Rb-1-BeforeProcedure, 
           .
      * ENTRY FIELD
       05
           ef-path, 
           Entry-Field, 
           COL 7,00, 
           LINE 6,40,
           LINES 2,50 CELLS,
           SIZE 49,90 CELLS,
           BOXED,
           COLOR IS 513,
           ID IS 78-ID-ef-path,                
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           MAX-TEXT 200,
           VALUE ef-path-buf,
           AFTER PROCEDURE scr-elab-Ef-1-AfterProcedure, 
           BEFORE PROCEDURE scr-elab-Ef-1-BeforeProcedure, 
           .


      * PUSH BUTTON
       05
           pb-sel, 
           Push-Button, 
           COL 56,90, 
           LINE 6,40,
           LINES 2,50 CELLS,
           SIZE 2,90 CELLS,
           EXCEPTION-VALUE 1004,
           FONT IS Small-Font,
           ID IS 6,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           SELF-ACT,
           TITLE "...",
           .

      * PUSH BUTTON
       05
           pb-sib, 
           Push-Button, 
           COL 44,50, 
           LINE 11,20,
           LINES 30,00 ,
           SIZE 73,00 ,
           BITMAP-HANDLE BOTTONE-OK-BMP,
           BITMAP-NUMBER 1,
           UNFRAMED,
           SQUARE,
           EXCEPTION-VALUE 1000,
           FLAT,
           FONT IS Small-Font,
           ID IS 5,
           AFTER PROCEDURE pb-sib-AfterProcedure, 
           BEFORE PROCEDURE pb-sib-BeforeProcedure, 
           .

      * PUSH BUTTON
       05
           pb-noa, 
           Push-Button, 
           COL 52,50, 
           LINE 11,20,
           LINES 30,00 ,
           SIZE 73,00 ,
           BITMAP-HANDLE BOTTONE-CANCEL-BMP,
           BITMAP-NUMBER 1,
           UNFRAMED,
           SQUARE,
           EXCEPTION-VALUE 27,
           FLAT,
           FONT IS Small-Font,
           ID IS 11,
           SELF-ACT,
           ESCAPE-BUTTON,
           AFTER PROCEDURE pb-noa-AfterProcedure, 
           BEFORE PROCEDURE pb-noa-BeforeProcedure, 
           .

      * BAR
       05
           Screen4-Br-1aaa, 
           Bar,
           COL 1,00, 
           LINE 11,00,
           SIZE 59,60 CELLS,
           ID IS 12,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           COLORS (8, 8),
           SHADING (-1, 1),
           WIDTH 2,
           .

      * LABEL
       05
           scr-elab-blockpgm-1, 
           Label, 
           COL 1,70, 
           LINE 11,80,
           LINES 1,70 CELLS,
           SIZE 3,20 CELLS,
           ID IS 2,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "BlockPgm",
           VISIBLE v-custom,
           .

      * LABEL
       05
           scr-elab-Custom1-1, 
           Label, 
           COL 7,90, 
           LINE 12,20,
           LINES 1,60 CELLS,
           SIZE 2,60 CELLS,
           FONT IS Default-Font,
           ID IS 7,
           TRANSPARENT,
           TITLE "CUSTOM CONTROL",
           VISIBLE v-custom,
           .

      * LABEL
       05
           scr-elab-La-1, 
           Label, 
           COL 16,30, 
           LINE 2,90,
           LINES 2,00 CELLS,
           SIZE 5,00 CELLS,
           ID IS 8,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "Bolle",
           .

      * LABEL
       05
           scr-elab-La-1a, 
           Label, 
           COL 28,60, 
           LINE 2,90,
           LINES 2,00 CELLS,
           SIZE 6,20 CELLS,
           ID IS 13,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "Fatture",
           .

      * LABEL
       05
           scr-elab-La-2, 
           Label, 
           COL 1,90, 
           LINE 6,40,
           LINES 2,50 CELLS,
           SIZE 3,60 CELLS,
           ID IS 4,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "File",
           .

      * LABEL
       05
           scr-elab-La-1aa, 
           Label, 
           COL 41,60, 
           LINE 2,90,
           LINES 2,00 CELLS,
           SIZE 11,00 CELLS,
           ID IS 14,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "Note credito",
           .

      *{TOTEM}END

      *{TOTEM}LINKPARA
       PROCEDURE  DIVISION USING LK-BLOCKPGM, USER-CODI, LIVELLO-ABIL.
      *{TOTEM}END

      *{TOTEM}DECLARATIVE
       DECLARATIVES.
      * <TOTEM:EPT. INIT:stdoccsv, INIT:stdoccsv, BeforeDeclarative>
      * <TOTEM:END>
       INPUT-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON INPUT.
       0100-DECL.
           EXIT.
       I-O-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON I-O.
       0200-DECL.
           EXIT.
       OUTPUT-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON OUTPUT.
       0300-DECL.
           EXIT.
       TRANSACTION-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON TRANSACTION.
       0400-DECL.
           EXIT.
       END DECLARATIVES.
      *{TOTEM}END

       MAIN-LOGIC.
      *{TOTEM}ENTRY-BEFPRG
      *    Before-Program
           PERFORM check-utf-Ev-Before-Program
      *{TOTEM}END
           PERFORM INITIALIZE-ROUTINE.
      * run main screen
      *{TOTEM}RUN-MAINSCR
           PERFORM form1-OPEN-ROUTINE.
      *{TOTEM}END

      *{TOTEM}COPY-PROCEDURE
       EXIT-STOP-ROUTINE.
           PERFORM CLOSE-FILE-RTN
      * <TOTEM:EPT. INIT:stdoccsv, INIT:stdoccsv, BeforeDestroyResource>
      * <TOTEM:END>
           DESTROY Verdana12-Occidentale
           CALL "w$bitmap" USING WBITMAP-DESTROY, BOTTONE-OK-BMP
           CALL "w$bitmap" USING WBITMAP-DESTROY, BOTTONE-CANCEL-BMP
      *    After-Program
           PERFORM check-utf-Ev-After-Program
           EXIT PROGRAM TOTEM-PgmStatus
           STOP RUN.

       INITIALIZE-ROUTINE.
      *    Before Init
      * initialize program status variable
           Initialize TOTEM-PgmStatus.
      * get system information
           ACCEPT SYSTEM-INFORMATION FROM SYSTEM-INFO.
      * get terminal information
           ACCEPT TERMINAL-ABILITIES FROM TERMINAL-INFO.
      * set font
           PERFORM INIT-FONT.
      * load bitmap
           PERFORM INIT-BMP.
      * load resource
           PERFORM INIT-RES.
      * create pop-up menu
           PERFORM INIT-POPUP.
      * open files
           PERFORM OPEN-FILE-RTN.
      *    After Init
           .
    
       INIT-FONT.
      * Verdana12-Occidentale
           INITIALIZE WFONT-DATA Verdana12-Occidentale
           MOVE 12 TO WFONT-SIZE
           MOVE "Verdana" TO WFONT-NAME
           SET WFCHARSET-DONT-CARE TO TRUE
           SET WFONT-BOLD TO FALSE
           SET WFONT-ITALIC TO FALSE
           SET WFONT-UNDERLINE TO FALSE
           SET WFONT-STRIKEOUT TO FALSE
           SET WFONT-FIXED-PITCH TO FALSE
           MOVE 0 TO WFONT-CHAR-SET
           CALL "W$FONT" USING WFONT-GET-FONT, 
                     Verdana12-Occidentale, WFONT-DATA
           .

       INIT-BMP.
      * pb-sib
           COPY RESOURCE "BOTTONE-OK.BMP".
           CALL "w$bitmap" USING WBITMAP-LOAD "BOTTONE-OK.BMP", 
                   GIVING BOTTONE-OK-BMP.
      * pb-noa
           COPY RESOURCE "BOTTONE-CANCEL.BMP".
           CALL "w$bitmap" USING WBITMAP-LOAD "BOTTONE-CANCEL.BMP", 
                   GIVING BOTTONE-CANCEL-BMP.
           .

       INIT-RES.
           .

       INIT-POPUP.
           .

       OPEN-FILE-RTN.
      *    Before Open
      *    lineseq OPEN MODE IS FALSE
      *    PERFORM OPEN-lineseq
           PERFORM OPEN-tnotacr
           PERFORM OPEN-tordini
      *    After Open
           .

       OPEN-lineseq.
      * <TOTEM:EPT. INIT:stdoccsv, FD:lineseq, BeforeOpen>
      * <TOTEM:END>
           OPEN  INPUT lineseq
           IF NOT Valid-STATUS-lineseq
              PERFORM  form1-EXTENDED-FILE-STATUS
              GO TO EXIT-STOP-ROUTINE
           END-IF
      * <TOTEM:EPT. INIT:stdoccsv, FD:lineseq, AfterOpen>
      * <TOTEM:END>
           .

       OPEN-tnotacr.
      * <TOTEM:EPT. INIT:stdoccsv, FD:tnotacr, BeforeOpen>
      * <TOTEM:END>
           OPEN  INPUT tnotacr
           IF NOT Valid-STATUS-tnotacr
              PERFORM  form1-EXTENDED-FILE-STATUS
              GO TO EXIT-STOP-ROUTINE
           END-IF
      * <TOTEM:EPT. INIT:stdoccsv, FD:tnotacr, AfterOpen>
      * <TOTEM:END>
           .

       OPEN-tordini.
      * <TOTEM:EPT. INIT:stdoccsv, FD:tordini, BeforeOpen>
      * <TOTEM:END>
           OPEN  INPUT tordini
           IF NOT Valid-STATUS-tordini
              PERFORM  form1-EXTENDED-FILE-STATUS
              GO TO EXIT-STOP-ROUTINE
           END-IF
      * <TOTEM:EPT. INIT:stdoccsv, FD:tordini, AfterOpen>
      * <TOTEM:END>
           .

       CLOSE-FILE-RTN.
      *    Before Close
      *    lineseq CLOSE MODE IS FALSE
      *    PERFORM CLOSE-lineseq
           PERFORM CLOSE-tnotacr
           PERFORM CLOSE-tordini
      *    After Close
           .

       CLOSE-lineseq.
      * <TOTEM:EPT. INIT:stdoccsv, FD:lineseq, BeforeClose>
      * <TOTEM:END>
           .

       CLOSE-tnotacr.
      * <TOTEM:EPT. INIT:stdoccsv, FD:tnotacr, BeforeClose>
      * <TOTEM:END>
           CLOSE tnotacr
           .

       CLOSE-tordini.
      * <TOTEM:EPT. INIT:stdoccsv, FD:tordini, BeforeClose>
      * <TOTEM:END>
           CLOSE tordini
           .

       DataSet1-lineseq-INITSTART.
           .

       DataSet1-lineseq-INITEND.
           .

       DataSet1-Change-CurrentKey-Asc.
           MOVE "A" TO DataSet1-lineseq-KEY-ORDER
           .

       DataSet1-Change-CurrentKey-Desc.
           MOVE "D" TO DataSet1-lineseq-KEY-ORDER
           .

       DataSet1-lineseq-Read.
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeReadRecord>
      * <TOTEM:END>
           IF DataSet1-lineseq-LOCK
              READ lineseq WITH LOCK 
           ELSE
              READ lineseq WITH NO LOCK 
           END-IF
           MOVE STATUS-lineseq TO TOTEM-ERR-STAT 
           MOVE "lineseq" TO TOTEM-ERR-FILE
           MOVE "READ" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterReadRecord>
      * <TOTEM:END>
           .

       DataSet1-lineseq-Read-Next.
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeReadNext>
      * <TOTEM:END>
           IF DataSet1-lineseq-KEY-Asc
              IF DataSet1-lineseq-LOCK
                 READ lineseq NEXT WITH LOCK
              ELSE
                 READ lineseq NEXT WITH NO LOCK
              END-IF
           END-IF
           MOVE STATUS-lineseq TO TOTEM-ERR-STAT
           MOVE "lineseq" TO TOTEM-ERR-FILE
           MOVE "READ NEXT" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterReadNext>
      * <TOTEM:END>
           .

       DataSet1-lineseq-Read-Prev.
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeReadPrev>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterReadPrev>
      * <TOTEM:END>
           .

       DataSet1-lineseq-Rec-Write.
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeWrite>
      * <TOTEM:END>
           MOVE STATUS-lineseq TO TOTEM-ERR-STAT
           MOVE "lineseq" TO TOTEM-ERR-FILE
           MOVE "WRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterWrite>
      * <TOTEM:END>
           .

       DataSet1-lineseq-Rec-Rewrite.
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeRewrite>
      * <TOTEM:END>
           MOVE STATUS-lineseq TO TOTEM-ERR-STAT
           MOVE "lineseq" TO TOTEM-ERR-FILE
           MOVE "REWRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterRewrite>
      * <TOTEM:END>
           .

       DataSet1-lineseq-Rec-Delete.
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, BeforeDelete>
      * <TOTEM:END>
           MOVE STATUS-lineseq TO TOTEM-ERR-STAT
           MOVE "lineseq" TO TOTEM-ERR-FILE
           MOVE "DELETE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:lineseq, AfterDelete>
      * <TOTEM:END>
           .

       tnotacr-k-causale-MERGE-SPLITBUF.
           INITIALIZE tnotacr-k-causale-SPLITBUF
           MOVE tno-causale(1:4) TO tnotacr-k-causale-SPLITBUF(1:4)
           MOVE tno-anno(1:4) TO tnotacr-k-causale-SPLITBUF(5:4)
           MOVE tno-numero(1:8) TO tnotacr-k-causale-SPLITBUF(9:8)
           .

       tnotacr-k1-MERGE-SPLITBUF.
           INITIALIZE tnotacr-k1-SPLITBUF
           MOVE tno-cod-cli(1:5) TO tnotacr-k1-SPLITBUF(1:5)
           MOVE tno-prg-destino(1:5) TO tnotacr-k1-SPLITBUF(6:5)
           MOVE tno-anno(1:4) TO tnotacr-k1-SPLITBUF(11:4)
           MOVE tno-numero(1:8) TO tnotacr-k1-SPLITBUF(15:8)
           .

       tnotacr-k2-MERGE-SPLITBUF.
           INITIALIZE tnotacr-k2-SPLITBUF
           MOVE tno-data-passaggio-ordine(1:8) TO 
           tnotacr-k2-SPLITBUF(1:8)
           MOVE tno-anno(1:4) TO tnotacr-k2-SPLITBUF(9:4)
           MOVE tno-numero(1:8) TO tnotacr-k2-SPLITBUF(13:8)
           .

       tnotacr-k-fattura-MERGE-SPLITBUF.
           INITIALIZE tnotacr-k-fattura-SPLITBUF
           MOVE tno-anno-fattura(1:4) TO tnotacr-k-fattura-SPLITBUF(1:4)
           MOVE tno-num-fattura(1:8) TO tnotacr-k-fattura-SPLITBUF(5:8)
           .

       tnotacr-k4-MERGE-SPLITBUF.
           INITIALIZE tnotacr-k4-SPLITBUF
           MOVE tno-anno-fattura(1:4) TO tnotacr-k4-SPLITBUF(1:4)
           MOVE tno-data-fattura(1:8) TO tnotacr-k4-SPLITBUF(5:8)
           MOVE tno-num-fattura(1:8) TO tnotacr-k4-SPLITBUF(13:8)
           MOVE tno-num-prenot(1:8) TO tnotacr-k4-SPLITBUF(21:8)
           MOVE tno-fatt-prenotata(1:1) TO tnotacr-k4-SPLITBUF(29:1)
           .

       tnotacr-k-contab-MERGE-SPLITBUF.
           INITIALIZE tnotacr-k-contab-SPLITBUF
           MOVE tno-agg-contab(1:1) TO tnotacr-k-contab-SPLITBUF(1:1)
           MOVE tno-anno-fattura(1:4) TO tnotacr-k-contab-SPLITBUF(2:4)
           MOVE tno-num-fattura(1:8) TO tnotacr-k-contab-SPLITBUF(6:8)
           .

       tnotacr-k-data-MERGE-SPLITBUF.
           INITIALIZE tnotacr-k-data-SPLITBUF
           MOVE tno-data(1:8) TO tnotacr-k-data-SPLITBUF(1:8)
           MOVE tno-numero(1:8) TO tnotacr-k-data-SPLITBUF(9:8)
           .

       tnotacr-k-agfatt-MERGE-SPLITBUF.
           INITIALIZE tnotacr-k-agfatt-SPLITBUF
           MOVE tno-anno-fattura(1:4) TO tnotacr-k-agfatt-SPLITBUF(1:4)
           MOVE tno-data-fattura(1:8) TO tnotacr-k-agfatt-SPLITBUF(5:8)
           MOVE tno-num-fattura(1:8) TO tnotacr-k-agfatt-SPLITBUF(13:8)
           MOVE tno-num-prenot(1:8) TO tnotacr-k-agfatt-SPLITBUF(21:8)
           MOVE tno-fatt-prenotata(1:1) TO 
           tnotacr-k-agfatt-SPLITBUF(29:1)
           MOVE tno-chiave(1:12) TO tnotacr-k-agfatt-SPLITBUF(30:12)
           .

       tnotacr-k-andamento-data-MERGE-SPLITBUF.
           INITIALIZE tnotacr-k-andamento-data-SPLITBUF
           MOVE tno-agg-contab(1:1) TO 
           tnotacr-k-andamento-data-SPLITBUF(1:1)
           MOVE tno-data-fattura(1:8) TO 
           tnotacr-k-andamento-data-SPLITBUF(2:8)
           .

       tnotacr-k-andamento-cliente-MERGE-SPLITBUF.
           INITIALIZE tnotacr-k-andamento-cliente-SPLITBUF
           MOVE tno-cod-cli(1:5) TO 
           tnotacr-k-andamento-cliente-SPLITBUF(1:5)
           MOVE tno-agg-contab(1:1) TO 
           tnotacr-k-andamento-cliente-SPLITBUF(6:1)
           MOVE tno-data-fattura(1:8) TO 
           tnotacr-k-andamento-cliente-SPLITBUF(7:8)
           .

       tnotacr-k-andamento-clides-MERGE-SPLITBUF.
           INITIALIZE tnotacr-k-andamento-clides-SPLITBUF
           MOVE tno-cod-cli(1:5) TO 
           tnotacr-k-andamento-clides-SPLITBUF(1:5)
           MOVE tno-prg-destino(1:5) TO 
           tnotacr-k-andamento-clides-SPLITBUF(6:5)
           MOVE tno-agg-contab(1:1) TO 
           tnotacr-k-andamento-clides-SPLITBUF(11:1)
           MOVE tno-data-fattura(1:8) TO 
           tnotacr-k-andamento-clides-SPLITBUF(12:8)
           .

       DataSet1-tnotacr-INITSTART.
           IF DataSet1-tnotacr-KEY-Asc
              MOVE Low-Value TO tno-chiave
           ELSE
              MOVE High-Value TO tno-chiave
           END-IF
           .

       DataSet1-tnotacr-INITEND.
           IF DataSet1-tnotacr-KEY-Asc
              MOVE High-Value TO tno-chiave
           ELSE
              MOVE Low-Value TO tno-chiave
           END-IF
           .

      * tnotacr
       DataSet1-tnotacr-START.
           IF DataSet1-tnotacr-KEY-Asc
              START tnotacr KEY >= tno-chiave
           ELSE
              START tnotacr KEY <= tno-chiave
           END-IF
           .

       DataSet1-tnotacr-START-NOTGREATER.
           IF DataSet1-tnotacr-KEY-Asc
              START tnotacr KEY <= tno-chiave
           ELSE
              START tnotacr KEY >= tno-chiave
           END-IF
           .

       DataSet1-tnotacr-START-GREATER.
           IF DataSet1-tnotacr-KEY-Asc
              START tnotacr KEY > tno-chiave
           ELSE
              START tnotacr KEY < tno-chiave
           END-IF
           .

       DataSet1-tnotacr-START-LESS.
           IF DataSet1-tnotacr-KEY-Asc
              START tnotacr KEY < tno-chiave
           ELSE
              START tnotacr KEY > tno-chiave
           END-IF
           .

       DataSet1-tnotacr-Read.
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, BeforeReadRecord>
      * <TOTEM:END>
           IF DataSet1-tnotacr-LOCK
              READ tnotacr WITH LOCK 
              KEY tno-chiave
           ELSE
              READ tnotacr WITH NO LOCK 
              KEY tno-chiave
           END-IF
           PERFORM tnotacr-k-causale-MERGE-SPLITBUF
           PERFORM tnotacr-k1-MERGE-SPLITBUF
           PERFORM tnotacr-k2-MERGE-SPLITBUF
           PERFORM tnotacr-k-fattura-MERGE-SPLITBUF
           PERFORM tnotacr-k4-MERGE-SPLITBUF
           PERFORM tnotacr-k-contab-MERGE-SPLITBUF
           PERFORM tnotacr-k-data-MERGE-SPLITBUF
           PERFORM tnotacr-k-agfatt-MERGE-SPLITBUF
           PERFORM tnotacr-k-andamento-data-MERGE-SPLITBUF
           PERFORM tnotacr-k-andamento-cliente-MERGE-SPLITBUF
           PERFORM tnotacr-k-andamento-clides-MERGE-SPLITBUF
           MOVE STATUS-tnotacr TO TOTEM-ERR-STAT 
           MOVE "tnotacr" TO TOTEM-ERR-FILE
           MOVE "READ" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, AfterReadRecord>
      * <TOTEM:END>
           .

       DataSet1-tnotacr-Read-Next.
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, BeforeReadNext>
      * <TOTEM:END>
           IF DataSet1-tnotacr-KEY-Asc
              IF DataSet1-tnotacr-LOCK
                 READ tnotacr NEXT WITH LOCK
              ELSE
                 READ tnotacr NEXT WITH NO LOCK
              END-IF
           ELSE
              IF DataSet1-tnotacr-LOCK
                 READ tnotacr PREVIOUS WITH LOCK
              ELSE
                 READ tnotacr PREVIOUS WITH NO LOCK
              END-IF
           END-IF
           PERFORM tnotacr-k-causale-MERGE-SPLITBUF
           PERFORM tnotacr-k1-MERGE-SPLITBUF
           PERFORM tnotacr-k2-MERGE-SPLITBUF
           PERFORM tnotacr-k-fattura-MERGE-SPLITBUF
           PERFORM tnotacr-k4-MERGE-SPLITBUF
           PERFORM tnotacr-k-contab-MERGE-SPLITBUF
           PERFORM tnotacr-k-data-MERGE-SPLITBUF
           PERFORM tnotacr-k-agfatt-MERGE-SPLITBUF
           PERFORM tnotacr-k-andamento-data-MERGE-SPLITBUF
           PERFORM tnotacr-k-andamento-cliente-MERGE-SPLITBUF
           PERFORM tnotacr-k-andamento-clides-MERGE-SPLITBUF
           MOVE STATUS-tnotacr TO TOTEM-ERR-STAT
           MOVE "tnotacr" TO TOTEM-ERR-FILE
           MOVE "READ NEXT" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, AfterReadNext>
      * <TOTEM:END>
           .

       DataSet1-tnotacr-Read-Prev.
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, BeforeReadPrev>
      * <TOTEM:END>
           IF DataSet1-tnotacr-KEY-Asc
              IF DataSet1-tnotacr-LOCK
                 READ tnotacr PREVIOUS WITH LOCK
              ELSE
                 READ tnotacr PREVIOUS WITH NO LOCK
              END-IF
           ELSE
              IF DataSet1-tnotacr-LOCK
                 READ tnotacr NEXT WITH LOCK
              ELSE
                 READ tnotacr NEXT WITH NO LOCK
              END-IF
           END-IF
           PERFORM tnotacr-k-causale-MERGE-SPLITBUF
           PERFORM tnotacr-k1-MERGE-SPLITBUF
           PERFORM tnotacr-k2-MERGE-SPLITBUF
           PERFORM tnotacr-k-fattura-MERGE-SPLITBUF
           PERFORM tnotacr-k4-MERGE-SPLITBUF
           PERFORM tnotacr-k-contab-MERGE-SPLITBUF
           PERFORM tnotacr-k-data-MERGE-SPLITBUF
           PERFORM tnotacr-k-agfatt-MERGE-SPLITBUF
           PERFORM tnotacr-k-andamento-data-MERGE-SPLITBUF
           PERFORM tnotacr-k-andamento-cliente-MERGE-SPLITBUF
           PERFORM tnotacr-k-andamento-clides-MERGE-SPLITBUF
           MOVE STATUS-tnotacr TO TOTEM-ERR-STAT
           MOVE "tnotacr" TO TOTEM-ERR-FILE
           MOVE "READ PREVIOUS" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, AfterReadPrev>
      * <TOTEM:END>
           .

       DataSet1-tnotacr-Rec-Write.
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, BeforeWrite>
      * <TOTEM:END>
           MOVE STATUS-tnotacr TO TOTEM-ERR-STAT
           MOVE "tnotacr" TO TOTEM-ERR-FILE
           MOVE "WRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, AfterWrite>
      * <TOTEM:END>
           .

       DataSet1-tnotacr-Rec-Rewrite.
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, BeforeRewrite>
      * <TOTEM:END>
           MOVE STATUS-tnotacr TO TOTEM-ERR-STAT
           MOVE "tnotacr" TO TOTEM-ERR-FILE
           MOVE "REWRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, AfterRewrite>
      * <TOTEM:END>
           .

       DataSet1-tnotacr-Rec-Delete.
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, BeforeDelete>
      * <TOTEM:END>
           MOVE STATUS-tnotacr TO TOTEM-ERR-STAT
           MOVE "tnotacr" TO TOTEM-ERR-FILE
           MOVE "DELETE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tnotacr, AfterDelete>
      * <TOTEM:END>
           .

       tordini-k-causale-MERGE-SPLITBUF.
           INITIALIZE tordini-k-causale-SPLITBUF
           MOVE tor-causale(1:4) TO tordini-k-causale-SPLITBUF(1:4)
           MOVE tor-anno(1:4) TO tordini-k-causale-SPLITBUF(5:4)
           MOVE tor-numero(1:8) TO tordini-k-causale-SPLITBUF(9:8)
           .

       tordini-k1-MERGE-SPLITBUF.
           INITIALIZE tordini-k1-SPLITBUF
           MOVE tor-cod-cli(1:5) TO tordini-k1-SPLITBUF(1:5)
           MOVE tor-prg-destino(1:5) TO tordini-k1-SPLITBUF(6:5)
           MOVE tor-anno(1:4) TO tordini-k1-SPLITBUF(11:4)
           MOVE tor-numero(1:8) TO tordini-k1-SPLITBUF(15:8)
           .

       tordini-k2-MERGE-SPLITBUF.
           INITIALIZE tordini-k2-SPLITBUF
           MOVE tor-data-passaggio-ordine(1:8) TO 
           tordini-k2-SPLITBUF(1:8)
           MOVE tor-anno(1:4) TO tordini-k2-SPLITBUF(9:4)
           MOVE tor-numero(1:8) TO tordini-k2-SPLITBUF(13:8)
           .

       tordini-k-bolla-MERGE-SPLITBUF.
           INITIALIZE tordini-k-bolla-SPLITBUF
           MOVE tor-anno-bolla(1:4) TO tordini-k-bolla-SPLITBUF(1:4)
           MOVE tor-num-bolla(1:8) TO tordini-k-bolla-SPLITBUF(5:8)
           .

       tordini-k3-MERGE-SPLITBUF.
           INITIALIZE tordini-k3-SPLITBUF
           MOVE tor-anno-bolla(1:4) TO tordini-k3-SPLITBUF(1:4)
           MOVE tor-data-bolla(1:8) TO tordini-k3-SPLITBUF(5:8)
           MOVE tor-num-bolla(1:8) TO tordini-k3-SPLITBUF(13:8)
           MOVE tor-bolla-prenotata(1:1) TO tordini-k3-SPLITBUF(21:1)
           .

       tordini-k-fattura-MERGE-SPLITBUF.
           INITIALIZE tordini-k-fattura-SPLITBUF
           MOVE tor-anno-fattura(1:4) TO tordini-k-fattura-SPLITBUF(1:4)
           MOVE tor-num-fattura(1:8) TO tordini-k-fattura-SPLITBUF(5:8)
           .

       tordini-k4-MERGE-SPLITBUF.
           INITIALIZE tordini-k4-SPLITBUF
           MOVE tor-anno-fattura(1:4) TO tordini-k4-SPLITBUF(1:4)
           MOVE tor-data-fattura(1:8) TO tordini-k4-SPLITBUF(5:8)
           MOVE tor-num-fattura(1:8) TO tordini-k4-SPLITBUF(13:8)
           MOVE tor-num-prenot(1:8) TO tordini-k4-SPLITBUF(21:8)
           MOVE tor-fatt-prenotata(1:1) TO tordini-k4-SPLITBUF(29:1)
           .

       tordini-k-contab-MERGE-SPLITBUF.
           INITIALIZE tordini-k-contab-SPLITBUF
           MOVE tor-agg-contab(1:1) TO tordini-k-contab-SPLITBUF(1:1)
           MOVE tor-anno-fattura(1:4) TO tordini-k-contab-SPLITBUF(2:4)
           MOVE tor-num-fattura(1:8) TO tordini-k-contab-SPLITBUF(6:8)
           .

       tordini-k-tipo-MERGE-SPLITBUF.
           INITIALIZE tordini-k-tipo-SPLITBUF
           MOVE tor-tipo(1:1) TO tordini-k-tipo-SPLITBUF(1:1)
           MOVE tor-chiave(1:12) TO tordini-k-tipo-SPLITBUF(2:12)
           .

       tordini-k-data-MERGE-SPLITBUF.
           INITIALIZE tordini-k-data-SPLITBUF
           MOVE tor-data-creazione(1:8) TO tordini-k-data-SPLITBUF(1:8)
           MOVE tor-numero(1:8) TO tordini-k-data-SPLITBUF(9:8)
           .

       tordini-k-agfatt-MERGE-SPLITBUF.
           INITIALIZE tordini-k-agfatt-SPLITBUF
           MOVE tor-anno-fattura(1:4) TO tordini-k-agfatt-SPLITBUF(1:4)
           MOVE tor-data-fattura(1:8) TO tordini-k-agfatt-SPLITBUF(5:8)
           MOVE tor-num-fattura(1:8) TO tordini-k-agfatt-SPLITBUF(13:8)
           MOVE tor-num-prenot(1:8) TO tordini-k-agfatt-SPLITBUF(21:8)
           MOVE tor-fatt-prenotata(1:1) TO 
           tordini-k-agfatt-SPLITBUF(29:1)
           MOVE tor-chiave(1:12) TO tordini-k-agfatt-SPLITBUF(30:12)
           .

       tordini-k-stbolle-MERGE-SPLITBUF.
           INITIALIZE tordini-k-stbolle-SPLITBUF
           MOVE tor-anno-bolla(1:4) TO tordini-k-stbolle-SPLITBUF(1:4)
           MOVE tor-data-bolla(1:8) TO tordini-k-stbolle-SPLITBUF(5:8)
           MOVE tor-num-bolla(1:8) TO tordini-k-stbolle-SPLITBUF(13:8)
           MOVE tor-bolla-prenotata(1:1) TO 
           tordini-k-stbolle-SPLITBUF(21:1)
           MOVE tor-chiave(1:12) TO tordini-k-stbolle-SPLITBUF(22:12)
           .

       tordini-k-andamento-data-MERGE-SPLITBUF.
           INITIALIZE tordini-k-andamento-data-SPLITBUF
           MOVE tor-agg-contab(1:1) TO 
           tordini-k-andamento-data-SPLITBUF(1:1)
           MOVE tor-data-fattura(1:8) TO 
           tordini-k-andamento-data-SPLITBUF(2:8)
           .

       tordini-k-andamento-cliente-MERGE-SPLITBUF.
           INITIALIZE tordini-k-andamento-cliente-SPLITBUF
           MOVE tor-cod-cli(1:5) TO 
           tordini-k-andamento-cliente-SPLITBUF(1:5)
           MOVE tor-agg-contab(1:1) TO 
           tordini-k-andamento-cliente-SPLITBUF(6:1)
           MOVE tor-data-fattura(1:8) TO 
           tordini-k-andamento-cliente-SPLITBUF(7:8)
           .

       tordini-k-andamento-clides-MERGE-SPLITBUF.
           INITIALIZE tordini-k-andamento-clides-SPLITBUF
           MOVE tor-cod-cli(1:5) TO 
           tordini-k-andamento-clides-SPLITBUF(1:5)
           MOVE tor-prg-destino(1:5) TO 
           tordini-k-andamento-clides-SPLITBUF(6:5)
           MOVE tor-agg-contab(1:1) TO 
           tordini-k-andamento-clides-SPLITBUF(11:1)
           MOVE tor-data-fattura(1:8) TO 
           tordini-k-andamento-clides-SPLITBUF(12:8)
           .

       tordini-k-promo-MERGE-SPLITBUF.
           INITIALIZE tordini-k-promo-SPLITBUF
           MOVE tor-stato(1:1) TO tordini-k-promo-SPLITBUF(1:1)
           MOVE tor-promo(1:1) TO tordini-k-promo-SPLITBUF(2:1)
           MOVE tor-data-ordine(1:8) TO tordini-k-promo-SPLITBUF(3:8)
           MOVE tor-numero(1:8) TO tordini-k-promo-SPLITBUF(11:8)
           MOVE tor-cod-cli(1:5) TO tordini-k-promo-SPLITBUF(19:5)
           MOVE tor-prg-destino(1:5) TO tordini-k-promo-SPLITBUF(24:5)
           .

       tordini-k-or-MERGE-SPLITBUF.
           INITIALIZE tordini-k-or-SPLITBUF
           MOVE tor-cod-cli(1:5) TO tordini-k-or-SPLITBUF(1:5)
           MOVE tor-prg-destino(1:5) TO tordini-k-or-SPLITBUF(6:5)
           MOVE tor-num-ord-cli(1:10) TO tordini-k-or-SPLITBUF(11:10)
           .

       tordini-k-tor-inviare-MERGE-SPLITBUF.
           INITIALIZE tordini-k-tor-inviare-SPLITBUF
           MOVE tor-da-inviare OF tordini(1:1) TO 
           tordini-k-tor-inviare-SPLITBUF(1:1)
           MOVE tor-chiave OF tordini(1:12) TO 
           tordini-k-tor-inviare-SPLITBUF(2:12)
           .

       tordini-k-tor-tipocli-MERGE-SPLITBUF.
           INITIALIZE tordini-k-tor-tipocli-SPLITBUF
           MOVE tor-tipocli OF tordini(1:2) TO 
           tordini-k-tor-tipocli-SPLITBUF(1:2)
           MOVE tor-cod-cli OF tordini(1:5) TO 
           tordini-k-tor-tipocli-SPLITBUF(3:5)
           MOVE tor-prg-destino OF tordini(1:5) TO 
           tordini-k-tor-tipocli-SPLITBUF(8:5)
           MOVE tor-chiave OF tordini(1:12) TO 
           tordini-k-tor-tipocli-SPLITBUF(13:12)
           .

       tordini-k-tor-gdo-MERGE-SPLITBUF.
           INITIALIZE tordini-k-tor-gdo-SPLITBUF
           MOVE tor-gdo OF tordini(1:5) TO 
           tordini-k-tor-gdo-SPLITBUF(1:5)
           MOVE tor-cod-cli OF tordini(1:5) TO 
           tordini-k-tor-gdo-SPLITBUF(6:5)
           MOVE tor-prg-destino OF tordini(1:5) TO 
           tordini-k-tor-gdo-SPLITBUF(11:5)
           MOVE tor-chiave OF tordini(1:12) TO 
           tordini-k-tor-gdo-SPLITBUF(16:12)
           .

       DataSet1-tordini-INITSTART.
           IF DataSet1-tordini-KEY-Asc
              MOVE Low-Value TO tor-chiave
           ELSE
              MOVE High-Value TO tor-chiave
           END-IF
           .

       DataSet1-tordini-INITEND.
           IF DataSet1-tordini-KEY-Asc
              MOVE High-Value TO tor-chiave
           ELSE
              MOVE Low-Value TO tor-chiave
           END-IF
           .

      * tordini
       DataSet1-tordini-START.
           IF DataSet1-tordini-KEY-Asc
              START tordini KEY >= tor-chiave
           ELSE
              START tordini KEY <= tor-chiave
           END-IF
           .

       DataSet1-tordini-START-NOTGREATER.
           IF DataSet1-tordini-KEY-Asc
              START tordini KEY <= tor-chiave
           ELSE
              START tordini KEY >= tor-chiave
           END-IF
           .

       DataSet1-tordini-START-GREATER.
           IF DataSet1-tordini-KEY-Asc
              START tordini KEY > tor-chiave
           ELSE
              START tordini KEY < tor-chiave
           END-IF
           .

       DataSet1-tordini-START-LESS.
           IF DataSet1-tordini-KEY-Asc
              START tordini KEY < tor-chiave
           ELSE
              START tordini KEY > tor-chiave
           END-IF
           .

       DataSet1-tordini-Read.
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, BeforeReadRecord>
      * <TOTEM:END>
           IF DataSet1-tordini-LOCK
              READ tordini WITH LOCK 
              KEY tor-chiave
           ELSE
              READ tordini WITH NO LOCK 
              KEY tor-chiave
           END-IF
           PERFORM tordini-k-causale-MERGE-SPLITBUF
           PERFORM tordini-k1-MERGE-SPLITBUF
           PERFORM tordini-k2-MERGE-SPLITBUF
           PERFORM tordini-k-bolla-MERGE-SPLITBUF
           PERFORM tordini-k3-MERGE-SPLITBUF
           PERFORM tordini-k-fattura-MERGE-SPLITBUF
           PERFORM tordini-k4-MERGE-SPLITBUF
           PERFORM tordini-k-contab-MERGE-SPLITBUF
           PERFORM tordini-k-tipo-MERGE-SPLITBUF
           PERFORM tordini-k-data-MERGE-SPLITBUF
           PERFORM tordini-k-agfatt-MERGE-SPLITBUF
           PERFORM tordini-k-stbolle-MERGE-SPLITBUF
           PERFORM tordini-k-andamento-data-MERGE-SPLITBUF
           PERFORM tordini-k-andamento-cliente-MERGE-SPLITBUF
           PERFORM tordini-k-andamento-clides-MERGE-SPLITBUF
           PERFORM tordini-k-promo-MERGE-SPLITBUF
           PERFORM tordini-k-or-MERGE-SPLITBUF
           PERFORM tordini-k-tor-inviare-MERGE-SPLITBUF
           PERFORM tordini-k-tor-tipocli-MERGE-SPLITBUF
           PERFORM tordini-k-tor-gdo-MERGE-SPLITBUF
           MOVE STATUS-tordini TO TOTEM-ERR-STAT 
           MOVE "tordini" TO TOTEM-ERR-FILE
           MOVE "READ" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, AfterReadRecord>
      * <TOTEM:END>
           .

       DataSet1-tordini-Read-Next.
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, BeforeReadNext>
      * <TOTEM:END>
           IF DataSet1-tordini-KEY-Asc
              IF DataSet1-tordini-LOCK
                 READ tordini NEXT WITH LOCK
              ELSE
                 READ tordini NEXT WITH NO LOCK
              END-IF
           ELSE
              IF DataSet1-tordini-LOCK
                 READ tordini PREVIOUS WITH LOCK
              ELSE
                 READ tordini PREVIOUS WITH NO LOCK
              END-IF
           END-IF
           PERFORM tordini-k-causale-MERGE-SPLITBUF
           PERFORM tordini-k1-MERGE-SPLITBUF
           PERFORM tordini-k2-MERGE-SPLITBUF
           PERFORM tordini-k-bolla-MERGE-SPLITBUF
           PERFORM tordini-k3-MERGE-SPLITBUF
           PERFORM tordini-k-fattura-MERGE-SPLITBUF
           PERFORM tordini-k4-MERGE-SPLITBUF
           PERFORM tordini-k-contab-MERGE-SPLITBUF
           PERFORM tordini-k-tipo-MERGE-SPLITBUF
           PERFORM tordini-k-data-MERGE-SPLITBUF
           PERFORM tordini-k-agfatt-MERGE-SPLITBUF
           PERFORM tordini-k-stbolle-MERGE-SPLITBUF
           PERFORM tordini-k-andamento-data-MERGE-SPLITBUF
           PERFORM tordini-k-andamento-cliente-MERGE-SPLITBUF
           PERFORM tordini-k-andamento-clides-MERGE-SPLITBUF
           PERFORM tordini-k-promo-MERGE-SPLITBUF
           PERFORM tordini-k-or-MERGE-SPLITBUF
           PERFORM tordini-k-tor-inviare-MERGE-SPLITBUF
           PERFORM tordini-k-tor-tipocli-MERGE-SPLITBUF
           PERFORM tordini-k-tor-gdo-MERGE-SPLITBUF
           MOVE STATUS-tordini TO TOTEM-ERR-STAT
           MOVE "tordini" TO TOTEM-ERR-FILE
           MOVE "READ NEXT" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, AfterReadNext>
      * <TOTEM:END>
           .

       DataSet1-tordini-Read-Prev.
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, BeforeReadPrev>
      * <TOTEM:END>
           IF DataSet1-tordini-KEY-Asc
              IF DataSet1-tordini-LOCK
                 READ tordini PREVIOUS WITH LOCK
              ELSE
                 READ tordini PREVIOUS WITH NO LOCK
              END-IF
           ELSE
              IF DataSet1-tordini-LOCK
                 READ tordini NEXT WITH LOCK
              ELSE
                 READ tordini NEXT WITH NO LOCK
              END-IF
           END-IF
           PERFORM tordini-k-causale-MERGE-SPLITBUF
           PERFORM tordini-k1-MERGE-SPLITBUF
           PERFORM tordini-k2-MERGE-SPLITBUF
           PERFORM tordini-k-bolla-MERGE-SPLITBUF
           PERFORM tordini-k3-MERGE-SPLITBUF
           PERFORM tordini-k-fattura-MERGE-SPLITBUF
           PERFORM tordini-k4-MERGE-SPLITBUF
           PERFORM tordini-k-contab-MERGE-SPLITBUF
           PERFORM tordini-k-tipo-MERGE-SPLITBUF
           PERFORM tordini-k-data-MERGE-SPLITBUF
           PERFORM tordini-k-agfatt-MERGE-SPLITBUF
           PERFORM tordini-k-stbolle-MERGE-SPLITBUF
           PERFORM tordini-k-andamento-data-MERGE-SPLITBUF
           PERFORM tordini-k-andamento-cliente-MERGE-SPLITBUF
           PERFORM tordini-k-andamento-clides-MERGE-SPLITBUF
           PERFORM tordini-k-promo-MERGE-SPLITBUF
           PERFORM tordini-k-or-MERGE-SPLITBUF
           PERFORM tordini-k-tor-inviare-MERGE-SPLITBUF
           PERFORM tordini-k-tor-tipocli-MERGE-SPLITBUF
           PERFORM tordini-k-tor-gdo-MERGE-SPLITBUF
           MOVE STATUS-tordini TO TOTEM-ERR-STAT
           MOVE "tordini" TO TOTEM-ERR-FILE
           MOVE "READ PREVIOUS" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, AfterReadPrev>
      * <TOTEM:END>
           .

       DataSet1-tordini-Rec-Write.
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, BeforeWrite>
      * <TOTEM:END>
           MOVE STATUS-tordini TO TOTEM-ERR-STAT
           MOVE "tordini" TO TOTEM-ERR-FILE
           MOVE "WRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, AfterWrite>
      * <TOTEM:END>
           .

       DataSet1-tordini-Rec-Rewrite.
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, BeforeRewrite>
      * <TOTEM:END>
           MOVE STATUS-tordini TO TOTEM-ERR-STAT
           MOVE "tordini" TO TOTEM-ERR-FILE
           MOVE "REWRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, AfterRewrite>
      * <TOTEM:END>
           .

       DataSet1-tordini-Rec-Delete.
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, BeforeDelete>
      * <TOTEM:END>
           MOVE STATUS-tordini TO TOTEM-ERR-STAT
           MOVE "tordini" TO TOTEM-ERR-FILE
           MOVE "DELETE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tordini, AfterDelete>
      * <TOTEM:END>
           .

       DataSet1-INIT-RECORD.
           INITIALIZE line-riga OF lineseq
           INITIALIZE tno-rec OF tnotacr
           INITIALIZE tor-rec OF tordini
           .


      * FD's Initialize Paragraph
       DataSet1-lineseq-INITREC.
           INITIALIZE line-riga OF lineseq
               REPLACING NUMERIC       DATA BY ZEROS
                         ALPHANUMERIC  DATA BY SPACES
                         ALPHABETIC    DATA BY SPACES
           .

      * FD's Initialize Paragraph
       DataSet1-tnotacr-INITREC.
           INITIALIZE tno-rec OF tnotacr
               REPLACING NUMERIC       DATA BY ZEROS
                         ALPHANUMERIC  DATA BY SPACES
                         ALPHABETIC    DATA BY SPACES
           .

      * FD's Initialize Paragraph
       DataSet1-tordini-INITREC.
           INITIALIZE tor-rec OF tordini
               REPLACING NUMERIC       DATA BY ZEROS
                         ALPHANUMERIC  DATA BY SPACES
                         ALPHABETIC    DATA BY SPACES
           .

      *
       DataSet1-DISPATCH-BUFTOFLD.
           .

       form1-Open-Routine.
           PERFORM form1-Scrn
           PERFORM form1-Proc
           .

       form1-Scrn.
           PERFORM form1-Create-Win
           PERFORM form1-Init-Value
           PERFORM form1-Init-Data
      * Tab keystrok settings
      * Tool Bar
           PERFORM form1-DISPLAY
           .

       form1-Create-Win.
           Display Independent GRAPHICAL WINDOW
              LINES 13,90,
              SIZE 59,60,
              CELL HEIGHT 10,
              CELL WIDTH 10,
              HEIGHT-IN-CELLS,
              WIDTH-IN-CELLS,
              COLOR 65793,
              ERASE,
              CONTROL FONT Verdana12-Occidentale,
              LABEL-OFFSET 0,
              LINK TO THREAD,
              MODELESS,
              NO SCROLL,
              TITLE-BAR,
              TITLE titolo,
              AUTO-MINIMIZE,
              WITH SYSTEM MENU,
              USER-GRAY,
              USER-WHITE,
              No WRAP,
              HANDLE IS form1-handle,
      * <TOTEM:EPT. FORM:form1, FORM:form1, AfterCreateWin>
      * <TOTEM:END>


      * Tool Bar    
      * Status-bar
           DISPLAY form1 UPON form1-handle
      * DISPLAY-COLUMNS settings
           .

       form1-PROC.
      * <TOTEM:EPT. FORM:form1, FORM:form1, BeforeAccept>
           move 1 to tipo-doc-s.
           display form1.

           .
      * <TOTEM:END>
           PERFORM UNTIL Exit-Pushed
              ACCEPT form1
                 ON EXCEPTION
                    PERFORM form1-Evaluate-Func
                 MOVE 1 TO TOTEM-Form-Index
              END-ACCEPT
      * <TOTEM:EPT. FORM:form1, FORM:form1, AfterEndAccept>
      * <TOTEM:END>
           END-PERFORM
      * <TOTEM:EPT. FORM:form1, FORM:form1, BeforeDestroyWindow>
      * <TOTEM:END>
           DESTROY form1-handle
           INITIALIZE Key-Status
           .

       form1-Evaluate-Func.
      * <TOTEM:EPT. FORM:form1, FORM:form1, AfterAccept>
      * <TOTEM:END>
           EVALUATE TRUE
              WHEN Exit-Pushed
                 PERFORM form1-Exit
              WHEN Event-Occurred
                 IF Event-Type = Cmd-Close
                    PERFORM form1-Exit
                 END-IF
              WHEN Key-Status = 1001
                 PERFORM rb-b-LinkTo
              WHEN Key-Status = 1002
                 PERFORM rb-f-LinkTo
              WHEN Key-Status = 1003
                 PERFORM rb-nc-LinkTo
              WHEN Key-Status = 1004
                 PERFORM pb-sel-LinkTo
              WHEN Key-Status = 1000
                 PERFORM pb-sib-LinkTo
           END-EVALUATE
      * avoid changing focus
           MOVE 4 TO Accept-Control
           .

       form1-CLEAR.
           PERFORM form1-INIT-VALUE
           PERFORM form1-DISPLAY
           .

       form1-DISPLAY.
      * <TOTEM:EPT. FORM:form1, FORM:form1, BeforeDisplay>
      * <TOTEM:END>
           DISPLAY form1 UPON form1-handle
      * <TOTEM:EPT. FORM:form1, FORM:form1, AfterDisplay>
           SET LK-BL-SCRITTURA     TO TRUE.
           MOVE COMO-PROG-ID       TO LK-BL-PROG-ID.
           MOVE FORM1-HANDLE       TO LK-HND-WIN.
           CALL "BLOCKPGM"  USING LK-BLOCKPGM.
           CANCEL "BLOCKPGM".

           .
      * <TOTEM:END>
           .

       form1-Exit.
      * for main screen
      * <TOTEM:EPT. FORM:form1, FORM:form1, BeforeExit>
      * <TOTEM:END>
           MOVE 27 TO Key-Status
           .

       form1-Init-Data.
           MOVE 1 TO TOTEM-Form-Index
           MOVE 0 TO TOTEM-Frame-Index
           .

       form1-Init-Value.
           MOVE titolo TO TOTEM-MSG-TITLE
      * <TOTEM:EPT. FORM:form1, FORM:form1, SetDefault>
      * <TOTEM:END>
           PERFORM form1-FLD-TO-BUF
           .


       form1-ALLGRID-RESET.
           .

      * for Form's Validation
       form1-VALIDATION-ROUTINE.
           SET TOTEM-CHECK-OK TO TRUE
           .


       form1-Buf-To-Fld.
      * <TOTEM:EPT. FORM:form1, FORM:form1, BeforeBufToFld>
      * <TOTEM:END>
      * <TOTEM:EPT. FORM:form1, FORM:form1, AfterBufToFld>
      * <TOTEM:END>
           .

       form1-Fld-To-Buf.
      * <TOTEM:EPT. FORM:form1, FORM:form1, BeforeFldToBuf>
      * <TOTEM:END>
      * <TOTEM:EPT. FORM:form1, FORM:form1, AfterFldToBuf>
      * <TOTEM:END>
           .

       form1-CONTROLLO-OLD.
           set SiSalvato to true.
           if mod = 0 exit paragraph end-if.
           perform form1-BUF-TO-FLD.
           move 0 to scelta.
           .
       form1-EXTENDED-FILE-STATUS.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
           MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           PERFORM form1-SHOW-MSG-ROUTINE
           .

       form1-SHOW-MSG-ROUTINE.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM form1-DISPLAY-MESSAGE
           .

       form1-DISPLAY-MESSAGE.
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

       form1-Save-Status.
           .             

       form1-Restore-Status.
           .


      * Paragrafo per la struttura del codice in AFTER sulla screen form1
      ***---
       form1-AFTER-SCREEN.

      * Generazione risettaggio keyboard "." ---> "."

      * Generazione stringa perform CONTROLLO
           evaluate control-id
           |78-ID-ef-path è l'ID del campo ef-path
           when 78-ID-ef-path
                perform CONTROLLO
           |99999 è un valore fittizio, che non sarà MAI usato,
           |ma mi serve per non riscontrare errori di compilazione
           |in caso non avessi generato nulla nella AFTER CONTROLLO della screen
           when 99999 continue
           when other continue
           end-evaluate.



      * USER DEFINE PARAGRAPH
       CONTROLLO.
      * <TOTEM:PARA. CONTROLLO>
           set tutto-ok to true.
           evaluate control-id
           when 78-ID-ef-path
                inquire ef-path, value in ef-path-buf
                if ef-path-buf = spaces
                   set errori to true
                   display message "Selezionare un file"
                             title tit-err
                              icon 2
                else
                   move ef-path-buf to wstampa
                   open input lineseq
                   if status-lineseq not = "00"
                      set errori to true
                      display message "File non valido"
                                title tit-err
                                 icon 2
                   else
                      close lineseq
                   end-if
                end-if

           end-evaluate.

           if errori
              move 4 to accept-control
           end-if 
           .
      * <TOTEM:END>

      * EVENT PARAGRAPH
       pb-sib-AfterProcedure.
      * <TOTEM:PARA. pb-sib-AfterProcedure>
           modify pb-sib, bitmap-number = 1 
           .
      * <TOTEM:END>
       pb-noa-BeforeProcedure.
      * <TOTEM:PARA. pb-noa-BeforeProcedure>
           modify pb-noa, bitmap-number = 2 
           .
      * <TOTEM:END>
       pb-noa-AfterProcedure.
      * <TOTEM:PARA. pb-noa-AfterProcedure>
           modify pb-noa, bitmap-number = 1 
           .
      * <TOTEM:END>
       pb-sib-BeforeProcedure.
      * <TOTEM:PARA. pb-sib-BeforeProcedure>
           modify pb-sib, bitmap-number = 2 
           .
      * <TOTEM:END>
       pb-sib-LinkTo.
      * <TOTEM:PARA. pb-sib-LinkTo>
           perform varying control-id from 78-ID-ef-path by 1
                     until control-id > 78-ID-ef-path
               perform CONTROLLO
               if errori
                  exit perform
               end-if
           end-perform.

           if tutto-ok
              evaluate tipo-doc-s
              when 1
                   display message "Confermi la ristampa delle bolle?"
                             title titolo
                              icon 2
                              type mb-yes-no
                           default mb-no
                            giving scelta
              when 2
                   display message "Confermi la ristampa delle fatture?"
                             title titolo
                              icon 2
                              type mb-yes-no
                           default mb-no
                            giving scelta
              when 3
                   display message "Confermi la ristampa delle note cred
      -    "ito?"
                             title titolo
                              icon 2
                              type mb-yes-no
                           default mb-no
                            giving scelta
              end-evaluate
              if scelta = mb-no
                 set errori to true
              end-if
           end-if.

           if tutto-ok
              move 0 to docs
              call "W$MOUSE" using set-mouse-shape, wait-pointer
              move ef-path-buf to wstampa
              open input lineseq
              move 0 to docs
              perform until 1 = 2
                 read lineseq next at end exit perform end-read
                 unstring line-riga delimited by ";"
                     into como-anno 
                          como-numero 
                 end-unstring
                 add 1 to docs
                 evaluate tipo-doc-s
                 when 1 perform CHECK-BOLLE
                 when 2 perform CHECK-FATTURE
                 when 3 perform CHECK-NOTECR
                 end-evaluate
                 if errori
                    exit perform
                 end-if
              end-perform
              close lineseq
              if tutto-ok
                 evaluate tipo-doc-s
                 when 1 perform STAMPA-BOLLE
                 when 2 perform STAMPA-FATTURE
                 when 3 perform STAMPA-NOTECR
                 end-evaluate             
                 display message "OPERAZIONE TERMINATA!!!"          
                           title titolo
                           icon 2
      *****                         x"0d0a""STAMPATE " docs " BOLLE"
      *****           when 2
      *****                display message "OPERAZIONE TERMINATA!!!"
      *****                         x"0d0a""STAMPATE " docs " FATTURE"
      *****                          title titolo
      *****                           icon 2
      *****           when 3
      *****                display message "OPERAZIONE TERMINATA!!!"
      *****                         x"0d0a""STAMPATE " docs " NOTE CREDITO"
      *****                          title titolo
      *****                           icon 2
      *****           end-evaluate
              end-if
              call "W$MOUSE" using set-mouse-shape, arrow-pointer 
              modify pb-sib, bitmap-number = 1
              move             4 to accept-control
           end-if.

      ***---
       CHECK-BOLLE.           
           move como-anno   to tor-anno-bolla.
           move como-numero to tor-num-bolla.
           read tordini key k-bolla
                invalid
                display message "Elaborazione non valida!"
                         x"0d0a""Bolla non valida" 
                         x"0d0a""ANNO: ", como-anno
                         x"0d0a""NUMERO: ", como-numero
                         x"0d0a""Riga: ", docs
                set errori to true
           end-read.    

      ***---
       CHECK-FATTURE.           
           move como-anno   to tor-anno-fattura.
           move como-numero to tor-num-fattura.
           read tordini key k-fattura
                invalid
                display message "Elaborazione non valida!"
                         x"0d0a""Fattura non valida" 
                         x"0d0a""ANNO: ", como-anno
                         x"0d0a""NUMERO: ", como-numero
                         x"0d0a""Riga: ", docs
                set errori to true
           end-read.    

      ***---
       CHECK-NOTECR.
           move como-anno   to tno-anno-fattura.
           move como-numero to tno-num-fattura.
           read tnotacr key k-fattura
                invalid
                display message "Elaborazione non valida!"
                         x"0d0a""Nota CR non valida" 
                         x"0d0a""ANNO: ", como-anno
                         x"0d0a""NUMERO: ", como-numero
                         x"0d0a""Riga: ", docs
                set errori to true
           end-read.    

      ***---
       STAMPA-BOLLE.
           initialize stbolle-linkage.
           set stbolle-ristampa to true.
           move tor-anno        to stbolle-anno.
           move ef-path-buf     to stbolle-path-csv.
           set  stbolle-k-bolla to true.
           set  stbolle-singola to true.

           move spaces to stbolle-path.
           call   "stbolle-p" using stbolle-linkage.
           cancel "stbolle-p".

      ***---
       STAMPA-FATTURE.  
           initialize stfatt-linkage replacing numeric data by zeroes
                                          alphanumeric data by spaces.
           move ef-path-buf      to stfatt-path-csv.
           move 1                to LinkElab.
           set  tutte            to true.
           move 1                to num-copie.
           set  Fatture          to true.
           |STAMPA "COPIA" AD USO INTERNO
LUBEXX     move 1 to link-tipo-stampa.

           call   "stfatt-p"  using stfatt-linkage.
           cancel "stfatt-p".

      ***---
       STAMPA-NOTECR.   
           initialize stfatt-linkage replacing numeric data by zeroes
                                          alphanumeric data by spaces.
           move ef-path-buf      to stfatt-path-csv.
           move 1                to LinkElab.
           set  tutte            to true.
           move 1                to num-copie.
           set  NoteCredito      to true.
           |STAMPA "COPIA" AD USO INTERNO
LUBEXX     move 1 to link-tipo-stampa. 

           call   "stfatt-p"  using stfatt-linkage.
           cancel "stfatt-p" 
           .
      * <TOTEM:END>
       check-utf-Ev-Before-Program.
      * <TOTEM:PARA. check-utf-Ev-Before-Program>
           move LK-BL-PROG-ID    TO COMO-PROG-ID 
           .
      * <TOTEM:END>
       check-utf-Ev-After-Program.
      * <TOTEM:PARA. check-utf-Ev-After-Program>
           SET LK-BL-CANCELLAZIONE TO TRUE.
           MOVE COMO-PROG-ID       TO LK-BL-PROG-ID.
           CALL "BLOCKPGM"  USING LK-BLOCKPGM 
           .
      * <TOTEM:END>
       scr-elab-Rb-1-BeforeProcedure.
      * <TOTEM:PARA. scr-elab-Rb-1-BeforeProcedure>
           modify control-handle, color = colore-nu
           .
      * <TOTEM:END>
       scr-elab-Rb-1-AfterProcedure.
      * <TOTEM:PARA. scr-elab-Rb-1-AfterProcedure>
           modify control-handle, color = colore-or
           .
      * <TOTEM:END>
       scr-elab-Ef-1-BeforeProcedure.
      * <TOTEM:PARA. scr-elab-Ef-1-BeforeProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-NU
           .
      * <TOTEM:END>
       scr-elab-Ef-1-AfterProcedure.
      * <TOTEM:PARA. scr-elab-Ef-1-AfterProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-OR
           perform CONTROLLO 
           .
      * <TOTEM:END>
       rb-b-LinkTo.
      * <TOTEM:PARA. rb-b-LinkTo>
           move 1 to tipo-doc-s 
           .
      * <TOTEM:END>
       rb-f-LinkTo.
      * <TOTEM:PARA. rb-f-LinkTo>
           move 2 to tipo-doc-s 
           .
      * <TOTEM:END>
       rb-nc-LinkTo.
      * <TOTEM:PARA. rb-nc-LinkTo>
           move 3 to tipo-doc-s 
           .
      * <TOTEM:END>
       pb-sel-LinkTo.
      * <TOTEM:PARA. pb-sel-LinkTo>
           initialize opnsav-filters
           move "CSV files (*.csv)|*.csv" to  opnsav-filters.
           move 1 to opnsav-default-filter
           move "Geslux -  Selezione csv elenco" to opnsav-title
           call "C$OPENSAVEBOX" using opensave-save-box, 
                                      opensave-data,
                               giving opensave-status
      
           if opensave-status = 1      
              move opnsav-filename to ef-path-buf
              display ef-path
           end-if 
           .
      * <TOTEM:END>

      *{TOTEM}END

      *{TOTEM}SHOW-MSG
       MESSAGE-FOR-FILEERROR.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
              MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           .

       SHOW-TRANSACTION-ROUTINE.
           IF TOTEM-TRANSACTION-FLAG = SPACES
              IF TRANSACTION-STATUS NOT = 0
                 STRING "TRANSACTION ERROR ", TRANSACTION-STATUS
                    DELIMITED BY SIZE INTO TOTEM-MSG-1
              END-IF
           ELSE
              PERFORM SHOW-MSG-ROUTINE
              IF TRANSACTION-STATUS = 0
                 MOVE "Transazione terminata con Rollback." TO 
           TOTEM-MSG-3
              ELSE
                 STRING "TRANSACTION ERROR ", TRANSACTION-STATUS
                    DELIMITED BY SIZE INTO TOTEM-MSG-3
              END-IF
           END-IF
           .

       SHOW-MSG-ROUTINE.
           MOVE SPACE TO TOTEM-MSG-1 TOTEM-MSG-2 TOTEM-MSG-3
           EVALUATE TOTEM-MSG-ID
               WHEN "10"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Nessun altro dato." TO TOTEM-MSG-2
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "22"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Chiave Duplicata." TO TOTEM-MSG-2
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "23"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Raggiunta fine file." TO TOTEM-MSG-2
                    MOVE MB-WARNING-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "101"
                    MOVE "Terminare l'applicazione?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "201"
                    MOVE "Aggiungere un nuovo record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "202"
                    MOVE "Aggiornare il Record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "203"
                    MOVE "Cancellare il Record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "204"
                    MOVE "Chiave duplicata." TO TOTEM-MSG-1
                    MOVE MB-WARNING-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "301"
                    MOVE "Inserimento avvenuto con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "302"
                    MOVE "Aggiornamento avvenuto con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "303"
                    MOVE "Cancellazione avvenuta con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "401"
                    MOVE "Shell non trovata." TO TOTEM-MSG-1
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN OTHER
                    MOVE TEXT-MESSAGE TO TOTEM-MSG-1
                    STRING "FILE:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-3
                    MOVE 0 TO TOTEM-IDX1
                    INSPECT TOTEM-MSG-3 TALLYING TOTEM-IDX1
                       FOR TRAILING SPACE
                    STRING TOTEM-MSG-3(1:TOTEM-MSG-LENGTH - 
           TOTEM-IDX1), 
                       ", FILE STATUS ", PRIMARY-ERROR "," 
                       SECONDARY-ERROR
                    DELIMITED BY SIZE INTO TOTEM-MSG-2
                    MOVE SPACES TO TOTEM-MSG-3
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
           END-EVALUATE
           PERFORM MESSAGE-BOX-ROUTINE
           .

       MESSAGE-BOX-ROUTINE.
           MOVE 1 TO TOTEM-MSG-TEXT-POINTER
           IF TOTEM-MSG-1 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-1 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              STRING TOTEM-MSG-1( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                 DELIMITED BY SIZE
                 INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-2 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-2 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              IF TOTEM-MSG-TEXT-POINTER > 1
                 STRING X"0A" DELIMITED BY SIZE
                     INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
              END-IF
              STRING TOTEM-MSG-2( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                  DELIMITED BY SIZE
                  INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-3 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-3 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              IF TOTEM-MSG-TEXT-POINTER > 1
                 STRING X"0A" DELIMITED BY SIZE
                     INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
              END-IF
              STRING TOTEM-MSG-3( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                  DELIMITED BY SIZE
                  INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-TEXT-POINTER = 1
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-TEXT TALLYING TOTEM-MSG-SIZE FOR 
           TRAILING SPACE
                  COMPUTE TOTEM-MSG-TEXT-POINTER = 
           TOTEM-MSG-FULL-LENGTH - TOTEM-MSG-SIZE + 1
           END-IF
           MOVE LOW-VALUES TO TOTEM-MSG-TEXT(TOTEM-MSG-TEXT-POINTER : 1 
           )
           .

       MESSAGE-BOX-DISPLAY.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

      *{TOTEM}END

