      *{TOTEM}PRG-COMMENT
      * tgruppi.Cbl
      * tgruppi.Cbl is generated by TOTEM
      * This is a generated file. DO NOT modify this file directly.
      *{TOTEM}END
       IDENTIFICATION       DIVISION.
      *{TOTEM}PRGID
       PROGRAM-ID.          tgruppi.
       AUTHOR.              ANDREA EVENTI.
       DATE-WRITTEN.        martedì 1 aprile 2014 19:19:53.
       REMARKS.
      *{TOTEM}END

       ENVIRONMENT          DIVISION.
       CONFIGURATION        SECTION.
       SPECIAL-NAMES.
      *{TOTEM}SPECIAL-NAME
      * <TOTEM:EPT. INIT:tgruppi, INIT:tgruppi, SpecialName>
      * <TOTEM:END>
      *{TOTEM}END
      *{TOTEM}ACTIVEX-DEF
      *{TOTEM}END
      *{TOTEM}DECIMAL-POINT
           DECIMAL-POINT IS COMMA.
      *{TOTEM}END

       INPUT-OUTPUT         SECTION.
       FILE-CONTROL.
      *{TOTEM}FILE-CONTROL
           COPY "tgruppi.sl".
      *{TOTEM}END
       DATA                 DIVISION.
       FILE                 SECTION.
      *{TOTEM}FILE
           COPY "tgruppi.fd".
      *{TOTEM}END

       WORKING-STORAGE      SECTION.
      *{TOTEM}ACU-DEF
               COPY "acugui.def".
               COPY "acucobol.def".
               COPY "fonts.def".
               COPY "crtvars.def".
               COPY "showmsg.def".
               COPY "totem.def".
               COPY "F:\Lubex\GESLUX\Copylib\UTYDATA.DEF".
               COPY "F:\Lubex\GESLUX\Copylib\comune.def".
               COPY "F:\Lubex\GESLUX\Copylib\custom.def".
      *{TOTEM}END

      *{TOTEM}COPY-WORKING
      * Key Status
       77 Key-Status IS SPECIAL-NAMES CRT STATUS PIC 9(5) VALUE 0.
          88 Enter-Pushed VALUE 13.
          88 Exit-Pushed VALUE 27.
          88 Message-Received VALUE 95.
          88 Event-Occurred VALUE 96.
          88 Screen-No-Input-Field VALUE 97.
      * Properties & User defined Working Stoarge
       77 Form1-Handle
                  USAGE IS HANDLE OF WINDOW.
       77 Form1-Tb-1-Handle
                  USAGE IS HANDLE OF WINDOW.
       77 E-ESCI           PIC  9
                  VALUE IS 1.
       77 E-NUOVO          PIC  9
                  VALUE IS 1.
       77 E-CANCELLA       PIC  9
                  VALUE IS 1.
       77 E-SALVA          PIC  9
                  VALUE IS 1.
       77 E-ANTEPRIMA      PIC  9
                  VALUE IS 0.
       77 E-MODIFICA       PIC  9
                  VALUE IS 1.
       77 E-STAMPA         PIC  9
                  VALUE IS 0.
       77 E-CERCA          PIC  9
                  VALUE IS 0.
       77 Form1-St-1-Handle
                  USAGE IS HANDLE OF STATUS-BAR.
       77 E-SELEZIONA      PIC  9
                  VALUE IS 1.
       77 toolbar-bmp
                  USAGE IS HANDLE OF BITMAP
                  VALUE IS 0.
       77 Screen1-Handle
                  USAGE IS HANDLE OF WINDOW.
       77 Default-Font
                  USAGE IS HANDLE OF FONT DEFAULT-FONT.
       77 Small-Font
                  USAGE IS HANDLE OF FONT SMALL-FONT.
       78 TITOLO VALUE IS "Geslux - Gestione gruppi di invio". 
       77 AUTO-ID          PIC  9(6)
                  VALUE IS 0.
       01 save-key.
           10 save-codice      PIC  9(5).
       77 Verdana10-Occidentale
                  USAGE IS HANDLE OF FONT.
       77 STATUS-tgruppi   PIC  X(2).
           88 Valid-STATUS-tgruppi VALUE IS "00" THRU "09". 
       01 OLD-tgr-rec.
           05 OLD-tgr-chiave.
               10 OLD-tgr-codice   PIC  9(5).
           05 OLD-tgr-dati.
               10 OLD-tgr-descrizione          PIC  x(100).
               10 OLD-tgr-email    PIC  x(2500).
               10 OLD-tgr-comuni.
                   15 OLD-tgr-data-creazione       PIC  9(8).
                   15 OLD-tgr-ora-creazione        PIC  9(8).
                   15 OLD-tgr-utente-creazione     PIC  x(10).
                   15 OLD-tgr-data-ultima-modifica PIC  9(8).
                   15 OLD-tgr-ora-ultima-modifica  PIC  9(8).
                   15 OLD-tgr-utente-ultima-modifica           PIC  
           x(10).
               10 OLD-tgr-vuoti.
                   15 OLD-tgr-num-vuoto-1          PIC  9(15).
                   15 OLD-tgrr-num-vuoto-2         PIC  9(15).
                   15 OLD-tgrr-num-vuoto-3         PIC  9(15).
                   15 OLD-tgr-alfa-vuoto-1         PIC  x(500).

      ***********************************************************
      *   Code Gen's Buffer                                     *
      ***********************************************************
       77 STATUS-Form1-FLAG-REFRESH PIC  9.
          88 Form1-FLAG-REFRESH  VALUE 1 FALSE 0. 
      * DATA CONTROL BUFFER
       01 Form1-BUF.
      * Data.Entry-Field
              05 ef-codice-BUF PIC 9(5).
      * Data.Entry-Field
              05 ef-descr-BUF PIC x(100).
      * Data.Entry-Field
              05 ef-email-BUF PIC x(2500).

       77 TMP-Form1-KEY1-ORDER  PIC X VALUE "A".
       77 TMP-Form1-tgruppi-RESTOREBUF  PIC X(3202).
       77 TMP-Form1-KEYIS  PIC 9(3) VALUE 1.
       77 Form1-MULKEY-TMPBUF   PIC X(3202).
       77 TMP-DataSet1-tgruppi-BUF     PIC X(3202).
      * VARIABLES FOR RECORD LENGTH.
       77  TotemFdSlRecordClearOffset   PIC 9(5) COMP-4.
       77  TotemFdSlRecordLength        PIC 9(5) COMP-4.
      * FILE'S LOCK MODE FLAG
       77 DataSet1-tgruppi-LOCK-FLAG   PIC X VALUE SPACE.
           88 DataSet1-tgruppi-LOCK  VALUE "Y".
       77 DataSet1-KEYIS   PIC 9(3) VALUE 1.
       77 DataSet1-tgruppi-KEY1-ORDER  PIC X VALUE "A".
          88 DataSet1-tgruppi-KEY1-Asc  VALUE "A".
          88 DataSet1-tgruppi-KEY1-Desc VALUE "D".


      *{TOTEM}END

      *{TOTEM}ID-LOGICI
      ***** Elenco ID Logici *****
       78  78-ID-ef-codice VALUE 5001.
       78  78-ID-ef-descr VALUE 5002.
       78  78-ID-ef-email VALUE 5003.
      ***** Fine ID Logici *****
      *{TOTEM}END

       LINKAGE          SECTION.
      *{TOTEM}LINKAGE
           COPY  "COMMON-LINKAGE.DEF".

      *{TOTEM}END

       SCREEN           SECTION.
      *{TOTEM}COPY-SCREEN
      * FORM
       01 
           Form1, 
           AFTER PROCEDURE Form1-AfterProcedure,
           BEFORE PROCEDURE Form1-BeforeProcedure,
           .

      * ENTRY FIELD
       05
           ef-codice, 
           Entry-Field, 
           COL 16,00, 
           LINE 2,00,
           LINES 1,31 ,
           SIZE 9,00 ,
           BOXED,
           UPPER,
           COLOR IS 513,
           ENABLED mod-k,
           HELP-ID AUTO-ID,
           ID IS 78-ID-ef-codice,                
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           MAX-TEXT 5,
           VALUE ef-codice-BUF,
           .

      * ENTRY FIELD
       05
           ef-descr, 
           Entry-Field, 
           COL 16,00, 
           LINE 5,00,
           LINES 1,31 ,
           SIZE 90,00 ,
           BOXED,
           COLOR IS 513,
           ENABLED mod,
           ID IS 78-ID-ef-descr,                
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           MAX-TEXT 100,
           VALUE ef-descr-BUF,
           .

      * LABEL
       05
           Form1-La-5aa, 
           Label, 
           COL 3,00, 
           LINE 2,00,
           LINES 1,31 ,
           SIZE 12,00 ,
           ID IS 102,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TITLE "Codice",
           .

      * LABEL
       05
           Form1-blockpgm-1, 
           Label, 
           COL 45,17, 
           LINE 2,31,
           LINES 0,62 ,
           SIZE 2,00 ,
           ID IS 103,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "BlockPgm",
           VISIBLE v-custom,
           .

      * LABEL
       05
           Form1-Custom1-1, 
           Label, 
           COL 37,83, 
           LINE 2,23,
           LINES 1,15 ,
           SIZE 2,00 ,
           ID IS 3,
           TRANSPARENT,
           TITLE "CUSTOM CONTROL",
           VISIBLE v-custom,
           .

      * BAR
       05
           Form1-Br-1, 
           Bar,
           COL 1,00, 
           LINE 3,92,
           SIZE 110,00 ,
           ID IS 4,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           COLORS (8, 8),
           SHADING (-1, 1),
           WIDTH 2,
           .

      * LABEL
       05
           Form1-La-1, 
           Label, 
           COL 3,00, 
           LINE 5,00,
           LINES 1,31 ,
           SIZE 12,00 ,
           ID IS 1,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "Descrizione",
           .

      * LABEL
       05
           Form1-La-1a, 
           Label, 
           COL 3,00, 
           LINE 7,00,
           LINES 1,31 ,
           SIZE 12,00 ,
           ID IS 2,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE "Indirizzi",
           .

      * ENTRY FIELD
       05
           ef-email, 
           Entry-Field, 
           COL 16,00, 
           LINE 7,00,
           LINES 12,00 ,
           SIZE 92,50 ,
           BOXED,
           COLOR IS 513,
           ENABLED mod,
           ID IS 78-ID-ef-email,                
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           MAX-TEXT 2500,
           VSCROLL-BAR,
           VALUE ef-email-BUF,
           .

      * LABEL
       05
           Form1-La-2, 
           Label, 
           COL 16,00, 
           LINE 19,50,
           LINES 1,25 ,
           SIZE 92,50 ,
           COLOR IS 5,
           ID IS 7,
           HEIGHT-IN-CELLS,
           WIDTH-IN-CELLS,
           TRANSPARENT,
           TITLE 'Separare gli indirizzi con ";"',
           .

      * TOOLBAR
       01
           Form1-Tb-1,
           .    

      * PUSH BUTTON
       05
           TOOL-ESCI, 
           Push-Button, 
           COL 1,00, 
           LINE 1,08,
           LINES 23,00 ,
           SIZE 24,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 1,
           FRAMED,
           SQUARE,
           ENABLED E-ESCI,
           EXCEPTION-VALUE 27,
           FLAT,
           ID IS 2223,
           SELF-ACT,
           ESCAPE-BUTTON,
           TITLE "Esci (Esc)",
           .

      * PUSH BUTTON
       05
           TOOL-NUOVO, 
           Push-Button, 
           COL 6,00, 
           LINE 1,08,
           LINES 23,00 ,
           SIZE 24,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 2,
           FRAMED,
           SQUARE,
           ENABLED E-NUOVO,
           EXCEPTION-VALUE 2,
           FLAT,
           ID IS 208,
           SELF-ACT,
           TITLE "Nuovo (F2)",
           bitmap-number BitmapNumNew
           .

      * PUSH BUTTON
       05
           TOOL-CANCELLA, 
           Push-Button, 
           COL 16,00, 
           LINE 1,08,
           LINES 23,00 ,
           SIZE 24,00 ,
           BITMAP-HANDLE toolbar-bmp,
           FRAMED,
           SQUARE,
           ENABLED E-CANCELLA,
           EXCEPTION-VALUE 4,
           FLAT,
           ID IS 106,
           SELF-ACT,
           TITLE "Cancella (F4)",
           BITMAP-NUMBER BitmapNumDelete
           .

      * PUSH BUTTON
       05
           TOOL-SALVA, 
           Push-Button, 
           COL 11,00, 
           LINE 1,08,
           LINES 23,00 ,
           SIZE 24,00 ,
           BITMAP-HANDLE toolbar-bmp,
           FRAMED,
           SQUARE,
           ENABLED E-SALVA,
           EXCEPTION-VALUE 3,
           FLAT,
           ID IS 75,
           SELF-ACT,
           TITLE "Salva (F3)",
           BITMAP-NUMBER BitmapNumSave
           .

      * PUSH BUTTON
       05
           TOOL-ANTEPRIMA, 
           Push-Button, 
           COL 26,00, 
           LINE 1,08,
           LINES 23,00 ,
           SIZE 24,00 ,
           BITMAP-HANDLE toolbar-bmp,
           FRAMED,
           SQUARE,
           ENABLED E-ANTEPRIMA,
           EXCEPTION-VALUE 6,
           FLAT,
           ID IS 76,
           SELF-ACT,
           TITLE "Anteprima (F6)",
           BITMAP-NUMBER BitmapNumPreview
           .

      * CHECK BOX
       05
           TOOL-MODIFICA, 
           Check-Box, 
           COL 21,00, 
           LINE 1,08,
           LINES 23,00 ,
           SIZE 24,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 5,
           FRAMED,
           SQUARE,
           ENABLED E-MODIFICA,
           EXCEPTION-VALUE 150
           FLAT,
           ID IS 77,
           SELF-ACT,
           TITLE "Modifica (F5)",
           VALUE MOD,
           AFTER PROCEDURE TOOL-MODIFICA-AfterProcedure,
           BEFORE PROCEDURE TOOL-MODIFICA-BeforeProcedure, 
           .
      * PUSH BUTTON
       05
           TOOL-STAMPA, 
           Push-Button, 
           COL 31,00, 
           LINE 1,15,
           LINES 23,00 ,
           SIZE 24,00 ,
           BITMAP-HANDLE toolbar-bmp,
           FRAMED,
           SQUARE,
           ENABLED E-STAMPA,
           EXCEPTION-VALUE 7,
           FLAT,
           ID IS 110,
           SELF-ACT,
           TITLE "Stampa (F7)",
           BITMAP-NUMBER BitmapNumPrint
           .

      * PUSH BUTTON
       05
           TOOL-CERCA, 
           Push-Button, 
           COL 36,00, 
           LINE 1,08,
           LINES 23,00 ,
           SIZE 24,00 ,
           BITMAP-HANDLE toolbar-bmp,
           FRAMED,
           SQUARE,
           ENABLED E-CERCA,
           EXCEPTION-VALUE 8,
           FLAT,
           ID IS 111,
           SELF-ACT,
           TITLE "Cerca (F8)",
           BITMAP-NUMBER BitmapNumZoom
           .

      * PUSH BUTTON
       05
           TOOL-SELEZIONA, 
           Push-Button, 
           COL 41,00, 
           LINE 1,08,
           LINES 23,00 ,
           SIZE 24,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 9,
           FRAMED,
           SQUARE,
           ENABLED E-SELEZIONA,
           EXCEPTION-VALUE 9,
           FLAT,
           ID IS 112,
           SELF-ACT,
           TITLE "Seleziona (F9)",
           .

      * PUSH BUTTON
       05
           Form1-Pb-1a, 
           Push-Button, 
           COL 46,00, 
           LINE 1,08,
           LINES 23,00 ,
           SIZE 24,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 10,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 1002,
           FLAT,
           ID IS 113,
           SELF-ACT,
           TITLE "&Primo",
           .

      * PUSH BUTTON
       05
           Form1-Pb-1b, 
           Push-Button, 
           COL 51,00, 
           LINE 1,08,
           LINES 23,00 ,
           SIZE 24,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 11,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 67,
           FLAT,
           ID IS 114,
           SELF-ACT,
           TITLE "Precedente (PgDn)",
           .

      * PUSH BUTTON
       05
           Form1-Pb-1c, 
           Push-Button, 
           COL 56,00, 
           LINE 1,08,
           LINES 23,00 ,
           SIZE 24,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 12,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 68,
           FLAT,
           ID IS 115,
           SELF-ACT,
           TITLE "Successivo (PgUp)",
           .

      * PUSH BUTTON
       05
           Form1-Pb-1d, 
           Push-Button, 
           COL 61,00, 
           LINE 1,08,
           LINES 23,00 ,
           SIZE 24,00 ,
           BITMAP-HANDLE toolbar-bmp,
           BITMAP-NUMBER 13,
           FRAMED,
           SQUARE,
           EXCEPTION-VALUE 1006,
           FLAT,
           ID IS 116,
           SELF-ACT,
           TITLE "&Ultimo",
           .

      *{TOTEM}END

      *{TOTEM}LINKPARA
       PROCEDURE  DIVISION USING LK-BLOCKPGM, USER-CODI, LIVELLO-ABIL.
      *{TOTEM}END

      *{TOTEM}DECLARATIVE
       DECLARATIVES.
      * <TOTEM:EPT. INIT:tgruppi, INIT:tgruppi, BeforeDeclarative>
       tgruppi-ERR SECTION.
           use after error procedure on tgruppi.
           set RecLocked to false.
           evaluate status-tgruppi
           when "35"
                display message "File [tgruppi] not found!"
                           title titolo
                            icon 3
                set errori to true
           when "39"
                display message "File [tgruppi] Mismatch size!"
                           title titolo
                            icon 3
                set errori to true
           when "98"
                display message "[tgruppi] Indexed file corrupt!"
                           title titolo
                            icon 3
                set errori to true
           when "93" 
                display message box "File già in uso"
                          title tit-err
                           icon 3
                perform ANAGR01-EV-AFTER-PROGRAM
                goback
           when "99" 
                set RecLocked to true
                set errori    to true
                move 1 to mod-k
                move 0 to mod
                modify tool-modifica, value  mod
                display form1
                set StatusVisua to true
                perform STATUS-BAR-MSG
                move "00" to status-tgruppi
                if ReadSecca
                   read  tgruppi no lock 
                         invalid  continue
                     not invalid  perform FORM1-IUD-DISPLAY
                   end-read
                end-if
                display message MSG-Record-gia-in-uso
                        title = tit-err
                        icon is mb-error-icon
           when "23"            
                move 1 to mod-k
                move 0 to mod
                modify tool-modifica, value = mod
                set StatusVisua to true
                perform STATUS-BAR-MSG 
                if nuovo              
                   initialize tgr-rec of tgruppi 
                              replacing numeric data by zeroes
                                   alphanumeric data by spaces
                   perform FORM1-FLD-TO-BUF
                   display form1-tb-1
                   set vecchio to true
                end-if       
                perform ABILITAZIONI
                display form1
                |RISETTO IL VALORE A "23" PERCHE DENTRO AL PAR. CLEAR-SCREEN
                |CON L'OPERAZIONE UNLOCK VIENE RISETTATO A ZERO COSICCHÈ 
                |QUANDO TORNA DENTRO AI PAR. DI SCORRIMENTO DI TOTEM SI 
                |TROVA IN UNA SITUAZIONE CORRETTA E PROSEGUE CON LA READ
                |USCENDO CON UN MESSAGGIO DI ERRORE DI TIPO "46"
                move "23" to status-tgruppi
           end-evaluate.

      * <TOTEM:END>
       INPUT-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON INPUT.
       0100-DECL.
           EXIT.
       I-O-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON I-O.
       0200-DECL.
           EXIT.
       OUTPUT-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON OUTPUT.
       0300-DECL.
           EXIT.
       TRANSACTION-ERROR SECTION.
           USE AFTER STANDARD ERROR PROCEDURE ON TRANSACTION.
       0400-DECL.
           EXIT.
       END DECLARATIVES.
      *{TOTEM}END

       MAIN-LOGIC.
      *{TOTEM}ENTRY-BEFPRG
      *    Before-Program
           PERFORM anagr01-Ev-Before-Program
      *{TOTEM}END
           PERFORM INITIALIZE-ROUTINE.
      * run main screen
      *{TOTEM}RUN-MAINSCR
           PERFORM Form1-OPEN-ROUTINE.
      *{TOTEM}END

      *{TOTEM}COPY-PROCEDURE
       EXIT-STOP-ROUTINE.
           PERFORM CLOSE-FILE-RTN
      * <TOTEM:EPT. INIT:tgruppi, INIT:tgruppi, BeforeDestroyResource>
      * <TOTEM:END>
           DESTROY Verdana10-Occidentale
           CALL "w$bitmap" USING WBITMAP-DESTROY, toolbar-bmp
      *    After-Program
           PERFORM anagr01-Ev-After-Program
           EXIT PROGRAM TOTEM-PgmStatus
           STOP RUN.

       INITIALIZE-ROUTINE.
      *    Before Init
      * initialize program status variable
           Initialize TOTEM-PgmStatus.
      * get system information
           ACCEPT SYSTEM-INFORMATION FROM SYSTEM-INFO.
      * get terminal information
           ACCEPT TERMINAL-ABILITIES FROM TERMINAL-INFO.
      * set font
           PERFORM INIT-FONT.
      * load bitmap
           PERFORM INIT-BMP.
      * load resource
           PERFORM INIT-RES.
      * create pop-up menu
           PERFORM INIT-POPUP.
      * open files
           PERFORM OPEN-FILE-RTN.
      *    After Init
           .
    
       INIT-FONT.
      * Verdana10-Occidentale
           INITIALIZE WFONT-DATA Verdana10-Occidentale
           MOVE 10 TO WFONT-SIZE
           MOVE "Verdana" TO WFONT-NAME
           SET WFCHARSET-DONT-CARE TO TRUE
           SET WFONT-BOLD TO FALSE
           SET WFONT-ITALIC TO FALSE
           SET WFONT-UNDERLINE TO FALSE
           SET WFONT-STRIKEOUT TO FALSE
           SET WFONT-FIXED-PITCH TO FALSE
           MOVE 0 TO WFONT-CHAR-SET
           CALL "W$FONT" USING WFONT-GET-FONT, 
                     Verdana10-Occidentale, WFONT-DATA
           .

       INIT-BMP.
      * TOOL-ESCI
           COPY RESOURCE "toolbar.bmp".
           CALL "w$bitmap" USING WBITMAP-LOAD "toolbar.bmp", 
                   GIVING toolbar-bmp.
           .

       INIT-RES.
           .

       INIT-POPUP.
           .

       OPEN-FILE-RTN.
      *    Before Open
           PERFORM OPEN-tgruppi
      *    After Open
           .

       OPEN-tgruppi.
      * <TOTEM:EPT. INIT:tgruppi, FD:tgruppi, BeforeOpen>
      * <TOTEM:END>
           OPEN  I-O tgruppi
           IF STATUS-tgruppi = "35"
              OPEN OUTPUT tgruppi
                IF Valid-STATUS-tgruppi
                   CLOSE tgruppi
                   OPEN I-O tgruppi
                END-IF
           END-IF
           IF NOT Valid-STATUS-tgruppi
              PERFORM  Form1-EXTENDED-FILE-STATUS
              GO TO EXIT-STOP-ROUTINE
           END-IF
      * <TOTEM:EPT. INIT:tgruppi, FD:tgruppi, AfterOpen>
      * <TOTEM:END>
           .

       CLOSE-FILE-RTN.
      *    Before Close
           PERFORM CLOSE-tgruppi
      *    After Close
           .

       CLOSE-tgruppi.
      * <TOTEM:EPT. INIT:tgruppi, FD:tgruppi, BeforeClose>
      * <TOTEM:END>
           CLOSE tgruppi
           .

       DataSet1-tgruppi-INITSTART.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tgruppi-KEY1-Asc
                 MOVE Low-Value TO tgr-chiave
              ELSE
                 MOVE High-Value TO tgr-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-tgruppi-INITEND.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tgruppi-KEY1-Asc
                 MOVE High-Value TO tgr-chiave
              ELSE
                 MOVE Low-Value TO tgr-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-CHANGETO-KEY1.
           MOVE 1 TO DataSet1-KEYIS
           .   

       DataSet1-Change-CurrentKey-Asc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "A" TO DataSet1-tgruppi-KEY1-ORDER
           END-EVALUATE
           .

       DataSet1-Change-CurrentKey-Desc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "D" TO DataSet1-tgruppi-KEY1-ORDER
           END-EVALUATE
           .

      * tgruppi
       DataSet1-tgruppi-START.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tgruppi-KEY1-Asc
                 START tgruppi KEY >= tgr-chiave
              ELSE
                 START tgruppi KEY <= tgr-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-tgruppi-START-NOTGREATER.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tgruppi-KEY1-Asc
                 START tgruppi KEY <= tgr-chiave
              ELSE
                 START tgruppi KEY >= tgr-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-tgruppi-START-GREATER.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tgruppi-KEY1-Asc
                 START tgruppi KEY > tgr-chiave
              ELSE
                 START tgruppi KEY < tgr-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-tgruppi-START-LESS.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tgruppi-KEY1-Asc
                 START tgruppi KEY < tgr-chiave
              ELSE
                 START tgruppi KEY > tgr-chiave
              END-IF
           END-EVALUATE
           .

       DataSet1-tgruppi-Read.
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, BeforeReadRecord>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tgruppi-LOCK
                 READ tgruppi WITH LOCK 
                 KEY tgr-chiave
              ELSE
                 READ tgruppi WITH NO LOCK 
                 KEY tgr-chiave
              END-IF
           END-EVALUATE
           MOVE STATUS-tgruppi TO TOTEM-ERR-STAT 
           MOVE "tgruppi" TO TOTEM-ERR-FILE
           MOVE "READ" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, AfterReadRecord>
      * <TOTEM:END>
           .

       DataSet1-tgruppi-Read-Next.
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, BeforeReadNext>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tgruppi-KEY1-Asc
                 IF DataSet1-tgruppi-LOCK
                    READ tgruppi NEXT WITH LOCK
                 ELSE
                    READ tgruppi NEXT WITH NO LOCK
                 END-IF
              ELSE
                 IF DataSet1-tgruppi-LOCK
                    READ tgruppi PREVIOUS WITH LOCK
                 ELSE
                    READ tgruppi PREVIOUS WITH NO LOCK
                 END-IF
              END-IF
           END-EVALUATE
           MOVE STATUS-tgruppi TO TOTEM-ERR-STAT
           MOVE "tgruppi" TO TOTEM-ERR-FILE
           MOVE "READ NEXT" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, AfterReadNext>
      * <TOTEM:END>
           .

       DataSet1-tgruppi-Read-Prev.
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, BeforeRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, BeforeReadPrev>
      * <TOTEM:END>
           EVALUATE DataSet1-KEYIS
           WHEN 1
              IF DataSet1-tgruppi-KEY1-Asc
                 IF DataSet1-tgruppi-LOCK
                    READ tgruppi PREVIOUS WITH LOCK
                 ELSE
                    READ tgruppi PREVIOUS WITH NO LOCK
                 END-IF
              ELSE
                 IF DataSet1-tgruppi-LOCK
                    READ tgruppi NEXT WITH LOCK
                 ELSE
                    READ tgruppi NEXT WITH NO LOCK
                 END-IF
              END-IF
           END-EVALUATE
           MOVE STATUS-tgruppi TO TOTEM-ERR-STAT
           MOVE "tgruppi" TO TOTEM-ERR-FILE
           MOVE "READ PREVIOUS" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, AfterRead>
      * <TOTEM:END>
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, AfterReadPrev>
      * <TOTEM:END>
           .

       DataSet1-tgruppi-Rec-Write.
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, BeforeWrite>
      * <TOTEM:END>
           WRITE tgr-rec OF tgruppi.
           MOVE STATUS-tgruppi TO TOTEM-ERR-STAT
           MOVE "tgruppi" TO TOTEM-ERR-FILE
           MOVE "WRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, AfterWrite>
      * <TOTEM:END>
           .

       DataSet1-tgruppi-Rec-Rewrite.
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, BeforeRewrite>
      * <TOTEM:END>
           REWRITE tgr-rec OF tgruppi.
           MOVE STATUS-tgruppi TO TOTEM-ERR-STAT
           MOVE "tgruppi" TO TOTEM-ERR-FILE
           MOVE "REWRITE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, AfterRewrite>
      * <TOTEM:END>
           .

       DataSet1-tgruppi-Rec-Delete.
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, BeforeDelete>
      * <TOTEM:END>
           DELETE tgruppi.
           MOVE STATUS-tgruppi TO TOTEM-ERR-STAT
           MOVE "tgruppi" TO TOTEM-ERR-FILE
           MOVE "DELETE" TO TOTEM-ERR-MODE
      * <TOTEM:EPT. FD:DataSet1, FD:tgruppi, AfterDelete>
      * <TOTEM:END>
           .

       DataSet1-INIT-RECORD.
           INITIALIZE tgr-rec OF tgruppi
           .


      * FD's Initialize Paragraph
       DataSet1-tgruppi-INITREC.
           INITIALIZE tgr-rec OF tgruppi
               REPLACING NUMERIC       DATA BY ZEROS
                         ALPHANUMERIC  DATA BY SPACES
                         ALPHABETIC    DATA BY SPACES
           .

      *
       DataSet1-DISPATCH-BUFTOFLD.
           EVALUATE TOTEM-Form-Index ALSO TOTEM-Frame-Index
              WHEN 1 ALSO 0
                  PERFORM Form1-Buf-To-Fld
           END-EVALUATE
           .

       Form1-DISPLAY-STATUS-MSG.
            MODIFY Form1-St-1-Handle PANEL-INDEX = 1
                PANEL-TEXT = TOTEM-HINT-TEXT
           .

       Form1-CLEAR-STATUS-MSG.
           MOVE SPACES TO TOTEM-MSG-1, TOTEM-MSG-2, TOTEM-MSG-3, 
           TOTEM-MSG-TEXT
           PERFORM Form1-DISPLAY-STATUS-MSG
           .

       Form1-Open-Routine.
           PERFORM Form1-Scrn
           PERFORM Form1-Proc
           .

       Form1-Scrn.
           PERFORM Form1-Create-Win
           PERFORM Form1-Init-Value
           PERFORM Form1-Init-Data
      * Tab keystrok settings
      * Tool Bar
           DISPLAY Form1-Tb-1
           PERFORM Form1-DISPLAY
           .

       Form1-Create-Win.
           Display Independent GRAPHICAL WINDOW
              LINES 21,81,
              SIZE 110,00,
              COLOR 65793,
              CONTROL FONT Verdana10-Occidentale,
              CONTROLS-UNCROPPED,
              LABEL-OFFSET 23,
              LINK TO THREAD,
              MODELESS,
              NO SCROLL,
              TITLE-BAR,
              TITLE TITOLO,
              AUTO-MINIMIZE,
              WITH SYSTEM MENU,
              USER-GRAY,
              USER-WHITE,
              No WRAP,
              EVENT PROCEDURE Form1-Event-Proc,
              HANDLE IS Form1-Handle,
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterCreateWin>
      * <TOTEM:END>


      * Tool Bar    
           DISPLAY TOOL-BAR 
              LINES 2,69,   
              HANDLE IN Form1-Tb-1-Handle
           DISPLAY Form1-Tb-1 UPON Form1-Tb-1-Handle

      * Status-bar
           DISPLAY STATUS-BAR
              GRIP,
              PANEL-WIDTHS (62, 23, 999),
              PANEL-STYLE  (1, 1, 1),
              PANEL-TEXT   (SPACE, SPACE, SPACE),
              HANDLE IS Form1-St-1-Handle
           DISPLAY Form1 UPON Form1-Handle
      * DISPLAY-COLUMNS settings
           .

       Form1-PROC.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeAccept>
      *<<** customized_default, sp-g, form1-custom1-2 **>>           
           perform ABILITA-TOOLBAR.
           perform ABILITAZIONI.

           set StatusVisua to true.
           perform STATUS-BAR-MSG.

           .
      * <TOTEM:END>
           PERFORM UNTIL Exit-Pushed
              ACCEPT Form1
                 ON EXCEPTION
                    PERFORM Form1-Evaluate-Func
                 MOVE 1 TO TOTEM-Form-Index
              END-ACCEPT
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterEndAccept>
      * <TOTEM:END>
           END-PERFORM
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeDestroyWindow>
      * <TOTEM:END>
           DESTROY Form1-Handle
           INITIALIZE Key-Status
           .

       Form1-Evaluate-Func.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterAccept>
           evaluate key-status
           when 5 |MODIFICA
                inquire tool-modifica, enabled in e-modifica
                if e-modifica = 1
                   if mod = 0 move 1 to mod
                   else       move 0 to mod
                   end-if
                   modify tool-modifica, value = mod
                   perform MODIFICA
                end-if
           end-evaluate.

           .
      * <TOTEM:END>
           EVALUATE TRUE
              WHEN Exit-Pushed
                 PERFORM Form1-Exit
              WHEN Event-Occurred
                 IF Event-Type = Cmd-Close
                    PERFORM Form1-Exit
                 END-IF
              WHEN Key-Status = 2
                 PERFORM NUOVO-LinkTo
              WHEN Key-Status = 4
                 PERFORM CANCELLA-LinkTo
              WHEN Key-Status = 3
                 PERFORM TOOL-SALVA-LinkTo
              WHEN Key-Status = 6
                 PERFORM ANTEPRIMA-LinkTo
              WHEN Key-Status = 150
                 PERFORM TOOL-MODIFICA-LinkTo
              WHEN Key-Status = 7
                 PERFORM STAMPA-LinkTo
              WHEN Key-Status = 8
                 PERFORM TOOL-CERCA-LinkTo
              WHEN Key-Status = 9
                 PERFORM TOOL-SELEZIONA-LinkTo
              WHEN Key-Status = 1002
                 PERFORM TOOL-PRIMO
              WHEN Key-Status = 67
                 PERFORM TOOL-PRECEDENTE
              WHEN Key-Status = 68
                 PERFORM TOOL-SUCCESSIVO
              WHEN Key-Status = 1006
                 PERFORM TOOL-ULTIMO
           END-EVALUATE
      * avoid changing focus
           MOVE 4 TO Accept-Control
           .

       Form1-CLEAR.
           PERFORM Form1-INIT-VALUE
           PERFORM Form1-DISPLAY
           .

       Form1-DISPLAY.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeDisplay>
      * <TOTEM:END>
           DISPLAY Form1-Tb-1
           DISPLAY Form1 UPON Form1-Handle
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterDisplay>
           SET LK-BL-SCRITTURA     TO TRUE.
           MOVE COMO-PROG-ID       TO LK-BL-PROG-ID.
           MOVE FORM1-HANDLE       TO LK-HND-WIN.
           CALL "BLOCKPGM"  USING LK-BLOCKPGM.
           CANCEL "BLOCKPGM".

           .
      * <TOTEM:END>
           .

       Form1-Exit.
      * for main screen
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeExit>
           perform SALV-MOD.

           if errori
              move 26 to key-status
              exit paragraph
           end-if.

           .
      * <TOTEM:END>
           MOVE 27 TO Key-Status
           .

       Form1-Init-Data.
           MOVE 1 TO TOTEM-Form-Index
           MOVE 0 TO TOTEM-Frame-Index
           .

       Form1-DataSet1-CHANGETO-KEY1.
           MOVE 1 TO DataSet1-KEYIS
           PERFORM Form1-DataSet1-Update-Key
           .

       Form1-DataSet1-Change-CurrentKey-Asc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "A" TO DataSet1-tgruppi-KEY1-ORDER
           END-EVALUATE
           PERFORM Form1-DataSet1-Update-Key
           .

       Form1-DataSet1-Change-CurrentKey-Desc.
           EVALUATE DataSet1-KEYIS
           WHEN 1
              MOVE "D" TO DataSet1-tgruppi-KEY1-ORDER
           END-EVALUATE
           PERFORM Form1-DataSet1-Update-Key
           .

       Form1-DataSet1-Update-Key.
           MOVE tgr-rec OF tgruppi TO
                     Form1-MULKEY-TMPBUF
           PERFORM Form1-CLEAR
           PERFORM Form1-INIT-DATA
           MOVE Form1-MULKEY-TMPBUF TO
                     tgr-rec OF tgruppi
           PERFORM DataSet1-tgruppi-Read
           PERFORM Form1-DUPLICATE-MOVEKEY
           PERFORM Form1-DUMMY-CURR
           PERFORM Form1-IUD-Display
           .

       Form1-DUPLICATE-MOVEKEY.
           .

       Form1-First.
           PERFORM Form1-DUMMY-FIRST
           PERFORM DataSet1-tgruppi-INITSTART
           PERFORM DataSet1-tgruppi-START
           IF NOT Valid-STATUS-tgruppi
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeFirst>
      * <TOTEM:END>
           PERFORM DataSet1-tgruppi-Read-Next
           IF NOT Valid-STATUS-tgruppi
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterFirst>
      * <TOTEM:END>
           PERFORM Form1-DUPLICATE-MOVEKEY.
           PERFORM Form1-IUD-Display
           .

       Form1-Previous.
              PERFORM Form1-Buf-To-Fld
              PERFORM DataSet1-tgruppi-START-LESS
           IF NOT Valid-STATUS-tgruppi
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforePrevious>
      * <TOTEM:END>
           PERFORM DataSet1-tgruppi-Read-Prev
           IF NOT Valid-STATUS-tgruppi
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterPrevious>
      * <TOTEM:END>
           PERFORM Form1-DUPLICATE-MOVEKEY
           PERFORM Form1-DUMMY-PREVIOUS
           PERFORM Form1-IUD-Display
           .

       Form1-Next.
              PERFORM Form1-Buf-To-Fld
              PERFORM DataSet1-tgruppi-START-GREATER
           IF NOT Valid-STATUS-tgruppi
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeNext>
      * <TOTEM:END>
           PERFORM DataSet1-tgruppi-Read-Next
           IF NOT Valid-STATUS-tgruppi
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterNext>
      * <TOTEM:END>
           PERFORM Form1-DUPLICATE-MOVEKEY
           PERFORM Form1-DUMMY-NEXT
           PERFORM Form1-IUD-Display
           .
      
       Form1-Last.
           PERFORM Form1-DUMMY-LAST
           PERFORM DataSet1-tgruppi-INITEND
           PERFORM DataSet1-tgruppi-START-NOTGREATER
           IF NOT Valid-STATUS-tgruppi
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeLast>
      * <TOTEM:END>
           PERFORM DataSet1-tgruppi-Read-Prev
           IF NOT Valid-STATUS-tgruppi
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterLast>
      * <TOTEM:END>
           PERFORM Form1-DUPLICATE-MOVEKEY.
           PERFORM Form1-IUD-Display
           .

       Form1-Curr.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeCurrent>
      * <TOTEM:END>
           PERFORM Form1-Buf-To-Fld
           PERFORM DataSet1-tgruppi-Read
           PERFORM Form1-DUPLICATE-MOVEKEY
           PERFORM Form1-DUMMY-CURR
           PERFORM Form1-IUD-Display
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterCurrent>
      * <TOTEM:END>
           .

       Form1-IUD-Display.
           IF Valid-STATUS-tgruppi
              PERFORM Form1-ALLGRID-RESET
              PERFORM Form1-Fld-To-Buf
              PERFORM Form1-NAVI-FOR-MASTERGRID
              PERFORM Form1-DISPLAY
           ELSE
              IF Form1-FLAG-REFRESH
                 CONTINUE
              ELSE
                 PERFORM Form1-Extended-File-Status
              END-IF
           END-IF
           .

       Form1-Add.
           PERFORM Form1-Buf-To-Fld
           PERFORM Form1-VALIDATION-ROUTINE
           IF NOT TOTEM-CHECK-OK
               EXIT PARAGRAPH
           END-IF
           PERFORM Form1-DUMMY-ADD
           PERFORM DataSet1-tgruppi-INITREC
           PERFORM Form1-Buf-To-Fld
           MOVE SPACES TO TOTEM-TRANSACTION-FLAG
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeAdd>
      * <TOTEM:END>
      * write
           PERFORM DataSet1-tgruppi-Rec-Write
           IF Valid-STATUS-tgruppi
              PERFORM Form1-RESUMMARY-INS
              PERFORM Form1-DUMMY-UPDATE-INIT
              MOVE "301" TO TOTEM-MSG-ID
              PERFORM Form1-IUD-Display
           END-IF
           PERFORM Form1-ERR-CHECKING
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterAdd>
      * <TOTEM:END>
           .
     
       Form1-Update.
           PERFORM Form1-Buf-To-Fld
           PERFORM DataSet1-tgruppi-START              
           IF NOT Valid-STATUS-tgruppi
              PERFORM Form1-Extended-File-Status
              EXIT PARAGRAPH
           END-IF
           PERFORM DataSet1-tgruppi-Read
           PERFORM Form1-Buf-To-Fld
           PERFORM Form1-VALIDATION-ROUTINE
           IF NOT TOTEM-CHECK-OK
               EXIT PARAGRAPH
           END-IF
           PERFORM Form1-DUMMY-UPDATE
           PERFORM Form1-Buf-To-Fld
           MOVE SPACES TO TOTEM-TRANSACTION-FLAG
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeUpdate>
      * <TOTEM:END>
      * write
           PERFORM DataSet1-tgruppi-Rec-Rewrite
           IF Valid-STATUS-tgruppi
              PERFORM Form1-RESUMMARY-DEL
              PERFORM Form1-DUMMY-UPDATE-INIT
              MOVE "302" TO TOTEM-MSG-ID
              PERFORM Form1-IUD-Display
           END-IF
           PERFORM Form1-ERR-CHECKING
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterUpdate>
      * <TOTEM:END>
           .

       Form1-Delete.
           MOVE "203" TO TOTEM-MSG-ID
           PERFORM MESSAGE-BOX-DISPLAY
           IF TOTEM-MSG-RETURN-VALUE NOT = 1
              INITIALIZE TOTEM-MSG-TEXT
              EXIT PARAGRAPH 
           END-IF
           MOVE SPACES TO TOTEM-TRANSACTION-FLAG
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeDelete>
      * <TOTEM:END>
           PERFORM Form1-DUMMY-DELETE
      * delete
           PERFORM Form1-Buf-To-Fld
           PERFORM DataSet1-tgruppi-Rec-Delete
           IF Valid-STATUS-tgruppi
              PERFORM Form1-CLEAR
              PERFORM Form1-DUMMY-DELETE-INIT
              MOVE "303" TO TOTEM-MSG-ID
              MOVE "00" to STATUS-tgruppi
           END-IF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterDelete>
      * <TOTEM:END>
           PERFORM Form1-ERR-CHECKING
           .

       Form1-NAVI-FOR-MASTERGRID.
           .

       Form1-ERR-CHECKING.
           IF Valid-STATUS-tgruppi
              PERFORM Form1-SHOW-MSG-ROUTINE
           ELSE
              PERFORM Form1-Extended-File-Status
           END-IF
           .

       Form1-RESUMMARY-INS.
           .

       Form1-RESUMMARY-DEL.
           .


       Form1-DUMMY-FIRST.
           .

       Form1-DUMMY-PREVIOUS.
           .

       Form1-DUMMY-NEXT.
           .

       Form1-DUMMY-LAST.
           .

       Form1-DUMMY-CURR.
           .

       Form1-DUMMY-ADD.
           .

       Form1-DUMMY-UPDATE.
           .

       Form1-DUMMY-UPDATE-INIT.
           .

       Form1-DUMMY-DELETE.
           .

       Form1-DUMMY-DELETE-INIT.
           .

       Form1-Init-Value.
           MOVE TITOLO TO TOTEM-MSG-TITLE
           INITIALIZE Form1-BUF
      * FORM : Form1
           PERFORM DataSet1-INIT-RECORD
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, SetDefault>
      * <TOTEM:END>
           PERFORM Form1-FLD-TO-BUF
           .


       Form1-ALLGRID-RESET.
           .

      * for Form's Validation
       Form1-VALIDATION-ROUTINE.
           SET TOTEM-CHECK-OK TO TRUE
      * ef-codice's Validation
           SET TOTEM-CHECK-OK TO FALSE
           PERFORM ef-codice-VALIDATION
           IF NOT TOTEM-CHECK-OK
               MOVE 4 TO ACCEPT-CONTROL
               MOVE 5001 TO CONTROL-ID
               EXIT PARAGRAPH
           END-IF
      * ef-descr's Validation
           SET TOTEM-CHECK-OK TO FALSE
           PERFORM ef-descr-VALIDATION
           IF NOT TOTEM-CHECK-OK
               MOVE 4 TO ACCEPT-CONTROL
               MOVE 5002 TO CONTROL-ID
               EXIT PARAGRAPH
           END-IF
      * ef-email's Validation
           SET TOTEM-CHECK-OK TO FALSE
           PERFORM ef-email-VALIDATION
           IF NOT TOTEM-CHECK-OK
               MOVE 4 TO ACCEPT-CONTROL
               MOVE 5003 TO CONTROL-ID
               EXIT PARAGRAPH
           END-IF
           .

       ef-codice-BEFORE-VALIDATION.
      * <TOTEM:EPT. FORM:Form1, Data.Entry-Field:ef-codice, BeforeValidation>
      * <TOTEM:END>
           .

       ef-codice-AFTER-VALIDATION.
      * <TOTEM:EPT. FORM:Form1, Data.Entry-Field:ef-codice, AfterValidation>
      * <TOTEM:END>
           .

      * ef-codice's Validation
       ef-codice-VALIDATION.
           PERFORM ef-codice-BEFORE-VALIDATION
           SET TOTEM-CHECK-OK TO TRUE
           PERFORM ef-codice-AFTER-VALIDATION
           .

       ef-descr-BEFORE-VALIDATION.
      * <TOTEM:EPT. FORM:Form1, Data.Entry-Field:ef-descr, BeforeValidation>
      * <TOTEM:END>
           .

       ef-descr-AFTER-VALIDATION.
      * <TOTEM:EPT. FORM:Form1, Data.Entry-Field:ef-descr, AfterValidation>
      * <TOTEM:END>
           .

      * ef-descr's Validation
       ef-descr-VALIDATION.
           PERFORM ef-descr-BEFORE-VALIDATION
           SET TOTEM-CHECK-OK TO TRUE
           PERFORM ef-descr-AFTER-VALIDATION
           .

       ef-email-BEFORE-VALIDATION.
      * <TOTEM:EPT. FORM:Form1, Data.Entry-Field:ef-email, BeforeValidation>
      * <TOTEM:END>
           .

       ef-email-AFTER-VALIDATION.
      * <TOTEM:EPT. FORM:Form1, Data.Entry-Field:ef-email, AfterValidation>
      * <TOTEM:END>
           .

      * ef-email's Validation
       ef-email-VALIDATION.
           PERFORM ef-email-BEFORE-VALIDATION
           SET TOTEM-CHECK-OK TO TRUE
           PERFORM ef-email-AFTER-VALIDATION
           .


       Form1-Buf-To-Fld.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeBufToFld>
      * <TOTEM:END>
      * DB_Entry-Field : ef-codice
           MOVE ef-codice-BUF TO tgr-codice
      * DB_Entry-Field : ef-descr
           MOVE ef-descr-BUF TO tgr-descrizione
      * DB_Entry-Field : ef-email
           MOVE ef-email-BUF TO tgr-email
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterBufToFld>
      * <TOTEM:END>
           .

       Form1-Fld-To-Buf.
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, BeforeFldToBuf>
      * <TOTEM:END>
      * DB_Entry-Field : ef-codice
           MOVE tgr-codice TO ef-codice-BUF
      * DB_Entry-Field : ef-descr
           MOVE tgr-descrizione TO ef-descr-BUF
      * DB_Entry-Field : ef-email
           MOVE tgr-email TO ef-email-BUF
      * <TOTEM:EPT. FORM:Form1, FORM:Form1, AfterFldToBuf>
           perform VALORIZZA-OLD.
           perform ABILITAZIONI.

           .
      * <TOTEM:END>
           .

       Form1-CONTROLLO-OLD.
           set SiSalvato to true.
           if mod = 0 exit paragraph end-if.
           perform Form1-BUF-TO-FLD.
           move 0 to scelta.
           if tgr-descrizione not = old-tgr-descrizione
              and SiSalvato
              set NoSalvato to true
              |78-ID-ef-descr è l'ID del campo ef-descr
              move 78-ID-ef-descr to store-id 
           end-if

           if tgr-email not = old-tgr-email
              and SiSalvato
              set NoSalvato to true
              |78-ID-ef-email è l'ID del campo ef-email
              move 78-ID-ef-email to store-id 
           end-if

           .
       Form1-EXTENDED-FILE-STATUS.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
           MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           PERFORM Form1-SHOW-MSG-ROUTINE
           .

       Form1-SHOW-MSG-ROUTINE.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM Form1-DISPLAY-MESSAGE
           .

       Form1-DISPLAY-MESSAGE.
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

       Form1-Save-Status.
           MOVE DataSet1-tgruppi-KEY1-ORDER TO TMP-Form1-KEY1-ORDER
           MOVE DataSet1-KEYIS TO TMP-Form1-KEYIS
           MOVE tgr-rec OF tgruppi TO 
              TMP-Form1-tgruppi-RESTOREBUF
           .             

       Form1-Restore-Status.
           MOVE TMP-Form1-KEY1-ORDER TO DataSet1-tgruppi-KEY1-ORDER
           MOVE TMP-Form1-KEYIS TO DataSet1-KEYIS
           MOVE TMP-Form1-tgruppi-RESTOREBUF TO
              tgr-rec OF tgruppi
           PERFORM DataSet1-tgruppi-START
           IF Valid-STATUS-tgruppi
              PERFORM DataSet1-tgruppi-Read-Next
           ELSE
              PERFORM DataSet1-tgruppi-INITREC
           END-IF
           PERFORM UNTIL NOT Valid-STATUS-tgruppi OR
              (Valid-STATUS-tgruppi AND
                 tgr-rec OF tgruppi = 
                   TMP-Form1-tgruppi-RESTOREBUF)
              PERFORM DataSet1-tgruppi-Read-Next
           END-PERFORM
           .


      * Paragrafo per la struttura del codice in AFTER sulla screen Form1
      ***---
       Form1-AFTER-SCREEN.

      * Generazione risettaggio keyboard "." ---> "."

      * Generazione stringa perform CONTROLLO
           evaluate control-id
           |78-ID-ef-codice è l'ID del campo ef-codice
           when 78-ID-ef-codice
                perform CONTROLLO
           |99999 è un valore fittizio, che non sarà MAI usato,
           |ma mi serve per non riscontrare errori di compilazione
           |in caso non avessi generato nulla nella AFTER CONTROLLO della screen
           when 99999 continue
           when other continue
           end-evaluate.



       Form1-BeforeProcedure.
           EVALUATE Control-Id
           WHEN 5001 MOVE "Digitare il codice GDO" to TOTEM-HINT-TEXT
           WHEN 5002 MOVE "Digitare la descrizione" to TOTEM-HINT-TEXT
           WHEN 5003 MOVE "Digitare uno o più indirizzi email" to 
           TOTEM-HINT-TEXT
           WHEN OTHER MOVE SPACES TO TOTEM-HINT-TEXT
           END-EVALUATE
           EVALUATE Control-Id
           When 5001 PERFORM ef-codice-BeforeProcedure
           When 5002 PERFORM ef-des-BeforeProcedure
           When 5003 PERFORM ef-des-BeforeProcedure
           END-EVALUATE
           PERFORM Form1-DISPLAY-STATUS-MSG
           .

       Form1-AfterProcedure.
           EVALUATE Control-Id
           When 5001 PERFORM ef-codice-AfterProcedure
           When 5002 PERFORM ef-des-AfterProcedure
           When 5003 PERFORM ef-des-AfterProcedure
           END-EVALUATE
           perform Form1-AFTER-SCREEN
           .

       Form1-Event-Proc.
           .

      * USER DEFINE PARAGRAPH
       ABILITAZIONI.
      * <TOTEM:PARA. ABILITAZIONI>
           if mod = 1
              move BitmapDeleteEnabled to BitmapNumDelete
              move BitmapSaveEnabled   to BitmapNumSave
              move 1 to e-salva e-cancella           
           else
              move BitmapDeleteDisabled to BitmapNumDelete
              move BitmapSaveDisabled   to BitmapNumSave
              move ZERO to e-salva e-cancella
           end-if.            

      * ISACCO (CORREZIONE SU LIVELLO ABILITAZIONE 2) - 07/11/2003
      * (CANCELLAZIONE NON PERMESSA)
           if livello-abil = 2 
              move ZERO to e-cancella
              move BitmapDeleteDisabled to BitmapNumDelete
           end-if.
      * FINE

           modify tool-cancella, enabled = e-cancella.
           modify tool-salva,    enabled = e-salva.
       
      * ISACCO (SERVE SEMPRE PER LA MODIFICA PRCEDENTE E PER RIPRISTINARE
      * LE BITMAP DISABILITATE. - 10/11/2003
      *     perform FORM1-DISPLAY.
           display tool-nuovo, tool-salva, tool-cancella, tool-modifica.
      * FINE 
           .
      * <TOTEM:END>

       ANTEPRIMA.
      * <TOTEM:PARA. ANTEPRIMA>
           SET ANTEPRIMA     TO TRUE 
           .
      * <TOTEM:END>

       CANCELLA.
      * <TOTEM:PARA. CANCELLA>
           if mod = 0 exit paragraph  end-if.
      *    
           inquire ef-codice, value in tgr-codice of tgruppi .
           display message MSG-Cancellare-il-record-corrente
                     title titolo
                      type mb-yes-no 
                   default mb-no
                    giving scelta

           if scelta = mb-yes
              delete tgruppi record invalid continue end-delete
   
              move 0 to mod
              move 1 to mod-k
              perform FORM1-CLEAR

              set vecchio to true
              perform CANCELLA-COLORE
              perform INIT-OLD-REC
                            
              display message  MSG-Cancellazione-avvenuta-con-successo
                      title titolo                         

              unlock tgruppi all records

              perform PRIMO
              move 1 to CONTROL-ID     
              move 4 to ACCEPT-CONTROL 
              set Statusvisua to true
              perform STATUS-BAR-MSG
              modify TOOL-MODIFICA value = mod
           end-if 
           .
      * <TOTEM:END>

       CLEAR-SCREEN.
      * <TOTEM:PARA. CLEAR-SCREEN>
           move tgr-chiave  of tgruppi to old-tgr-chiave.

           initialize tgr-dati  of tgruppi 
                      replacing numeric data by zeroes
                           alphanumeric data by spaces.

           perform FORM1-FLD-TO-BUF. 

           perform INIT-OLD-REC.

           display form1.     
  
           unlock tgruppi all records 
           .
      * <TOTEM:END>

       CHECK-INSERIMENTO.
      * <TOTEM:PARA. CHECK-INSERIMENTO>
      * MODIFICA LA STATUS-BAR
      * CONTROLLO SE DA INSERIMENTO SCORRO. ALLORA DEVO SEGNALARE CHE
      * SONO TORNATO IN MODIFICA.
           inquire tool-modifica, value in mod.

           evaluate mod
           when 1
                set StatusModifica to true
           when ZERO
                set StatusVisua to true   
           end-evaluate.
      
           perform STATUS-BAR-MSG 
           .
      * <TOTEM:END>

       CONTROLLO.
      * <TOTEM:PARA. CONTROLLO>
           set tutto-ok to true.

      * Paragrafo per la struttura dei controlli sulla screen Form1
           evaluate control-id
           |78-ID-ef-codice è l'ID del control ef-codice
           when 78-ID-ef-codice
                inquire ef-codice, value in tgr-codice of tgruppi
                if tgr-codice  of tgruppi = spaces
                   set errori to true
                   display message "Inserimento codice mancante"
                             title tit-err
                              icon 2
                else
                   read tgruppi no lock
                        invalid 
                        if vecchio
                           display message MSG-record-inesistente
                                     title tit-err
                                      icon 2
                           perform CLEAR-SCREEN
                           set errori to true
                           move 78-ID-ef-codice to control-id
                        end-if
                    not invalid
                        if old-tgr-chiave not = tgr-chiave of tgruppi
                           perform CURRENT-RECORD 
                           set errori to true  
                           move 78-ID-ef-codice to control-id
                        end-if
                   end-read
                end-if

           when 78-ID-ef-descr
                inquire ef-descr, value in tgr-descrizione
                if tgr-descrizione = spaces
                   set errori to true
                   display message "Descrizione obbligatoria"
                             title tit-err
                              icon 2
                end-if

           when 78-ID-ef-email
                inquire ef-email, value in tgr-email
                if tgr-email = spaces
                   set errori to true
                   display message "Email obbligatorie"
                             title tit-err
                              icon 2
                end-if

           end-evaluate.

           if errori
              move control-id to store-id
              perform CANCELLA-COLORE
              move 4        to ACCEPT-CONTROL
           end-if 
           .
      * <TOTEM:END>

       CURRENT-RECORD.
      * <TOTEM:PARA. CURRENT-RECORD>
           inquire ef-codice, value in tgr-codice of tgruppi.
           set tutto-ok  to true.
           set ReadSecca to true.
           if nuovo move 0 to mod end-if.

           if mod = 1
              read tgruppi lock invalid 
                 set errori to true 
              end-read
           else
              read tgruppi no lock invalid 
                 set errori to true 
              end-read
           end-if.                    
           set ReadSecca to false.

           if RecLocked
              set RecLocked to false
           else
              if tutto-ok    
                 if nuovo
                    move 0 to mod
                    move 1 to mod-k
                    move 1 to CONTROL-ID
                    move 4 to ACCEPT-CONTROL
                 end-if   
                 perform FORM1-IUD-DISPLAY
                 set vecchio to true
                 if mod = 1
                    set StatusModifica to true
                 else                         
                    set StatusVisua    to true
                 end-if
                 perform STATUS-BAR-MSG
              else
                 move 0 to mod
                 move 1 to mod-k
                 if vecchio
                    perform CLEAR-SCREEN
                    if YesMessage
                       move 78-ID-ef-codice to CONTROL-ID
                       move 4               to ACCEPT-CONTROL
                       display message MSG-Record-inesistente
                                 title tit-err
                                  icon mb-warning-icon
                    end-if
                 end-if
              end-if
           end-if 
           .
      * <TOTEM:END>

       INIT-OLD-REC.
      * <TOTEM:PARA. INIT-OLD-REC>
           initialize old-tgr-rec  replacing numeric data by zeroes
                                        alphanumeric data by spaces 
           .
      * <TOTEM:END>

       MODIFICA.
      * <TOTEM:PARA. MODIFICA>
           move 5 to key-status.
           inquire tool-modifica, value in mod.
           set tutto-ok to true.

           if nuovo
              move 1 to mod                  
              modify tool-modifica, value mod
           else
      *  SE L'UTENTE E' ABILITATO PUO' MODIFICARE UN RECORD
              if mod = 1
                 set YesMessage to true
                 perform CURRENT-RECORD
                 if tutto-ok
                    move 0 to mod-k
                    move 1 to mod
                    set StatusModifica to true
                    perform STATUS-BAR-MSG
                 end-if
              else
                 move 1 to mod
                 perform SALV-MOD            
                 move 0 to mod
                 move 1 to mod-k
                 if errori
                    move 1 to mod
                    move 0 to mod-k
                 else
                    move 78-ID-ef-codice to CONTROL-ID
                    set  NoMessage       to true
                    perform CURRENT-RECORD
                    set StatusVisua to true
                    perform STATUS-BAR-MSG 
                    unlock tgruppi all records

                 end-if
              end-if
                               
              display form1
              modify tool-modifica,  value mod
              perform CANCELLA-COLORE
              move 4    to ACCEPT-CONTROL
              move ZERO to StatusHelp
              perform STATUS-HELP
           end-if 
           .
      * <TOTEM:END>

       NUOVO.
      * <TOTEM:PARA. NUOVO>
           perform SALV-MOD.

           if tutto-ok 
      *****        |SPECIFICO PER I PGM. AVENTI TAB-CONTROL
      *****        move 1 to Screen1-Ta-1-TAB-VALUE
      *****        perform SCREEN1-TA-1-TABCHANGE
              |******          
              move 78-ID-ef-codice to CONTROL-ID
              move 4               to ACCEPT-CONTROL 
              move 1 to mod mod-k
              modify tool-modifica,  value = mod
              perform CANCELLA-COLORE

              move 1 to mod, mod-k

              perform FORM1-CLEAR

              Perform VALORIZZA-NUOVO                                   
                                                
              perform INIT-OLD-REC

      *        perform DISPLAY-SCREEN
              display form1

      * IL FLAG SICCOME E' ANCORA SETTATO A VECCHIO DALLA PRECEDENTE
      * OPERAZIONE, VIENE RISETTATO A NUOVO
      * (STANDARD NORMALE)
              set nuovo to true
              set StatusIns to true
              perform STATUS-BAR-MSG  
              unlock tgruppi all records
           end-if 
           .
      * <TOTEM:END>

       PARAGRAFO-COPY.
      * <TOTEM:PARA. PARAGRAFO-COPY>
           copy "abilita-toolbar.cpy".
           copy "color-custom.cpy".
           copy "status.cpy"  
           .
      * <TOTEM:END>

       PRECEDENTE.
      * <TOTEM:PARA. PRECEDENTE>
           perform SALV-MOD.           
           if tutto-ok
              perform CHECK-INSERIMENTO
              unlock tgruppi all records

              if mod = 1
                 move ZERO to mod-k
                 set dataset1-tgruppi-lock to true
              else              
                 move 1    to mod-k     
                 initialize dataset1-tgruppi-lock-flag
              end-if

              perform CANCELLA-COLORE
              perform FORM1-PREVIOUS

              if RecLocked
                 set RecLocked to false             
                 initialize dataset1-tgruppi-lock-flag
                 move 1 to mod-k
                 perform FORM1-PREVIOUS
              end-if
           end-if 
           .
      * <TOTEM:END>

       PRIMO.
      * <TOTEM:PARA. PRIMO>
           perform SALV-MOD.           
           if tutto-ok     
              perform CHECK-INSERIMENTO
              unlock tgruppi  all records

              if mod = 1
                 move ZERO to mod-k
                 set dataset1-tgruppi-lock to true
              else              
                 move 1 to mod-k     
                 initialize dataset1-tgruppi-lock-flag
              end-if

              perform CANCELLA-COLORE
              perform FORM1-FIRST

              if RecLocked
                 set RecLocked to false             
                 initialize dataset1-tgruppi-lock-flag
                 move 1 to mod-k
                 perform FORM1-FIRST
              end-if
           end-if 
           .
      * <TOTEM:END>

       SALVA.
      * <TOTEM:PARA. SALVA>
           if mod = 0 exit paragraph end-if.

           set tutto-ok to true.
                                 
           move control-id to mem-id.
           perform  varying CONTROL-ID from 78-ID-ef-codice by 1
                      until CONTROL-ID > 78-ID-ef-email
              perform CONTROLLO
              if errori exit perform end-if
           end-perform.

           if errori
              perform CANCELLA-COLORE
              perform ABILITAZIONI
              move store-id to control-id
              move 4 to ACCEPT-CONTROL
           else    
              perform FORM1-BUF-TO-FLD

              perform CANCELLA-COLORE
                                                   
              accept como-data from century-date
              accept como-ora  from time
              if nuovo
                 move como-data to tgr-data-creazione   of tgruppi 
                 move como-ora  to tgr-ora-creazione    of tgruppi 
                 move user-codi to tgr-utente-creazione of tgruppi 
              else
                 move como-data to tgr-data-modifica   of tgruppi 
                 move como-ora  to tgr-ora-modifica    of tgruppi 
                 move user-codi to tgr-utente-modifica of tgruppi 
              end-if

              write tgr-rec of tgruppi invalid 
                    rewrite tgr-rec of tgruppi 
              end-write

              set vecchio to true       
              perform TORNA-IN-VISUA
           end-if.   
                 
           display form1 
           .
      * <TOTEM:END>

       SALV-MOD.
      * <TOTEM:PARA. SALV-MOD>
           set tutto-ok to true.
           perform FORM1-CONTROLLO-OLD.

           if NoSalvato
              display message box MSG-Salvare-le-modifiche
                            title titolo
                            type mb-yes-no-cancel 
                            giving scelta       
       
              evaluate scelta
              when mb-yes 
                   perform SALVA
              when mb-no  
                   continue
              when other
                   modify control-handle, color = colore-or
                   set errori to true
                   move store-id   to CONTROL-ID    
                   move 4          to ACCEPT-CONTROL
              end-evaluate
           end-if 
           .
      * <TOTEM:END>

       SELEZIONA.
      * <TOTEM:PARA. SELEZIONA>
           inquire ef-codice, value in tgr-codice of tgruppi.

           move "tgruppi"      to como-file.
           call   "zoom-gt"  using como-file, tgr-rec of tgruppi
                            giving stato-zoom.
           cancel "zoom-gt".

           if stato-zoom = 0
              if old-tgr-chiave not = tgr-chiave of tgruppi
                 move tgr-chiave  of tgruppi to save-key
                 perform SALV-MOD
                 if tutto-ok
                    move save-key   to tgr-chiave of tgruppi
                    move tgr-codice of tgruppi   to ef-codice-buf
                    display ef-codice
                    set ReadSecca      to true
                    perform CURRENT-RECORD
                    perform CANCELLA-COLORE
                    move 78-ID-ef-codice to CONTROL-ID
                    move 4               to ACCEPT-CONTROL
                 end-if
              end-if
           end-if 
           .
      * <TOTEM:END>

       STAMPA.
      * <TOTEM:PARA. STAMPA>
           SET STAMPA     TO TRUE 
           .
      * <TOTEM:END>

       TORNA-IN-VISUA.
      * <TOTEM:PARA. TORNA-IN-VISUA>
           move 0 to mod.
           move 1 to mod-k.
           move 78-ID-ef-codice to CONTROL-ID.
           set NoMessage        to true.
           perform ABILITAZIONI.
           set StatusVisua to true.
           perform STATUS-BAR-MSG.
           unlock tgruppi all records.
                        
           modify tool-modifica,  value mod.
           perform CANCELLA-COLORE.
           move 4 to ACCEPT-CONTROL 
           .
      * <TOTEM:END>

       SUCCESSIVO.
      * <TOTEM:PARA. SUCCESSIVO>
           perform SALV-MOD.           
           if tutto-ok          
              perform CHECK-INSERIMENTO
              unlock tgruppi all records

              if mod = 1
                 move ZERO to mod-k
                 set dataset1-tgruppi-lock to true
              else              
                 move 1    to mod-k     
                 initialize dataset1-tgruppi-lock-flag
              end-if

              perform CANCELLA-COLORE
              perform FORM1-NEXT

              if RecLocked
                 set RecLocked to false             
                 initialize dataset1-tgruppi-lock-flag
                 move 1 to mod-k
                 perform FORM1-NEXT
              end-if
           end-if 
           .
      * <TOTEM:END>

       ULTIMO.
      * <TOTEM:PARA. ULTIMO>
           perform SALV-MOD.
           if tutto-ok
              perform CHECK-INSERIMENTO
              unlock tgruppi all records 

              if mod = 1
                 move ZERO to mod-k
                 set dataset1-tgruppi-lock to true
              else              
                 move 1    to mod-k     
                 initialize dataset1-tgruppi-lock-flag
              end-if

              perform CANCELLA-COLORE
              perform FORM1-LAST 

              if RecLocked
                 set RecLocked to false             
                 initialize dataset1-tgruppi-lock-flag
                 move 1 to mod-k
                 perform FORM1-LAST
              end-if
           end-if 
           .
      * <TOTEM:END>

       VALORIZZA-NUOVO.
      * <TOTEM:PARA. VALORIZZA-NUOVO>
           move "00" to status-tgruppi.
      
           initialize tgr-dati  of tgruppi 
                      replacing numeric data by zeroes
                           alphanumeric data by spaces 
           .
      * <TOTEM:END>

       VALORIZZA-OLD.
      * <TOTEM:PARA. VALORIZZA-OLD>
           move tgr-rec  of tgruppi to old-tgr-rec.

           set vecchio to true.

           move 0 to StatusHelp.

           perform STATUS-HELP 
           .
      * <TOTEM:END>

      * EVENT PARAGRAPH
       anagr01-Ev-After-Program.
      * <TOTEM:PARA. anagr01-Ev-After-Program>
           SET LK-BL-CANCELLAZIONE TO TRUE.
           MOVE COMO-PROG-ID       TO LK-BL-PROG-ID.
           CALL "BLOCKPGM"  USING LK-BLOCKPGM 
           .
      * <TOTEM:END>
       anagr01-Ev-Before-Program.
      * <TOTEM:PARA. anagr01-Ev-Before-Program>
           move LK-BL-PROG-ID    TO COMO-PROG-ID 
           .
      * <TOTEM:END>
       NUOVO-LinkTo.
      * <TOTEM:PARA. NUOVO-LinkTo>
           INQUIRE TOOL-NUOVO, ENABLED IN E-NUOVO.

           IF E-NUOVO = 1
              PERFORM NUOVO
           END-IF                    
           .
      * <TOTEM:END>
       CANCELLA-LinkTo.
      * <TOTEM:PARA. CANCELLA-LinkTo>
           INQUIRE TOOL-MODIFICA, VALUE IN MOD.
                              
           INQUIRE TOOL-CANCELLA, ENABLED IN E-CANCELLA
           IF E-CANCELLA = 1
              PERFORM CANCELLA
           END-IF                                                
           .
      * <TOTEM:END>
       TOOL-SALVA-LinkTo.
      * <TOTEM:PARA. TOOL-SALVA-LinkTo>
           INQUIRE TOOL-MODIFICA, VALUE IN MOD           

           INQUIRE TOOL-SALVA, ENABLED IN E-SALVA
           IF E-SALVA = 1
              PERFORM SALVA
           END-IF           
           .
      * <TOTEM:END>
       ANTEPRIMA-LinkTo.
      * <TOTEM:PARA. ANTEPRIMA-LinkTo>
           INQUIRE TOOL-ANTEPRIMA, ENABLED IN E-ANTEPRIMA.
           IF E-ANTEPRIMA = 1
                PERFORM ANTEPRIMA
           END-IF 
           .
      * <TOTEM:END>
       TOOL-MODIFICA-LinkTo.
      * <TOTEM:PARA. TOOL-MODIFICA-LinkTo>
           INQUIRE TOOL-MODIFICA, ENABLED IN E-MODIFICA.

           IF E-MODIFICA = 1
              PERFORM MODIFICA
           END-IF 
           .
      * <TOTEM:END>
       STAMPA-LinkTo.
      * <TOTEM:PARA. STAMPA-LinkTo>
           INQUIRE TOOL-STAMPA, ENABLED IN E-STAMPA

           IF E-STAMPA = 1
                PERFORM STAMPA
           END-IF 
           .
      * <TOTEM:END>
       TOOL-PRIMO.
      * <TOTEM:PARA. TOOL-PRIMO>
           PERFORM PRIMO 
           .
      * <TOTEM:END>
       TOOL-PRECEDENTE.
      * <TOTEM:PARA. TOOL-PRECEDENTE>
           if nuovo             
              perform PRIMO
           else
              perform PRECEDENTE
           end-if 
           .
      * <TOTEM:END>
       TOOL-SUCCESSIVO.
      * <TOTEM:PARA. TOOL-SUCCESSIVO>
           if nuovo             
              perform ULTIMO
           else
              perform SUCCESSIVO
           end-if 
           .
      * <TOTEM:END>
       TOOL-ULTIMO.
      * <TOTEM:PARA. TOOL-ULTIMO>
           PERFORM ULTIMO 
           .
      * <TOTEM:END>
       TOOL-SELEZIONA-LinkTo.
      * <TOTEM:PARA. TOOL-SELEZIONA-LinkTo>
           inquire tool-seleziona, enabled in e-seleziona

           if e-seleziona = 1
              perform SELEZIONA
           end-if 
           .
      * <TOTEM:END>
       TOOL-MODIFICA-BeforeProcedure.
      * <TOTEM:PARA. TOOL-MODIFICA-BeforeProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-NU
           .
      * <TOTEM:END>
       TOOL-MODIFICA-AfterProcedure.
      * <TOTEM:PARA. TOOL-MODIFICA-AfterProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-OR
           .
      * <TOTEM:END>
       ef-codice-BeforeProcedure.
      * <TOTEM:PARA. ef-codice-BeforeProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-NU
           .
      * <TOTEM:END>
       ef-des-BeforeProcedure.
      * <TOTEM:PARA. ef-des-BeforeProcedure>
           MODIFY CONTROL-HANDLE COLOR = COLORE-NU
           .
      * <TOTEM:END>
       ef-codice-AfterProcedure.
      * <TOTEM:PARA. ef-codice-AfterProcedure>
              INQUIRE ef-codice, VALUE IN tgr-codice
              SET TOTEM-CHECK-OK TO FALSE
              PERFORM ef-codice-VALIDATION
              IF NOT TOTEM-CHECK-OK
                 MOVE 1 TO ACCEPT-CONTROL
              END-IF
           MODIFY CONTROL-HANDLE COLOR = COLORE-OR

           .
      * <TOTEM:END>

       ef-des-AfterProcedure.
      * <TOTEM:PARA. ef-des-AfterProcedure>
              INQUIRE ef-descr, VALUE IN tgr-descrizione
              SET TOTEM-CHECK-OK TO FALSE
              PERFORM ef-descr-VALIDATION
              IF NOT TOTEM-CHECK-OK
                 MOVE 1 TO ACCEPT-CONTROL
              END-IF
              INQUIRE ef-email, VALUE IN tgr-email
              SET TOTEM-CHECK-OK TO FALSE
              PERFORM ef-email-VALIDATION
              IF NOT TOTEM-CHECK-OK
                 MOVE 1 TO ACCEPT-CONTROL
              END-IF
           MODIFY CONTROL-HANDLE COLOR = COLORE-OR

           .
      * <TOTEM:END>

       TOOL-CERCA-LinkTo.
      * <TOTEM:PARA. TOOL-CERCA-LinkTo>
           .
      * <TOTEM:END>

      *{TOTEM}END

      *{TOTEM}SHOW-MSG
       MESSAGE-FOR-FILEERROR.
           CALL "C$RERRNAME" USING TOTEM-MSG-ERR-FILE
           CALL "C$RERR" USING EXTEND-STAT, TEXT-MESSAGE
              MOVE PRIMARY-ERROR TO TOTEM-MSG-ID
           .

       SHOW-TRANSACTION-ROUTINE.
           IF TOTEM-TRANSACTION-FLAG = SPACES
              IF TRANSACTION-STATUS NOT = 0
                 STRING "TRANSACTION ERROR ", TRANSACTION-STATUS
                    DELIMITED BY SIZE INTO TOTEM-MSG-1
              END-IF
           ELSE
              PERFORM SHOW-MSG-ROUTINE
              IF TRANSACTION-STATUS = 0
                 MOVE "Transazione terminata con Rollback." TO 
           TOTEM-MSG-3
              ELSE
                 STRING "TRANSACTION ERROR ", TRANSACTION-STATUS
                    DELIMITED BY SIZE INTO TOTEM-MSG-3
              END-IF
           END-IF
           .

       SHOW-MSG-ROUTINE.
           MOVE SPACE TO TOTEM-MSG-1 TOTEM-MSG-2 TOTEM-MSG-3
           EVALUATE TOTEM-MSG-ID
               WHEN "10"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Nessun altro dato." TO TOTEM-MSG-2
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "22"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Chiave Duplicata." TO TOTEM-MSG-2
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "23"
                    STRING "File:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-1
                    MOVE "Raggiunta fine file." TO TOTEM-MSG-2
                    MOVE MB-WARNING-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "101"
                    MOVE "Terminare l'applicazione?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "201"
                    MOVE "Aggiungere un nuovo record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "202"
                    MOVE "Aggiornare il Record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "203"
                    MOVE "Cancellare il Record?" TO TOTEM-MSG-1
                    MOVE 4 TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-YES-NO TO TOTEM-MSG-BUTTON-TYPE
               WHEN "204"
                    MOVE "Chiave duplicata." TO TOTEM-MSG-1
                    MOVE MB-WARNING-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "301"
                    MOVE "Inserimento avvenuto con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "302"
                    MOVE "Aggiornamento avvenuto con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "303"
                    MOVE "Cancellazione avvenuta con Successo." TO 
           TOTEM-MSG-1
                    MOVE MB-DEFAULT-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN "401"
                    MOVE "Shell non trovata." TO TOTEM-MSG-1
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
               WHEN OTHER
                    MOVE TEXT-MESSAGE TO TOTEM-MSG-1
                    STRING "FILE:" TOTEM-MSG-ERR-FILE DELIMITED BY SPACE
                       INTO TOTEM-MSG-3
                    MOVE 0 TO TOTEM-IDX1
                    INSPECT TOTEM-MSG-3 TALLYING TOTEM-IDX1
                       FOR TRAILING SPACE
                    STRING TOTEM-MSG-3(1:TOTEM-MSG-LENGTH - 
           TOTEM-IDX1), 
                       ", FILE STATUS ", PRIMARY-ERROR "," 
                       SECONDARY-ERROR
                    DELIMITED BY SIZE INTO TOTEM-MSG-2
                    MOVE SPACES TO TOTEM-MSG-3
                    MOVE MB-ERROR-ICON TO TOTEM-MSG-ICON-TYPE
                    MOVE MB-OK TO TOTEM-MSG-BUTTON-TYPE
           END-EVALUATE
           PERFORM MESSAGE-BOX-ROUTINE
           .

       MESSAGE-BOX-ROUTINE.
           MOVE 1 TO TOTEM-MSG-TEXT-POINTER
           IF TOTEM-MSG-1 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-1 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              STRING TOTEM-MSG-1( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                 DELIMITED BY SIZE
                 INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-2 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-2 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              IF TOTEM-MSG-TEXT-POINTER > 1
                 STRING X"0A" DELIMITED BY SIZE
                     INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
              END-IF
              STRING TOTEM-MSG-2( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                  DELIMITED BY SIZE
                  INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-3 NOT = SPACE
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-3 TALLYING TOTEM-MSG-SIZE FOR TRAILING 
           SPACE
              IF TOTEM-MSG-TEXT-POINTER > 1
                 STRING X"0A" DELIMITED BY SIZE
                     INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
              END-IF
              STRING TOTEM-MSG-3( 1 : TOTEM-MSG-LENGTH - TOTEM-MSG-SIZE 
           )
                  DELIMITED BY SIZE
                  INTO TOTEM-MSG-TEXT, POINTER TOTEM-MSG-TEXT-POINTER
           END-IF

           IF TOTEM-MSG-TEXT-POINTER = 1
              MOVE 0 TO TOTEM-MSG-SIZE
              INSPECT TOTEM-MSG-TEXT TALLYING TOTEM-MSG-SIZE FOR 
           TRAILING SPACE
                  COMPUTE TOTEM-MSG-TEXT-POINTER = 
           TOTEM-MSG-FULL-LENGTH - TOTEM-MSG-SIZE + 1
           END-IF
           MOVE LOW-VALUES TO TOTEM-MSG-TEXT(TOTEM-MSG-TEXT-POINTER : 1 
           )
           .

       MESSAGE-BOX-DISPLAY.
           PERFORM SHOW-MSG-ROUTINE
           PERFORM MESSAGE-BOX-ROUTINE
           DISPLAY MESSAGE BOX TOTEM-MSG-TEXT
               TITLE IS TOTEM-MSG-TITLE
               TYPE  IS TOTEM-MSG-BUTTON-TYPE
               ICON  IS TOTEM-MSG-DEFAULT-BUTTON
               RETURNING TOTEM-MSG-RETURN-VALUE
           .

      *{TOTEM}END

