       SELECT OPTIONAL ART ASSIGN RANDOM "ART"
           COMPRESSION 80
           ORGANIZATION INDEXED ACCESS DYNAMIC RECORD ART-CODICE
           ALTERNATE RECORD ART-CODICE1 = ART-CODICE-ALTERNATIVO 
                                          ART-CODICE
           ALTERNATE RECORD ART-CODICE2 = ART-DESCRIZIONE1 ART-CODICE
           ALTERNATE RECORD ART-CODICE3 = ART-CODICE-CM ART-CODICE
           ALTERNATE RECORD ART-CODICE4 = ART-CODICE-ME ART-CODICE
           ALTERNATE RECORD ART-CODICE5 = ART-CODICE-IN ART-CODICE                   
           FILE STATUS IS STATO.




























