       SELECT OPTIONAL ART
           ASSIGN       TO RANDOM "ART"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS status-art
           RECORD KEY   IS ART-CODICE-G2
           ALTERNATE RECORD KEY IS ART-CODICE1 = 
           ART-CODICE-ALTERNATIVO, ART-CODICE-G2
           ALTERNATE RECORD KEY IS ART-CODICE2 = ART-DESCRIZIONE1-G2, 
           ART-CODICE-G2
           ALTERNATE RECORD KEY IS ART-CODICE3 = ART-CODICE-CM, 
           ART-CODICE-G2
           ALTERNATE RECORD KEY IS ART-CODICE4 = ART-CODICE-ME, 
           ART-CODICE-G2
           ALTERNATE RECORD KEY IS ART-CODICE5 = ART-CODICE-IN, 
           ART-CODICE-G2.
