       SELECT OPTIONAL CLI
           ASSIGN       TO RANDOM "CLI"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-CLI
           RECORD KEY   IS CLI-CODICE-G2
           ALTERNATE RECORD KEY IS CLI-CODICE1 = 
           CLI-CODICE-ALTERNATIVO, CLI-CODICE-G2
           ALTERNATE RECORD KEY IS CLI-CODICE2 = CLI-DESCRIZIONE1, 
           CLI-CODICE-G2
           ALTERNATE RECORD KEY IS CLI-CODICE3 = CLI-PARTITA-IVA, 
           CLI-CODICE-G2
           ALTERNATE RECORD KEY IS CLI-CODICE4 = CLI-CODICE-FISCALE, 
           CLI-CODICE-G2.
