       SELECT OPTIONAL DOCDI
           ASSIGN       TO RANDOM "DOC"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-DOCDI
           RECORD KEY   IS DOCDI-CODICE.
