       SELECT OPTIONAL FRZ
           ASSIGN       TO RANDOM SELFRZ
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-FRZ
           RECORD KEY   IS FRZ-CODICE.
