       SELECT OPTIONAL MAZ
           ASSIGN       TO RANDOM SELMAZ
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-MAZ
           RECORD KEY   IS MAZ-CODICE.
