       SELECT OPTIONAL DVR
           ASSIGN       TO RANDOM "DVR"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-DVR
           RECORD KEY   IS DVR-CODICE
           ALTERNATE RECORD KEY IS DVR-CODICE1 = DVR-DATA-DOCUMENTO, 
           DVR-DOCUMENTO, DVR-CODICE
           ALTERNATE RECORD KEY IS DVR-CODICE2 = DVR-CODICE-CONTO, 
           DVR-DATA-DOCUMENTO, DVR-CODICE
           ALTERNATE RECORD KEY IS DVR-CODICE3 = DVR-CODICE-ART, 
           DVR-DATA-DOCUMENTO, DVR-CODICE.
