       SELECT OPTIONAL DVT
           ASSIGN       TO RANDOM "DVT"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-DVT
           RECORD KEY   IS DVT-CODICE
           ALTERNATE RECORD KEY IS DVT-CODICE1 = DVT-CODICE-CONTO, 
           DVT-DATA-DOCUMENTO, DVT-CODICE
           ALTERNATE RECORD KEY IS DVT-CODICE2 = DVT-DOCUMENTO, 
           DVT-DATA-DOCUMENTO, DVT-CODICE
           ALTERNATE RECORD KEY IS DVT-CODICE3 = DVT-FATTURA, 
           DVT-DATA-FATTURA, DVT-CODICE
           ALTERNATE RECORD KEY IS DVT-CODICE4 = DVT-PROTOCOLLO, 
           DVT-DATA-PROTOCOLLO, DVT-CODICE
           ALTERNATE RECORD KEY IS DVT-CODICE5 = DVT-DATA-DOCUMENTO, 
           DVT-DOCUMENTO, DVT-CODICE.
