      *
      *
      * 
      *-
      *2
       SELECT OPTIONAL PAS
           ASSIGN       TO RANDOM "PAS"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-PAS
           RECORD KEY   IS PAS-CODICE
           ALTERNATE RECORD KEY IS PAS-CODICE1 = PAS-DATA-SCADENZA, 
           PAS-CODICE
           ALTERNATE RECORD KEY IS PAS-CODICE2 = PAS-CODICE-CONTO, 
           PAS-DATA-SCADENZA, PAS-CODICE
           ALTERNATE RECORD KEY IS PAS-CODICE3 = PAS-CODICE-CONTO, 
           PAS-DATA-RIFERIMENTO, PAS-NUMERO-RIFERIMENTO, PAS-CODICE
           ALTERNATE RECORD KEY IS PAS-CODICE4 = PAS-CODICE-CONTO, 
           PAS-SITUAZIONE, PAS-DATA-SCADENZA, PAS-CODICE.
