       SELECT OPTIONAL PAT
           ASSIGN       TO RANDOM "PAT"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-PAT
           RECORD KEY   IS PAT-CODICE
           ALTERNATE RECORD KEY IS PAT-CODICE1 = PAT-CODICE-CONTO, 
           PAT-DATA-RIFERIMENTO, PAT-NUMERO-RIFERIMENTO, PAT-CODICE.
