       SELECT OPTIONAL PNI
           ASSIGN       TO RANDOM "PNI"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-PNI
           RECORD KEY   IS PNI-CODICE.
