       SELECT OPTIONAL PNR
           ASSIGN       TO RANDOM "PNR"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-PNR
           RECORD KEY   IS PNR-CODICE
           ALTERNATE RECORD KEY IS PNR-CODICE1 = PNR-CODICE-CONTO, 
           PNR-ESERCIZIO, PNR-DATA-REGISTRAZIONE, PNR-CODICE.
