       SELECT OPTIONAL STA
           ASSIGN       TO RANDOM "STA"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-STA
           RECORD KEY   IS STA-CODICE
           ALTERNATE RECORD KEY IS STA-CODICE1 = STA-CODICE-FRN, 
           STA-DATA-FATTURA, STA-CODICE
           ALTERNATE RECORD KEY IS STA-CODICE2 = STA-CODICE-ART, 
           STA-DATA-FATTURA, STA-CODICE
           ALTERNATE RECORD KEY IS STA-CODICE3 = STA-DATA-FATTURA, 
           STA-CODICE
           ALTERNATE RECORD KEY IS STA-CODICE4 = STA-CODICE-FRN, 
           STA-CODICE-ART, STA-DATA-FATTURA, STA-CODICE.
