       SELECT OPTIONAL TBLDO
           ASSIGN       TO RANDOM "TBLDO"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS STATUS-TBLDO
           RECORD KEY   IS TBLDO-CODICE
           ALTERNATE RECORD KEY IS TBLDO-CODICE-01 = TBLDO-CODICE1, 
           TBLDO-DESCRIZIONE1, TBLDO-CODICE2.
