       SELECT OPTIONAL TBLTR
           ASSIGN       TO RANDOM "TBLTR"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS status-tbltr
           RECORD KEY   IS TBLTR-CODICE
           ALTERNATE RECORD KEY IS TBL-CODICE-01 = TBLTR-CODICE1, 
           TBLTR-DESCRIZIONE1, TBLTR-CODICE2.
